-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2016                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

CONNECT TO PEOPLEDB@

-- grant connect

GRANT CONNECT ON DATABASE TO USER LCUSER@

-- grants for Profiles tables

GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.GIVEN_NAME TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.SURNAME TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_EXTENSIONS TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_EXT_DRAFT TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PEOPLE_TAG TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.DEPARTMENT TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.ORGANIZATION TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.COUNTRY TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_TYPE TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMPLOYEE TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PHOTO TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PHOTOBKUP TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PHOTO_GUID TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PRONUNCIATION TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.WORKLOC TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_DRAFT TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.CHG_EMP_DRAFT  TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROF_CONNECTIONS TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.SNPROF_SCHEMA TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROF_CONSTANTS TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EVENTLOG TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_LOGIN TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_PREFS TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_LAST_LOGIN TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.USER_PLATFORM_EVENTS TO USER LCUSER@
--GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.USER_PLATFORM_EVENTS_INDEX TO USER LCUSER@
GRANT USAGE ON SEQUENCE EMPINST.USER_PLATFORM_EVENT_INDEX_SEQ TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.TENANT TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_ROLE_MAP TO USER LCUSER@
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_UPDATE_TIMESTAMP TO USER LCUSER@


GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_TASK TO USER LCUSER@
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_LMGR TO USER LCUSER@
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_LMPR TO USER LCUSER@
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_TREG TO USER LCUSER@

COMMIT@

CONNECT RESET@
