-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

-- FIXUP11A.SQL AND MigrateEmployeeTable JAVA PROGRAM MUST BE RUN BEFORE THIS SCRIPT

--- step 4b: add constraints on new  table
--- keep the following stmt in sync with postdbxfer.sql

SET INTEGRITY FOR EMPINST.EMPLOYEE OFF@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_MAIL_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_MAIL))@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_LOGIN_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_LOGIN))@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_GW_EMAIL_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_GROUPWARE_EMAIL))@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_UID_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_UID))@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_MANAGER_UID_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_MANAGER_UID))@ 
SET INTEGRITY FOR EMPINST.EMPLOYEE IMMEDIATE CHECKED FORCE GENERATED@ 
COMMIT@


{include.msgVector-postdbxfer.sql}


--- step 5: drop temp table

DROP TABLE "EMPINST"."EMPLOYEE_T"@
COMMIT@


--- step 6: create triggers/indices new table
--- keep the following stmts in sync with createdb.sql
-- DDL Statements for indexes on Table "EMPINST"."EMPLOYEE"

CREATE INDEX "EMPINST"."EMP_GUID_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_GUID" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."EMP_UID_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_UID" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."MAIL_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_MAIL" ASC) ALLOW REVERSE SCANS@	

CREATE INDEX "EMPINST"."MAIL_LOWER_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_MAIL_LOWER" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."UID_LOWER_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_UID_LOWER" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."GW_EMAIL_LOWER_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_GW_EMAIL_LOWER" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PREF_FNX" ON "EMPINST"."EMPLOYEE" 
		("PROF_PREFERRED_FIRST_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PREF_LNX" ON "EMPINST"."EMPLOYEE" 
		("PROF_PREFERRED_LAST_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."DISPNMX" ON "EMPINST"."EMPLOYEE" 
		("PROF_DISPLAY_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."MGRIDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_MANAGER_UID" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."GRPEMAIL_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_GROUPWARE_EMAIL" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."JOB_RESP_UID_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_JOB_RESPONSIBILITIES", "PROF_KEY")@

CREATE INDEX "EMPINST"."ORG_UID_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_ORGANIZATION_IDENTIFIER", "PROF_KEY")@

CREATE INDEX "EMPINST"."COUNTRY_UID_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_ISO_COUNTRY_CODE", "PROF_KEY")@
		
CREATE INDEX "EMPINST"."FAX_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_FAX_TELEPHONE_NUMBER" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."IPPHONE_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_IP_TELEPHONE_NUMBER" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."MOBILE_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_MOBILE" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PAGER_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_PAGER" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PHONE_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_TELEPHONE_NUMBER" ASC) ALLOW REVERSE SCANS@
                
CREATE INDEX "EMPINST"."WORKLOC_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_WORK_LOCATION" ASC) ALLOW REVERSE SCANS@
                           
CREATE INDEX "EMPINST"."LOGIN_LOWER_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_LOGIN_LOWER" ASC) ALLOW REVERSE SCANS@
                           

CREATE INDEX "EMPINST"."MANAGER_UID_LOWER_IDX" ON "EMPINST"."EMPLOYEE"
                ("PROF_MANAGER_UID_LOWER" ASC) ALLOW REVERSE SCANS@
COMMIT@
		
-- DDL Statements for triggers on Table "EMPINST"."EMPLOYEE"

CREATE TRIGGER "EMPINST"."T_EMPLOYEE_INSRT" NO CASCADE BEFORE INSERT ON "EMPINST"."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST"."T_EMPLOYEE_UPDT" NO CASCADE BEFORE UPDATE ON "EMPINST"."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

COMMIT@


------------------------------------------------
-- DDL Statements for view "EMPINST"."SNCORE_PERSON"
------------------------------------------------

CREATE VIEW EMPINST.SNCORE_PERSON (SNC_INTERNAL_ID, SNC_IDKEY, SNC_EMAIL_LOWER, SNC_DISPLAY_NAME)
  	AS SELECT PROF_KEY, PROF_GUID, PROF_MAIL_LOWER, PROF_DISPLAY_NAME FROM EMPINST.EMPLOYEE@


------------------------------------------------
-- DDL Statements for table "EMPINST"."GIVEN_NAME"
------------------------------------------------

ALTER TABLE "EMPINST"."GIVEN_NAME" ADD COLUMN "PROF_NAME_SOURCE" INTEGER DEFAULT 0@


------------------------------------------------
-- DDL Statements for table "EMPINST"."SURNAME"
------------------------------------------------

ALTER TABLE "EMPINST"."SURNAME" ADD COLUMN "PROF_NAME_SOURCE" INTEGER DEFAULT 0@


------------------------------------------------
-- DDL Statements for table "EMPINST"."PROF_CONNECTIONS"
------------------------------------------------

CREATE INDEX "EMPINST"."CONN_TARGET_IDX" ON "EMPINST"."PROF_CONNECTIONS" 
	("PROF_TARGET_KEY" ASC, "PROF_STATUS" ASC, "PROF_TYPE" ASC) ALLOW REVERSE SCANS@

------------------------------------------------
-- DDL Statements for view "EMPINST"."EVENTLOG"
------------------------------------------------

CREATE TABLE EMPINST.EVENTLOG (
	"EVENT_KEY" 				VARCHAR(36) NOT NULL, 
	"EVENT_SOURCE" 				VARCHAR(36) NOT NULL, 
	"OBJECT_KEY"				VARCHAR(36) NOT NULL,
	"EVENT_NAME"				VARCHAR(128) NOT NULL, 
	"EVENT_TYPE"				INTEGER NOT NULL DEFAULT -1, 
	"CREATED" 				TIMESTAMP NOT NULL,
	"CREATED_BY_KEY"			VARCHAR(36) NOT NULL,
	"CREATED_BY_GUID"			VARCHAR(256) NOT NULL, 
	"CREATED_BY_UID"			VARCHAR(256) NOT NULL, 
	"CREATED_BY_NAME"			VARCHAR(128),
	"ISPRIVATE"				SMALLINT DEFAULT 0,
	"ISSYSEVENT"				SMALLINT DEFAULT 0,
	"EVENT_METADATA"			CLOB(2 M) LOGGED COMPACT,
	CONSTRAINT "PK" PRIMARY KEY ("EVENT_KEY")
) IN USERSPACE4K INDEX IN USERSPACE4K@

CREATE INDEX "EMPINST"."EVLOG_TYPE_IDX" ON EMPINST.EVENTLOG ("CREATED" ASC, "EVENT_TYPE" ASC) ALLOW REVERSE SCANS@



-- Update schema version
UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 11 WHERE COMPKEY='Profiles'@

COMMIT@
CONNECT RESET@
