-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

-- add column: see sn.homepage\lwp\dboard.sn.install\scripts\db\<dbtype>\fixup\fixup12.sql

-- NOTE: Any changes here are to also reflected in upgrade-301-40b2.sql (until b2 is finalized)

------
-- TENANT: create table, add constraitns, indexes
------
-- create TENANT table

CREATE TABLE "EMPINST"."TENANT"  (
	"TENANT_KEY" VARCHAR(36) NOT NULL,
	"TENANT_EXID" VARCHAR(256) NOT NULL,
	"TENANT_NAME"  VARCHAR(256) NOT NULL,
	"TENANT_NAME_LOWER"  VARCHAR(256) NOT NULL,
	"TENANT_STATE" SMALLINT NOT NULL,
	"TENANT_CREATED" TIMESTAMP NOT NULL,
	--"TENANT_CREATED_BY_KEY" VARCHAR(36) NOT NULL,
	"TENANT_LASTUPDATE" TIMESTAMP NOT NULL,
	--"TENANT_LASTMOD_BY_KEY" VARCHAR(36) NOT NULL,
	CONSTRAINT "TENANT_PK" PRIMARY KEY ("TENANT_KEY")
)
	IN "USERSPACE32K" INDEX IN USERSPACE4K @


-- TENANT constaints
CREATE UNIQUE INDEX "EMPINST"."TENANT_EXID_UDX" ON "EMPINST"."TENANT"
		("TENANT_EXID" ASC) ALLOW REVERSE SCANS @

-- insert standard tenant
INSERT INTO EMPINST.TENANT(
	TENANT_KEY           ,
	TENANT_EXID          ,
	TENANT_NAME          ,
	TENANT_NAME_LOWER    ,
	TENANT_STATE         ,
	TENANT_CREATED       ,
	--TENANT_CREATED_BY_KEY,
	TENANT_LASTUPDATE
	--TENANT_LASTMOD_BY_KEY
)
VALUES(
	'00000000-0000-0000-0000-040508202233',
	'standard_tenant_guid',
	'Default Tenant',
	'default tenant',
	0,
	CURRENT_TIMESTAMP,
	-- no admin,
	CURRENT_TIMESTAMP
	-- no admin
)@

------
-- EMPLOYEE: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EMPLOYEE
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPPROF_TENT_UK  UNIQUE (PROF_KEY, TENANT_KEY)@

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- GIVEN_NAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.GIVEN_NAME
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GVNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- SURNAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.SURNAME
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- DEPARTMENT: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.DEPARTMENT
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@
	
ALTER TABLE EMPINST.DEPARTMENT DROP PRIMARY KEY@

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY (TENANT_KEY, PROF_DEPARTMENT_CODE)@

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPT_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- ORGANIZATION: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.ORGANIZATION
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.ORGANIZATION DROP PRIMARY KEY@

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_PK PRIMARY KEY (TENANT_KEY, PROF_ORGANIZATION_CODE)@

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- COUNTRY: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.COUNTRY
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.COUNTRY DROP PRIMARY KEY@

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (TENANT_KEY, PROF_ISO_COUNTRY_CODE)@

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT CNTRY_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- EMP_TYPE: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EMP_TYPE
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.EMP_TYPE DROP PRIMARY KEY@

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_PK PRIMARY KEY (TENANT_KEY, PROF_EMPLOYEE_TYPE)@

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- WORKLOC: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.WORKLOC
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.WORKLOC DROP PRIMARY KEY@

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_PK PRIMARY KEY (TENANT_KEY, PROF_WORK_LOC)@

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- EVENTLOG: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EVENTLOG
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVLOG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- PROFILE_LOGIN: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_LOGIN
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT LOGIN_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

DROP INDEX EMPINST.LOGIN_UDX@

CREATE UNIQUE INDEX EMPINST.LOGIN_UDX ON EMPINST.PROFILE_LOGIN (PROF_LOGIN,TENANT_KEY)@	

------
-- USER_PLATFORM_EVENTS: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT UPLTEV_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@


-- Update schema versions

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 31, RELEASEVER='4.0.0.0' WHERE COMPKEY='Profiles'@

COMMIT@

CONNECT RESET@
