-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

-- Restore generated expressions after importing data into database
SET INTEGRITY FOR EMPINST.EMPLOYEE OFF@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_MAIL_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_MAIL))@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_LOGIN_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_LOGIN))@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_GW_EMAIL_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_GROUPWARE_EMAIL))@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_UID_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_UID))@ 
SET INTEGRITY FOR EMPINST.EMPLOYEE IMMEDIATE CHECKED FORCE GENERATED@ 

CREATE TRIGGER "EMPINST "."T_EXT_DRAFT_SEQ" NO CASCADE BEFORE INSERT ON "EMPINST "."PROFILE_EXT_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL             
		 SET N.PROF_UPDATE_SEQUENCE = NEXTVAL FOR "EMPINST "."EXT_DRAFT_SEQ"@  

CREATE TRIGGER "EMPINST "."T_EMPLOYEE_INSRT" NO CASCADE BEFORE INSERT ON "EMPINST "."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST "."T_EMPLOYEE_UPDT" NO CASCADE BEFORE UPDATE ON "EMPINST "."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST "."T_PHOTO_INSRT" NO CASCADE BEFORE INSERT ON "EMPINST "."PHOTO" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATED = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST "."T_PHOTO_UPDT" NO CASCADE BEFORE UPDATE ON "EMPINST "."PHOTO" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATED = CURRENT TIMESTAMP@


CREATE TRIGGER "EMPINST "."T_PRONOUNCE_INSRT" NO CASCADE BEFORE INSERT ON "EMPINST "."PRONUNCIATION" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATED = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST "."T_PRONOUNCE_UPDT" NO CASCADE BEFORE UPDATE ON "EMPINST "."PRONUNCIATION" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATED = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST "."T_EMP_DRAFT_SEQ" NO CASCADE BEFORE INSERT ON "EMPINST "."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATE_SEQUENCE = NEXTVAL FOR "EMPINST "."EMP_DRAFT_SEQ"@

CREATE TRIGGER "EMPINST "."T_EMP_INS" AFTER INSERT ON "EMPINST "."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO "EMPINST "."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST "."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'I', N.PROF_UPDATE_SEQUENCE, N.PROF_UID )@

CREATE TRIGGER "EMPINST "."T_EMP_DEL" AFTER DELETE ON "EMPINST "."EMP_DRAFT" REFERENCING OLD AS N 
	FOR EACH ROW MODE DB2SQL
		 INSERT INTO "EMPINST "."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST "."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'D', N.PROF_UPDATE_SEQUENCE, N.PROF_UID )@

CREATE TRIGGER "EMPINST "."T_EMP_UPD" AFTER UPDATE ON "EMPINST "."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO "EMPINST "."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST "."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'U', N.PROF_UPDATE_SEQUENCE, N.PROF_UID )@

COMMIT@
CONNECT RESET@
