-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

 
CREATE TRIGGER EMPINST.T_EXT_DRAFT_SEQ NO CASCADE BEFORE INSERT ON EMPINST.PROFILE_EXT_DRAFT REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATE_SEQUENCE = NEXTVAL FOR EMPINST.EXT_DRAFT_SEQ@

CREATE TRIGGER EMPINST.T_EMP_DRAFT_SEQ NO CASCADE BEFORE INSERT ON EMPINST.EMP_DRAFT REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATE_SEQUENCE = NEXTVAL FOR EMPINST.EMP_DRAFT_SEQ@

CREATE TRIGGER EMPINST.T_EMP_INS AFTER INSERT ON EMPINST.EMP_DRAFT REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO EMPINST.CHG_EMP_DRAFT VALUES (NEXTVAL FOR EMPINST.CHG_EMP_DRAFT_SEQ, 0, 
			CURRENT_DATE, 'I', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY, N.TENANT_KEY )@

CREATE TRIGGER EMPINST.T_EMP_DEL AFTER DELETE ON EMPINST.EMP_DRAFT REFERENCING OLD AS N 
	FOR EACH ROW MODE DB2SQL
		 INSERT INTO EMPINST.CHG_EMP_DRAFT VALUES (NEXTVAL FOR EMPINST.CHG_EMP_DRAFT_SEQ, 0, 
			CURRENT_DATE, 'D', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY, N.TENANT_KEY )@

CREATE TRIGGER EMPINST.T_EMP_UPD AFTER UPDATE ON EMPINST.EMP_DRAFT REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO EMPINST.CHG_EMP_DRAFT VALUES (NEXTVAL FOR EMPINST.CHG_EMP_DRAFT_SEQ, 0, 
			CURRENT_DATE, 'U', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY, N.TENANT_KEY)@

COMMIT@

--
--- Foreign keys for tenant
--
ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GVNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROFEXT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT PREXTDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PEOPLE_TAG ADD CONSTRAINT PPLTAG_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPT_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT CNTRY_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNC_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMPDRAFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.CHG_EMP_DRAFT ADD CONSTRAINT CHEMPDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVLOG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT LOGIN_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFPREF_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT UPLTEV_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

COMMIT@

{include.msgVector-postdbxfer301.sql}

{include.dynattr-postdbxfer30.sql}

COMMIT@
CONNECT RESET@

