-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2016                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

RUNSTATS ON TABLE EMPINST.SNPROF_SCHEMA WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.GIVEN_NAME WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.SURNAME WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.DEPARTMENT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.ORGANIZATION WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PHOTO WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PHOTO_GUID WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PHOTOBKUP WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PRONUNCIATION WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.WORKLOC WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.EMPLOYEE WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.COUNTRY WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILE_EXTENSIONS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILE_EXT_DRAFT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PEOPLE_TAG WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.EMP_TYPE WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.EMP_DRAFT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.CHG_EMP_DRAFT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROF_CONNECTIONS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROF_CONSTANTS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.EVENTLOG WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILE_LOGIN WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILE_PREFS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILE_LAST_LOGIN WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.TENANT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.EMP_ROLE_MAP WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.EMP_UPDATE_TIMESTAMP WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@

RUNSTATS ON TABLE EMPINST.USER_PLATFORM_EVENTS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
--RUNSTATS ON TABLE EMPINST.USER_PLATFORM_EVENTS_INDEX WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILES_SCHEDULER_TASK WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILES_SCHEDULER_LMGR WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILES_SCHEDULER_LMPR WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@
RUNSTATS ON TABLE EMPINST.PROFILES_SCHEDULER_TREG WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS@

COMMIT@

CONNECT RESET@
