-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@


!db2set DB2_INLIST_TO_NLJN=YES@
!db2set DB2_EVALUNCOMMITTED=YES@

------------------------------------------------
-- DDL Statements for view "EMPINST"."EMPLOYEE"
------------------------------------------------

CREATE INDEX "EMPINST"."PROF_DISP_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_KEY" ASC, "PROF_DISPLAY_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PROF_SNGN_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_KEY" ASC, "PROF_SURNAME" ASC, "PROF_GIVEN_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PROF_GN2_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_GIVEN_NAME" ASC, "PROF_KEY" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PROF_SN2_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_SURNAME" ASC, "PROF_KEY" ASC) ALLOW REVERSE SCANS@

ALTER TABLE "EMPINST"."EMPLOYEE" ALTER COLUMN "PROF_DEPARTMENT_NUMBER" SET DATA TYPE VARCHAR (24)@

COMMIT@
		
-- DDL Statements for triggers on Table "EMPINST"."EMPLOYEE"

DROP TRIGGER "EMPINST"."T_EMPLOYEE_INSRT"@

DROP TRIGGER "EMPINST"."T_EMPLOYEE_UPDT"@
COMMIT@

CREATE TRIGGER "EMPINST"."T_EMPLOYEE_INSRT" NO CASCADE BEFORE INSERT ON "EMPINST"."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST"."T_EMPLOYEE_UPDT" NO CASCADE BEFORE UPDATE ON "EMPINST"."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

COMMIT@

------------------------------------------------
-- DDL Statements for table "EMPINST"."SURNAME"
------------------------------------------------

DROP INDEX EMPINST.SURNAME_UDX@

DROP INDEX EMPINST.SURNAME_IDX@

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_PK PRIMARY KEY (PROF_KEY, PROF_SURNAME)@

CREATE INDEX EMPINST.SURNAME_IDX ON EMPINST.SURNAME (PROF_SURNAME ASC, PROF_KEY ASC)@


------------------------------------------------
-- DDL Statements for table "EMPINST"."GIVEN_NAME"
------------------------------------------------

DROP INDEX EMPINST.GIVEN_NAME_UDX@

DROP INDEX EMPINST.GIVEN_NAME_IDX@

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GIVEN_NAME_PK PRIMARY KEY (PROF_KEY, PROF_GIVENNAME)@

CREATE INDEX EMPINST.GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME (PROF_GIVENNAME ASC, PROF_KEY ASC)@
COMMIT@
		 

------------------------------------------------
-- DDL Statements for table EMPINST."PROFILE_EXT_DRAFT
------------------------------------------------

DROP INDEX EMPINST.EXT_DRAFT_PK @

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT EXT_DRAFT_PK PRIMARY KEY (PROF_KEY, PROF_UPDATE_SEQUENCE)@


------------------------------------------------
-- DDL Statements for table EMPINST.PROFILE_EXTENSIONS
------------------------------------------------

DROP INDEX EMPINST.PROFILE_EXTENSIONS_UDX@

ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROFILE_EXT_PK PRIMARY KEY (PROF_KEY, PROF_PROPERTY_ID)@


------------------------------------------------
-- DDL Statements for table "EMPINST"."DEPARTMENT"
------------------------------------------------

ALTER TABLE "EMPINST"."DEPARTMENT" ALTER COLUMN "PROF_DEPARTMENT_CODE" SET DATA TYPE VARCHAR (24)@

COMMIT@
	

------------------------------------------------
-- DDL Statements for table "EMPINST"."PRONUNCIATION"
------------------------------------------------

ALTER TABLE "EMPINST"."PRONUNCIATION" ADD COLUMN "PROF_FILE_TYPE" VARCHAR (50) NOT NULL DEFAULT 'audio/wav'@
	 
------------------------------------------------
-- DDL Statements for table "EMPINST"."USER_PLATFORM_EVENTS"
------------------------------------------------

CREATE TABLE "EMPINST"."USER_PLATFORM_EVENTS"  (
	"EVENT_KEY" BIGINT NOT NULL, 
	"EVENT_TYPE" VARCHAR(36) NOT NULL,
	"PAYLOAD" CLOB(100K) LOGGED COMPACT,
	"CREATED" TIMESTAMP NOT NULL,
	CONSTRAINT "PLATFORM_EVENTS_PK" PRIMARY KEY ("EVENT_KEY") 
) IN USERSPACE4K INDEX IN USERSPACE4K@

	
CREATE SEQUENCE "EMPINST"."USER_PLATFORM_EVENT_INDEX_SEQ"
	START WITH 0
	INCREMENT BY 1
	NO MAXVALUE
	NO CYCLE
	CACHE 20@


-------------------------------------------------------------------
-- START ADDING SCHEDULER TABLES
-------------------------------------------------------------------

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TASK" (
	TASKID BIGINT NOT NULL,
	VERSION VARCHAR(5) NOT NULL,
	ROW_VERSION INTEGER NOT NULL,
	TASKTYPE INTEGER NOT NULL,
	TASKSUSPENDED SMALLINT NOT NULL,
	CANCELLED SMALLINT NOT NULL,
	NEXTFIRETIME BIGINT NOT NULL,
	STARTBYINTERVAL VARCHAR(254),
	STARTBYTIME BIGINT,
	VALIDFROMTIME BIGINT,
	VALIDTOTIME BIGINT,
	REPEATINTERVAL VARCHAR(254),
	MAXREPEATS INTEGER NOT NULL,
	REPEATSLEFT INTEGER NOT NULL,
	TASKINFO BLOB(102400) LOGGED NOT COMPACT,
	NAME VARCHAR(254) NOT NULL,
	AUTOPURGE INTEGER NOT NULL,
	FAILUREACTION INTEGER,
	MAXATTEMPTS INTEGER,
	QOS INTEGER,
	PARTITIONID INTEGER,
	OWNERTOKEN VARCHAR(200) NOT NULL,
	CREATETIME BIGINT NOT NULL
) 
IN USERSPACE4K INDEX IN USERSPACE4K@

ALTER TABLE "EMPINST".PROFILES_SCHEDULER_TASK 
	ADD PRIMARY KEY (TASKID)@

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX1 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" (TASKID, OWNERTOKEN)@

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX2 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" (NEXTFIRETIME ASC, REPEATSLEFT, PARTITIONID) CLUSTER@

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TREG" (
	REGKEY VARCHAR(254) NOT NULL,
	REGVALUE VARCHAR(254) 
) 
IN USERSPACE4K INDEX IN USERSPACE4K@

ALTER TABLE "EMPINST".PROFILES_SCHEDULER_TREG 
	ADD PRIMARY KEY (REGKEY)@

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMGR" (
	LEASENAME VARCHAR(254) NOT NULL,
	LEASEOWNER VARCHAR(254) NOT NULL,
	LEASE_EXPIRE_TIME  BIGINT,
	DISABLED VARCHAR(5)
)
IN USERSPACE4K INDEX IN USERSPACE4K@

ALTER TABLE "EMPINST"."PROFILES_SCHEDULER_LMGR"
	ADD PRIMARY KEY (LEASENAME)@

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMPR" (
	LEASENAME VARCHAR(254) NOT NULL,
	NAME VARCHAR(254) NOT NULL,
	VALUE VARCHAR(254) NOT NULL
)
IN USERSPACE4K INDEX IN USERSPACE4K@

CREATE INDEX "EMPINST"."PROFILES_SCHEDULER_LMPR_IDX1 "
	ON "EMPINST"."PROFILES_SCHEDULER_LMPR" (LEASENAME, NAME)@

-------------------------------------------------------------------
-- END ADDING SCHEDULER TABLES
-------------------------------------------------------------------

------------------------------------------------
-- Stuff to create external index dynattr
------------------------------------------------

{include.createDynaDefs.sql}

--
-- User state look aside index table
--
CREATE TABLE EMPINST.USER_STATE_LAIDX (
 DEFID    CHAR(16) FOR BIT DATA NOT NULL,
 IDXID    CHAR(16) FOR BIT DATA NOT NULL,
 USRSTATE   INTEGER NOT NULL,
 USRSTATE_UPDATED TIMESTAMP NOT NULL,
 OBJID    CHAR(16) FOR BIT DATA NOT NULL,
 OBJIDSTR   CHAR(36) NOT NULL,
 CONSTRAINT PK PRIMARY KEY (IDXID)
) IN USERSPACE4K INDEX IN USERSPACE4K@

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_DEF_FK FOREIGN KEY (DEFID) 
 REFERENCES EMPINST.DYNA_DEFS(DEFID)
 ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_OBJ_FK FOREIGN KEY (OBJID) 
	REFERENCES EMPINST.DYNA_OBJ_REF(OBJID)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

--
-- Constrain to one value per user
--
CREATE UNIQUE INDEX USRSTATE_CONS_VALB 
	ON EMPINST.USER_STATE_LAIDX (OBJID ASC)
	INCLUDE (OBJIDSTR, USRSTATE, USRSTATE_UPDATED)
	ALLOW REVERSE SCANS@
	
CREATE UNIQUE INDEX USRSTATE_CONS_VALS 
	ON EMPINST.USER_STATE_LAIDX (OBJIDSTR ASC)
	INCLUDE (OBJID, USRSTATE, USRSTATE_UPDATED)
	ALLOW REVERSE SCANS@

--
-- Main index for scanning
--
CREATE INDEX USRSTATE_IDX
	ON EMPINST.USER_STATE_LAIDX (USRSTATE ASC, USRSTATE_UPDATED ASC, OBJID ASC, OBJIDSTR ASC)
	ALLOW REVERSE SCANS@
-- Update schema versions

-- ==========================================================
-- Updates to the board
-- ==========================================================
{include.msgVector-fixup5.sql}

-- Add state field for lookaside index tables
INSERT INTO EMPINST.PROF_CONSTANTS VALUES ('LA_IDX_STATE', 'inconsistent')@

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 27, RELEASEVER='3.0.0.0' WHERE COMPKEY='Profiles'@

COMMIT@
CONNECT RESET@
