-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@


!db2set DB2_INLIST_TO_NLJN=YES@
!db2set DB2_EVALUNCOMMITTED=YES@

------------------------------------------------
-- DDL Statements for view "EMPINST"."EMPLOYEE"
------------------------------------------------


DROP TRIGGER "EMPINST"."T_EMPLOYEE_INSRT"@

DROP TRIGGER "EMPINST"."T_EMPLOYEE_UPDT"@

ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_UID_LOWER DROP EXPRESSION @ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_MAIL_LOWER DROP EXPRESSION @ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_LOGIN_LOWER DROP EXPRESSION @
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_MANAGER_UID_LOWER DROP EXPRESSION @ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_GW_EMAIL_LOWER DROP EXPRESSION @    
COMMIT@

UPDATE EMPINST.EMPLOYEE SET PROF_LAST_UPDATE=CURRENT TIMESTAMP WHERE PROF_LAST_UPDATE IS NULL@
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_LAST_UPDATE SET NOT NULL@

REORG TABLE EMPINST.EMPLOYEE@

UPDATE EMPINST.EMPLOYEE SET PROF_UID_LOWER=LOWER(PROF_UID)@
UPDATE EMPINST.EMPLOYEE SET PROF_MAIL_LOWER=LOWER(PROF_MAIL)@
UPDATE EMPINST.EMPLOYEE SET PROF_LOGIN_LOWER=LOWER(PROF_LOGIN)@
UPDATE EMPINST.EMPLOYEE SET PROF_MANAGER_UID_LOWER=LOWER(PROF_MANAGER_UID)@
UPDATE EMPINST.EMPLOYEE SET PROF_GW_EMAIL_LOWER=LOWER(PROF_GROUPWARE_EMAIL)@

ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_UID_LOWER SET NOT NULL@
ALTER TABLE "EMPINST"."EMPLOYEE" ALTER COLUMN "PROF_DEPARTMENT_NUMBER" SET DATA TYPE VARCHAR (24)@
ALTER TABLE "EMPINST"."EMPLOYEE" ALTER COLUMN "PROF_TIMEZONE" SET DATA TYPE VARCHAR (64)@

ALTER TABLE EMPINST.EMPLOYEE ADD COLUMN PROF_SRC_UID_LOWER VARCHAR(256)@
UPDATE EMPINST.EMPLOYEE SET PROF_SRC_UID_LOWER=LOWER(PROF_SOURCE_UID)@
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_SRC_UID_LOWER SET NOT NULL@

COMMIT@
REORG TABLE EMPINST.EMPLOYEE@


CREATE INDEX "EMPINST"."PROF_DISP_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_KEY" ASC, "PROF_DISPLAY_NAME" ASC, "PROF_SURNAME" ASC, "PROF_GIVEN_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PROF_SNGN_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_KEY" ASC, "PROF_SURNAME" ASC, "PROF_GIVEN_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PROF_GN2_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_GIVEN_NAME" ASC, "PROF_KEY" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."PROF_SN2_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_SURNAME" ASC, "PROF_KEY" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."SRC_UID_LOWER_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_SRC_UID_LOWER" ASC, "PROF_KEY" ASC) ALLOW REVERSE SCANS@

COMMIT@
		

------------------------------------------------
-- DDL Statements for table "EMPINST"."SURNAME"
------------------------------------------------

DROP INDEX EMPINST.SURNAMEX@
DROP INDEX EMPINST.SURNAME_UDX@
DROP INDEX EMPINST.SURNAME_IDX@

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_PK PRIMARY KEY (PROF_KEY, PROF_SURNAME)@

ALTER TABLE EMPINST.SURNAME ADD COLUMN PROF_USRSTATE INTEGER DEFAULT 0 NOT NULL@

CREATE INDEX EMPINST.SURNAME_IDX ON EMPINST.SURNAME (PROF_SURNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC)@
CREATE INDEX EMPINST.SURNAME_IDX2 ON EMPINST.SURNAME (PROF_USRSTATE ASC, PROF_SURNAME ASC, PROF_KEY ASC)@
CREATE INDEX EMPINST.SURNAMEX ON EMPINST.SURNAME (PROF_KEY ASC, PROF_SURNAME ASC, PROF_USRSTATE ASC)@

------------------------------------------------
-- DDL Statements for table "EMPINST"."GIVEN_NAME"
------------------------------------------------

DROP INDEX EMPINST.GIVEN_NAMEX@	
DROP INDEX EMPINST.GIVEN_NAME_UDX@
DROP INDEX EMPINST.GIVEN_NAME_IDX@

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GIVEN_NAME_PK PRIMARY KEY (PROF_KEY, PROF_GIVENNAME)@

ALTER TABLE EMPINST.GIVEN_NAME ADD COLUMN PROF_USRSTATE INTEGER DEFAULT 0 NOT NULL@

CREATE INDEX EMPINST.GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME (PROF_GIVENNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC)@
CREATE INDEX EMPINST.GIVEN_NAME_IDX2 ON EMPINST.GIVEN_NAME (PROF_USRSTATE ASC, PROF_GIVENNAME ASC, PROF_KEY ASC)@
CREATE INDEX EMPINST.GIVEN_NAMEX ON EMPINST.GIVEN_NAME (PROF_KEY ASC, PROF_GIVENNAME ASC, PROF_USRSTATE ASC)@

COMMIT@

------------------------------------------------
-- DDL Statements for table "EMPINST"."EMP_DRAFT"
------------------------------------------------

DROP TRIGGER "EMPINST "."T_EMP_DRAFT_SEQ"@ 
DROP TRIGGER "EMPINST "."T_EMP_INS"@ 
DROP TRIGGER "EMPINST "."T_EMP_DEL"@ 
DROP TRIGGER "EMPINST "."T_EMP_UPD"@
COMMIT@

UPDATE EMPINST.EMP_DRAFT SET PROF_LAST_UPDATE=CURRENT TIMESTAMP WHERE PROF_LAST_UPDATE IS NULL@
ALTER TABLE EMPINST.EMP_DRAFT ALTER COLUMN PROF_LAST_UPDATE SET NOT NULL@

ALTER TABLE "EMPINST"."EMP_DRAFT" ALTER COLUMN "PROF_BUILDING_IDENTIFIER" SET DATA TYPE VARCHAR (64)@
ALTER TABLE "EMPINST"."EMP_DRAFT" ALTER COLUMN "PROF_DEPARTMENT_NUMBER" SET DATA TYPE VARCHAR (24)@
ALTER TABLE "EMPINST"."EMP_DRAFT" ALTER COLUMN "PROF_TIMEZONE" SET DATA TYPE VARCHAR (64)@

DROP INDEX "EMPINST"."ED_PREF_FNX"@
DROP INDEX "EMPINST"."ED_PREF_LNX"@

COMMIT@
REORG TABLE EMPINST.EMP_DRAFT@

CREATE INDEX "EMPINST"."ED_UPDATE_IDX" ON "EMPINST"."EMP_DRAFT" 
		("PROF_LAST_UPDATE" DESC, "PROF_KEY" DESC, "PROF_UPDATE_SEQUENCE" DESC)@

CREATE TRIGGER "EMPINST"."T_EMP_DRAFT_SEQ" NO CASCADE BEFORE INSERT ON "EMPINST"."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATE_SEQUENCE = NEXTVAL FOR "EMPINST"."EMP_DRAFT_SEQ"@

CREATE TRIGGER "EMPINST"."T_EMP_INS" AFTER INSERT ON "EMPINST"."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO "EMPINST"."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST"."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'I', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY )@

CREATE TRIGGER "EMPINST"."T_EMP_DEL" AFTER DELETE ON "EMPINST"."EMP_DRAFT" REFERENCING OLD AS N 
	FOR EACH ROW MODE DB2SQL
		 INSERT INTO "EMPINST"."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST"."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'D', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY )@

CREATE TRIGGER "EMPINST"."T_EMP_UPD" AFTER UPDATE ON "EMPINST"."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO "EMPINST"."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST"."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'U', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY )@
COMMIT@

------------------------------------------------
-- DDL Statements for table EMPINST."PROFILE_EXT_DRAFT
------------------------------------------------

DROP INDEX EMPINST.EXT_DRAFT_PK @

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT EXT_DRAFT_PK PRIMARY KEY (PROF_KEY, PROF_UPDATE_SEQUENCE)@


------------------------------------------------
-- DDL Statements for table EMPINST.PROFILE_EXTENSIONS
------------------------------------------------

DROP INDEX EMPINST.PROFILE_EXTENSIONS_UDX@

ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROFILE_EXT_PK PRIMARY KEY (PROF_KEY, PROF_PROPERTY_ID)@


------------------------------------------------
-- DDL Statements for table "EMPINST"."DEPARTMENT"
------------------------------------------------

ALTER TABLE "EMPINST"."DEPARTMENT" ALTER COLUMN "PROF_DEPARTMENT_CODE" SET DATA TYPE VARCHAR (24)@

COMMIT@
	

------------------------------------------------
-- DDL Statements for view "EMPINST"."PHOTO"
------------------------------------------------

DROP TRIGGER "EMPINST"."T_PHOTO_INSRT"@

DROP TRIGGER "EMPINST"."T_PHOTO_UPDT"@

------------------------------------------------
-- DDL Statements for table "EMPINST"."PRONUNCIATION"
------------------------------------------------

DROP TRIGGER "EMPINST"."T_PRONOUNCE_INSRT"@

DROP TRIGGER "EMPINST"."T_PRONOUNCE_UPDT"@

ALTER TABLE "EMPINST"."PRONUNCIATION" ADD COLUMN "PROF_FILE_TYPE" VARCHAR (50) NOT NULL DEFAULT 'audio/wav'@


------------------------------------------------
-- DDL Statements for table "EMPINST"."PROF_CONNECTIONS"
------------------------------------------------
DROP INDEX "EMPINST"."CONN_INDEX1"@
DROP INDEX "EMPINST"."CONN_INDEX2"@
DROP INDEX "EMPINST"."CONN_TARGET_IDX"@

-- Main index to select a users connections for showing friends in UI
CREATE INDEX EMPINST.CONN_INDEX1 ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_LASTMOD DESC, PROF_TARGET_KEY ASC) ALLOW REVERSE SCANS@

-- Friends in common; get list of connection keys
-- 'isConnection' query
CREATE INDEX EMPINST.CONN_INDEX2 ON EMPINST.PROF_CONNECTIONS 
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_TARGET_KEY ASC, PROF_LASTMOD ASC) ALLOW REVERSE SCANS@

-- Reverse index for deletes
CREATE INDEX EMPINST.CONN_REV_IDX ON EMPINST.PROF_CONNECTIONS 
	(PROF_TARGET_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_SOURCE_KEY ASC, PROF_LASTMOD ASC) ALLOW REVERSE SCANS@

COMMIT@
	

------------------------------------------------
-- DDL Statements for table "EMPINST"."EVENTLOG"
------------------------------------------------

CREATE INDEX "EMPINST"."EVLOG_AUDIT_IDX" ON EMPINST.EVENTLOG (ISSYSEVENT ASC, EVENT_KEY ASC) ALLOW REVERSE SCANS@


------------------------------------------------
-- DDL Statements for table "EMPINST"."USER_PLATFORM_EVENTS"
------------------------------------------------

CREATE TABLE "EMPINST"."USER_PLATFORM_EVENTS"  (
	"EVENT_KEY" BIGINT NOT NULL, 
	"EVENT_TYPE" VARCHAR(36) NOT NULL,
	"PAYLOAD" CLOB(100K) LOGGED COMPACT,
	"CREATED" TIMESTAMP NOT NULL,
	CONSTRAINT "PLATFORM_EVENTS_PK" PRIMARY KEY ("EVENT_KEY") 
) IN USERSPACE4K INDEX IN USERSPACE4K@

	
CREATE SEQUENCE "EMPINST"."USER_PLATFORM_EVENT_INDEX_SEQ"
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	NOCYCLE
	CACHE 20@

-------------------------------------------------------------------
-- START ADDING SCHEDULER TABLES
-------------------------------------------------------------------

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TASK" (
	TASKID BIGINT NOT NULL,
	VERSION VARCHAR(5) NOT NULL,
	ROW_VERSION INTEGER NOT NULL,
	TASKTYPE INTEGER NOT NULL,
	TASKSUSPENDED SMALLINT NOT NULL,
	CANCELLED SMALLINT NOT NULL,
	NEXTFIRETIME BIGINT NOT NULL,
	STARTBYINTERVAL VARCHAR(254),
	STARTBYTIME BIGINT,
	VALIDFROMTIME BIGINT,
	VALIDTOTIME BIGINT,
	REPEATINTERVAL VARCHAR(254),
	MAXREPEATS INTEGER NOT NULL,
	REPEATSLEFT INTEGER NOT NULL,
	TASKINFO BLOB(102400) LOGGED NOT COMPACT,
	NAME VARCHAR(254) NOT NULL,
	AUTOPURGE INTEGER NOT NULL,
	FAILUREACTION INTEGER,
	MAXATTEMPTS INTEGER,
	QOS INTEGER,
	PARTITIONID INTEGER,
	OWNERTOKEN VARCHAR(200) NOT NULL,
	CREATETIME BIGINT NOT NULL
) 
IN USERSPACE4K INDEX IN USERSPACE4K@

ALTER TABLE "EMPINST".PROFILES_SCHEDULER_TASK 
	ADD PRIMARY KEY (TASKID)@

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX1 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" (TASKID, OWNERTOKEN)@

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX2 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" (NEXTFIRETIME ASC, REPEATSLEFT, PARTITIONID) CLUSTER@

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TREG" (
	REGKEY VARCHAR(254) NOT NULL,
	REGVALUE VARCHAR(254) 
) 
IN USERSPACE4K INDEX IN USERSPACE4K@

ALTER TABLE "EMPINST".PROFILES_SCHEDULER_TREG 
	ADD PRIMARY KEY (REGKEY)@

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMGR" (
	LEASENAME VARCHAR(254) NOT NULL,
	LEASEOWNER VARCHAR(254) NOT NULL,
	LEASE_EXPIRE_TIME  BIGINT,
	DISABLED VARCHAR(5)
)
IN USERSPACE4K INDEX IN USERSPACE4K@

ALTER TABLE "EMPINST"."PROFILES_SCHEDULER_LMGR"
	ADD PRIMARY KEY (LEASENAME)@

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMPR" (
	LEASENAME VARCHAR(254) NOT NULL,
	NAME VARCHAR(254) NOT NULL,
	VALUE VARCHAR(254) NOT NULL
)
IN USERSPACE4K INDEX IN USERSPACE4K@

CREATE INDEX "EMPINST"."PROFILES_SCHEDULER_LMPR_IDX1 "
	ON "EMPINST"."PROFILES_SCHEDULER_LMPR" (LEASENAME, NAME)@
	
-------------------------------------------------------------------
-- END ADDING SCHEDULER TABLES
-------------------------------------------------------------------

------------------------------------------------
-- Stuff to create external index dynattr
------------------------------------------------

{include.createDynaDefs.sql}

--
-- User state look aside index table
--
CREATE TABLE EMPINST.USER_STATE_LAIDX (
	IDXID    CHAR(16) FOR BIT DATA NOT NULL,
	DEFID    CHAR(16) FOR BIT DATA NOT NULL,
	ATTRID	 CHAR(16) FOR BIT DATA NOT NULL,
	USRSTATE INTEGER NOT NULL,
	USRSTATE_UPDATED TIMESTAMP NOT NULL,
	OBJID    CHAR(16) FOR BIT DATA NOT NULL,
	OBJIDSTR   CHAR(36) NOT NULL,
	CONSTRAINT USRSTATE_PK PRIMARY KEY (IDXID)
) IN USERSPACE4K INDEX IN USERSPACE4K@

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_DEF_FK FOREIGN KEY (DEFID) 
	REFERENCES EMPINST.DYNA_DEFS(DEFID)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

--
-- Foriegn key constraint to reference field which contains value
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_ATTR_FK FOREIGN KEY (ATTRID) 
	REFERENCES EMPINST.DYNA_ATTRS(ATTRID)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

--
-- Enforce single attr/idx-val
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTE_ATTR_UK UNIQUE (ATTRID)@

--
-- Constrain to one value per user
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT OBJID_UNIQUE UNIQUE (OBJID)@
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT OBJIDSTR_UNIQUE UNIQUE (OBJIDSTR)@

CREATE INDEX EMPINST.USRSTATE_CONS_VALB 
	ON EMPINST.USER_STATE_LAIDX (OBJID ASC, OBJIDSTR ASC, USRSTATE ASC, USRSTATE_UPDATED ASC)
	ALLOW REVERSE SCANS@
	
CREATE INDEX EMPINST.USRSTATE_CONS_VALS 
	ON EMPINST.USER_STATE_LAIDX (OBJIDSTR ASC, OBJID ASC, USRSTATE ASC, USRSTATE_UPDATED ASC)
	ALLOW REVERSE SCANS@
	
--
-- Main index for scanning
--
CREATE INDEX USRSTATE_IDX
	ON EMPINST.USER_STATE_LAIDX (USRSTATE ASC, USRSTATE_UPDATED ASC, OBJID ASC, OBJIDSTR ASC)
	ALLOW REVERSE SCANS@

--
-- User state look aside index table
--
CREATE TABLE EMPINST.USER_ORGS_LAIDX (
	IDXID    CHAR(16) FOR BIT DATA NOT NULL,
	DEFID    CHAR(16) FOR BIT DATA NOT NULL,
	ATTRID	  CHAR(16) FOR BIT DATA NOT NULL,
	ORGID	  VARCHAR(128) NOT NULL,
	OBJID    CHAR(16) FOR BIT DATA NOT NULL,
	OBJIDSTR CHAR(36) NOT NULL,
	CONSTRAINT USRORGS_PK PRIMARY KEY (IDXID)
) IN USERSPACE4K INDEX IN USERSPACE4K@

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_DEF_FK FOREIGN KEY (DEFID) 
	REFERENCES EMPINST.DYNA_DEFS(DEFID)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

--
-- Foriegn key constraint to reference field which contains value
--
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_ATTR_FK FOREIGN KEY (ATTRID) 
	REFERENCES EMPINST.DYNA_ATTRS(ATTRID)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

--
-- Enforce single attr/idx-val
--
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_ATTR_UK UNIQUE (ATTRID)@

--
-- Main index for scanning
--
CREATE INDEX EMPINST.USRORGS_IDX
	ON EMPINST.USER_ORGS_LAIDX (DEFID ASC, ORGID ASC, OBJIDSTR ASC, OBJID ASC)
	ALLOW REVERSE SCANS@

ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_C_OBJID UNIQUE (DEFID, OBJID, ORGID)@
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_C_OBJIDS UNIQUE (DEFID, OBJIDSTR, ORGID)@

CREATE INDEX EMPINST.USRORGS_MEM_BIDX
	ON EMPINST.USER_ORGS_LAIDX (OBJID ASC, DEFID ASC, ORGID ASC, OBJIDSTR ASC)
	ALLOW REVERSE SCANS@

CREATE INDEX EMPINST.USRORGS_MEM_SIDX
	ON EMPINST.USER_ORGS_LAIDX (OBJIDSTR ASC, DEFID ASC, ORGID ASC, OBJID ASC)
	ALLOW REVERSE SCANS@

--
-- Board schema updates
--
{include.msgVector-fixup5.sql}

--
-- Add state field for lookaside index tables
--
INSERT INTO EMPINST.PROF_CONSTANTS VALUES ('LA_IDX_STATE', 'inconsistent')@

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 29, RELEASEVER='3.0.0.0' WHERE COMPKEY='Profiles'@

COMMIT@
CONNECT RESET@
