-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

------------------------------------------------
-- DDL Statements for table "EMPINST"."EMPLOYEE"
------------------------------------------------

DROP TRIGGER "EMPINST"."T_EMPLOYEE_INSRT"@

DROP TRIGGER "EMPINST"."T_EMPLOYEE_UPDT"@

ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_UID_LOWER DROP EXPRESSION @ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_MAIL_LOWER DROP EXPRESSION @ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_LOGIN_LOWER DROP EXPRESSION @
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_MANAGER_UID_LOWER DROP EXPRESSION @ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_GW_EMAIL_LOWER DROP EXPRESSION @    
COMMIT@

UPDATE EMPINST.EMPLOYEE SET PROF_LAST_UPDATE=CURRENT TIMESTAMP WHERE PROF_LAST_UPDATE IS NULL@
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_LAST_UPDATE SET NOT NULL@

REORG TABLE EMPINST.EMPLOYEE@

UPDATE EMPINST.EMPLOYEE SET PROF_UID_LOWER=LOWER(PROF_UID)@
UPDATE EMPINST.EMPLOYEE SET PROF_MAIL_LOWER=LOWER(PROF_MAIL)@
UPDATE EMPINST.EMPLOYEE SET PROF_LOGIN_LOWER=LOWER(PROF_LOGIN)@
UPDATE EMPINST.EMPLOYEE SET PROF_MANAGER_UID_LOWER=LOWER(PROF_MANAGER_UID)@
UPDATE EMPINST.EMPLOYEE SET PROF_GW_EMAIL_LOWER=LOWER(PROF_GROUPWARE_EMAIL)@

ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_UID_LOWER SET NOT NULL@

DROP INDEX "EMPINST"."PROF_DISP_IDX"@

ALTER TABLE EMPINST.EMPLOYEE ADD COLUMN PROF_SRC_UID_LOWER VARCHAR(256)@
UPDATE EMPINST.EMPLOYEE SET PROF_SRC_UID_LOWER=LOWER(PROF_SOURCE_UID)@
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_SRC_UID_LOWER SET NOT NULL@

COMMIT@
REORG TABLE EMPINST.EMPLOYEE@

CREATE INDEX "EMPINST"."PROF_DISP_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_KEY" ASC, "PROF_DISPLAY_NAME" ASC, "PROF_SURNAME" ASC, "PROF_GIVEN_NAME" ASC) ALLOW REVERSE SCANS@

CREATE INDEX "EMPINST"."SRC_UID_LOWER_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_SRC_UID_LOWER" ASC, "PROF_KEY" ASC) ALLOW REVERSE SCANS@

------------------------------------------------
-- DDL Statements for table "EMPINST"."EMP_DRAFT"
------------------------------------------------

DROP TRIGGER "EMPINST "."T_EMP_DRAFT_SEQ"@ 
DROP TRIGGER "EMPINST "."T_EMP_INS"@ 
DROP TRIGGER "EMPINST "."T_EMP_DEL"@ 
DROP TRIGGER "EMPINST "."T_EMP_UPD"@
COMMIT@

UPDATE EMPINST.EMP_DRAFT SET PROF_LAST_UPDATE=CURRENT TIMESTAMP WHERE PROF_LAST_UPDATE IS NULL@
ALTER TABLE EMPINST.EMP_DRAFT ALTER COLUMN PROF_LAST_UPDATE SET NOT NULL@

ALTER TABLE "EMPINST"."EMP_DRAFT" ALTER COLUMN "PROF_BUILDING_IDENTIFIER" SET DATA TYPE VARCHAR (64)@
ALTER TABLE "EMPINST"."EMP_DRAFT" ALTER COLUMN "PROF_DEPARTMENT_NUMBER" SET DATA TYPE VARCHAR (24)@
ALTER TABLE "EMPINST"."EMP_DRAFT" ALTER COLUMN "PROF_TIMEZONE" SET DATA TYPE VARCHAR (64)@

DROP INDEX "EMPINST"."ED_PREF_FNX"@
DROP INDEX "EMPINST"."ED_PREF_LNX"@

COMMIT@
REORG TABLE EMPINST.EMP_DRAFT@

CREATE INDEX "EMPINST"."ED_UPDATE_IDX" ON "EMPINST"."EMP_DRAFT" 
		("PROF_LAST_UPDATE" DESC, "PROF_KEY" DESC, "PROF_UPDATE_SEQUENCE" DESC)@

CREATE TRIGGER "EMPINST"."T_EMP_DRAFT_SEQ" NO CASCADE BEFORE INSERT ON "EMPINST"."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATE_SEQUENCE = NEXTVAL FOR "EMPINST"."EMP_DRAFT_SEQ"@

CREATE TRIGGER "EMPINST"."T_EMP_INS" AFTER INSERT ON "EMPINST"."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO "EMPINST"."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST"."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'I', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY )@

CREATE TRIGGER "EMPINST"."T_EMP_DEL" AFTER DELETE ON "EMPINST"."EMP_DRAFT" REFERENCING OLD AS N 
	FOR EACH ROW MODE DB2SQL
		 INSERT INTO "EMPINST"."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST"."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'D', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY )@

CREATE TRIGGER "EMPINST"."T_EMP_UPD" AFTER UPDATE ON "EMPINST"."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO "EMPINST"."CHG_EMP_DRAFT" VALUES (NEXTVAL FOR "EMPINST"."CHG_EMP_DRAFT_SEQ", 0, 
			CURRENT_DATE, 'U', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY )@
COMMIT@

------------------------------------------------
-- DDL Statements for view "EMPINST"."PHOTO"
------------------------------------------------

DROP TRIGGER "EMPINST"."T_PHOTO_INSRT"@

DROP TRIGGER "EMPINST"."T_PHOTO_UPDT"@

------------------------------------------------
-- DDL Statements for table "EMPINST"."PRONUNCIATION"
------------------------------------------------

DROP TRIGGER "EMPINST"."T_PRONOUNCE_INSRT"@

DROP TRIGGER "EMPINST"."T_PRONOUNCE_UPDT"@

------------------------------------------------
-- DDL Statements for table "EMPINST"."EVENTLOG"
------------------------------------------------

CREATE INDEX "EMPINST"."EVLOG_AUDIT_IDX" ON EMPINST.EVENTLOG (ISSYSEVENT ASC, EVENT_KEY ASC) ALLOW REVERSE SCANS@


-- Update schema versions
UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 29 WHERE COMPKEY='Profiles'@


COMMIT@
CONNECT RESET@
