-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2012, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

------
-- EMPLOYEE
------

CREATE INDEX EMPINST.PROF_SRC_UID_IDX ON EMPINST.EMPLOYEE (PROF_SOURCE_UID ASC) ALLOW REVERSE SCANS@
COMMIT@

------
-- PROFILE_EXTENSIONS: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_EXTENSIONS
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROFEXT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- PROFILE_EXT_DRAFT: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT PREXTDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- PEOPLE_TAG: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PEOPLE_TAG
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PEOPLE_TAG ADD CONSTRAINT PPLTAG_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- PHOTO: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PHOTO
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_TENT_UK  UNIQUE (PROF_KEY, TENANT_KEY)@

ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- PRONUNCIATION: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PRONUNCIATION
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNC_TENT_UK  UNIQUE (PROF_KEY, TENANT_KEY)@

ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNC_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- EMP_DRAFT: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EMP_DRAFT
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMPDRAFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- CHG_EMP_DRAFT: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.CHG_EMP_DRAFT
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.CHG_EMP_DRAFT ADD CONSTRAINT CHEMPDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

DROP TRIGGER EMPINST.T_EMP_INS@
DROP TRIGGER EMPINST.T_EMP_DEL@
DROP TRIGGER EMPINST.T_EMP_UPD@

CREATE TRIGGER EMPINST.T_EMP_INS AFTER INSERT ON EMPINST.EMP_DRAFT REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO EMPINST.CHG_EMP_DRAFT VALUES (NEXTVAL FOR EMPINST.CHG_EMP_DRAFT_SEQ, 0, 
			CURRENT_DATE, 'I', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY, N.TENANT_KEY )@

CREATE TRIGGER EMPINST.T_EMP_DEL AFTER DELETE ON EMPINST.EMP_DRAFT REFERENCING OLD AS N 
	FOR EACH ROW MODE DB2SQL
		 INSERT INTO EMPINST.CHG_EMP_DRAFT VALUES (NEXTVAL FOR EMPINST.CHG_EMP_DRAFT_SEQ, 0, 
			CURRENT_DATE, 'D', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY, N.TENANT_KEY )@

CREATE TRIGGER EMPINST.T_EMP_UPD AFTER UPDATE ON EMPINST.EMP_DRAFT REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 INSERT INTO EMPINST.CHG_EMP_DRAFT VALUES (NEXTVAL FOR EMPINST.CHG_EMP_DRAFT_SEQ, 0, 
			CURRENT_DATE, 'U', N.PROF_UPDATE_SEQUENCE, N.PROF_KEY, N.TENANT_KEY)@
------
-- PROF_CONNECTIONS: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROF_CONNECTIONS
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- PROFILE_PREFS: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_PREFS
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFPREF_TENT_UK  UNIQUE (PROF_KEY, TENANT_KEY)@

ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFPREF_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- PROFILE_LAST_LOGIN: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN
	ADD COLUMN TENANT_KEY VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'@

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_TENT_UK  UNIQUE (PROF_KEY, TENANT_KEY)@

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

------
-- Update schema version
------

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 36, RELEASEVER='4.5.0.0' WHERE COMPKEY='Profiles'@
COMMIT@

CONNECT RESET@