-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CONNECT TO PEOPLEDB@

ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN PROF_LOGIN_LOWER DROP EXPRESSION @
COMMIT@
ALTER TABLE "EMPINST"."EMPLOYEE" ALTER COLUMN "PROF_LOGIN_LOWER" SET DATA TYPE VARCHAR (256)@
COMMIT@
SET INTEGRITY FOR EMPINST.EMPLOYEE OFF@ 
ALTER TABLE EMPINST.EMPLOYEE ALTER COLUMN  PROF_LOGIN_LOWER SET GENERATED ALWAYS AS (LOWER(PROF_LOGIN))@
SET INTEGRITY FOR EMPINST.EMPLOYEE IMMEDIATE CHECKED FORCE GENERATED@ 
COMMIT@

ALTER TABLE "EMPINST"."EMPLOYEE" ADD COLUMN "TEMP_DESC" VARCHAR(4000)@
UPDATE "EMPINST"."EMPLOYEE" SET "TEMP_DESC"="PROF_DESCRIPTION"@

ALTER TABLE "EMPINST"."EMPLOYEE" ADD COLUMN "TEMP_EXP" VARCHAR(4000)@
UPDATE "EMPINST"."EMPLOYEE" SET "TEMP_EXP"="PROF_EXPERIENCE"@

ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "PROF_DESCRIPTION"@
ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "PROF_EXPERIENCE"@

REORG TABLE "EMPINST"."EMPLOYEE"@

ALTER TABLE "EMPINST"."EMPLOYEE" ADD COLUMN "PROF_DESCRIPTION" CLOB(1 M) NOT COMPACT@
UPDATE "EMPINST"."EMPLOYEE" SET "PROF_DESCRIPTION"="TEMP_DESC"@

ALTER TABLE "EMPINST"."EMPLOYEE" ADD COLUMN "PROF_EXPERIENCE" CLOB(1 M) NOT COMPACT@
UPDATE "EMPINST"."EMPLOYEE" SET "PROF_EXPERIENCE"="TEMP_EXP"@

ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "TEMP_DESC"@
ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "TEMP_EXP"@

REORG TABLE "EMPINST"."EMPLOYEE"@

CREATE INDEX "EMPINST"."SRC_UID_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_SOURCE_UID" ASC) ALLOW REVERSE SCANS@

		
-- DDL Statements for triggers on Table "EMPINST"."EMPLOYEE"

CREATE TRIGGER "EMPINST"."T_EMPLOYEE_INSRT" NO CASCADE BEFORE INSERT ON "EMPINST"."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

CREATE TRIGGER "EMPINST"."T_EMPLOYEE_UPDT" NO CASCADE BEFORE UPDATE ON "EMPINST"."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_LAST_UPDATE = CURRENT TIMESTAMP@

ALTER TABLE "EMPINST"."EMP_DRAFT" ALTER COLUMN "PROF_LOGIN" SET DATA TYPE VARCHAR (256)@
   
ALTER TABLE "EMPINST"."EMP_DRAFT" ADD COLUMN "TEMP_DESC" VARCHAR(4000)@
UPDATE "EMPINST"."EMP_DRAFT" SET "TEMP_DESC"="PROF_DESCRIPTION"@

ALTER TABLE "EMPINST"."EMP_DRAFT" ADD COLUMN "TEMP_EXP" VARCHAR(4000)@
UPDATE "EMPINST"."EMP_DRAFT" SET "TEMP_EXP"="PROF_EXPERIENCE"@

ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "PROF_DESCRIPTION"@
ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "PROF_EXPERIENCE"@

REORG TABLE "EMPINST"."EMP_DRAFT"@

ALTER TABLE "EMPINST"."EMP_DRAFT" ADD COLUMN "PROF_DESCRIPTION" CLOB(1 M) NOT COMPACT@
UPDATE "EMPINST"."EMP_DRAFT" SET "PROF_DESCRIPTION"="TEMP_DESC"@

ALTER TABLE "EMPINST"."EMP_DRAFT" ADD COLUMN "PROF_EXPERIENCE" CLOB(1 M) NOT COMPACT@
UPDATE "EMPINST"."EMP_DRAFT" SET "PROF_EXPERIENCE"="TEMP_EXP"@

ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "TEMP_DESC"@
ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "TEMP_EXP"@

REORG TABLE "EMPINST"."EMP_DRAFT"@
                      
-- DDL Statements for triggers on Table "EMPINST"."EMP_DRAFT"
CREATE TRIGGER "EMPINST"."T_EMP_DRAFT_SEQ" NO CASCADE BEFORE INSERT ON "EMPINST"."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL 
		 SET N.PROF_UPDATE_SEQUENCE = NEXTVAL FOR "EMPINST"."EMP_DRAFT_SEQ"@
                 
                    
DROP INDEX "EMPINST"."CONN_UDX" @
DROP INDEX "EMPINST"."CONN_INDEX1"@
DROP INDEX "EMPINST"."CONN_INDEX2"@ 

ALTER TABLE "EMPINST"."PROF_CONNECTIONS" DROP COLUMN "PROF_VISIBILITY"@
ALTER TABLE "EMPINST"."PROF_CONNECTIONS" DROP COLUMN "PROF_TYPE"@

ALTER TABLE "EMPINST"."PROF_CONNECTIONS" ADD COLUMN "PROF_TYPE" VARCHAR(36)@

REORG TABLE "EMPINST"."PROF_CONNECTIONS"@

UPDATE "EMPINST"."PROF_CONNECTIONS" SET "PROF_TYPE"="PROF_VALUE"@

ALTER TABLE "EMPINST"."PROF_CONNECTIONS" DROP COLUMN "PROF_VALUE"@

REORG TABLE "EMPINST"."PROF_CONNECTIONS"@

CREATE UNIQUE INDEX "EMPINST"."CONN_UDX" ON EMPINST.PROF_CONNECTIONS
		(PROF_SOURCE_KEY ASC, PROF_TARGET_KEY ASC, PROF_TYPE ASC)@

-- Main index to select a users connections
CREATE INDEX "EMPINST"."CONN_INDEX1" ON EMPINST.PROF_CONNECTIONS
	(PROF_STATUS ASC, PROF_TYPE ASC,  PROF_SOURCE_KEY ASC) CLUSTER ALLOW REVERSE SCANS@

-- Secondary index for walking; used for recnt connections
CREATE INDEX "EMPINST"."CONN_INDEX2" ON EMPINST.PROF_CONNECTIONS
	(PROF_STATUS ASC, PROF_TYPE ASC,  PROF_SOURCE_KEY ASC, PROF_LASTMOD DESC) ALLOW REVERSE SCANS@


------------------------------------------------
-- update schema to current version
------------------------------------------------

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 5 WHERE COMPKEY='Profiles'@

BIND @db2cli.lst ACTION REPLACE REOPT NONE COLLECTION EMPINST@

COMMIT@
CONNECT RESET@

