<%-- Copyright IBM Corp. 2011, 2013  All Rights Reserved. --%><%--
                   

   The Connections business card is generated by this JSP.
                   
=== DO NOT CHANGE ===
--%><%@ page contentType="text/html;charset=UTF-8" %><%--
--%><%@ taglib prefix="c"        uri="http://java.sun.com/jsp/jstl/core" %><%--
--%><%@ taglib prefix="fmt"      uri="http://java.sun.com/jsp/jstl/fmt" %><%--
--%><%@ taglib prefix="lc-cache" uri="http://www.ibm.com/connections/core/cache" %><%--
--%><%@ taglib prefix="lc-ui"    uri="http://www.ibm.com/lconn/tags/coreuiutil" %><%--
--%><%@ taglib prefix="fn" 			uri="http://java.sun.com/jsp/jstl/functions" %><%--
--%><%@ taglib prefix="html" 		uri="http://jakarta.apache.org/struts/tags-html" %><%--
--%><%@ taglib prefix="tiles" 		uri="http://jakarta.apache.org/struts/tags-tiles" %><%--
--%><%@ taglib prefix="profiles"	uri="/WEB-INF/tlds/profiles.tld" %><%--
--%><%@ taglib prefix="tags"		uri="/WEB-INF/tags" %><%--
--%><%@page import="java.util.List,
		com.ibm.peoplepages.data.Employee,
		org.apache.commons.lang.StringEscapeUtils,
		com.ibm.lconn.profiles.config.ui.UIBusinessCardActionConfig,
		com.ibm.peoplepages.json.actions.BusinessCardHelper,
		com.ibm.lconn.profiles.config.ui.UIBusinessCardConfig,
		com.ibm.lconn.profiles.web.ui.actions.person.forms.PersonCard,
		com.ibm.lconn.profiles.config.ui.UIAttributeConfig,
		com.ibm.lconn.profiles.web.util.UIAttributeWriterConfig,
		com.ibm.lconn.profiles.web.util.UIAttributeWriterHelper" %><%--

--%><c:set var="showName" value="${param.showName}" /><%--

--%><lc-ui:bundle basename="com.ibm.lconn.profiles.strings.ui"><% 

	boolean isCacheable = false;

	boolean showName = Boolean.parseBoolean(request.getParameter("showName"));
	PersonCard actionBean = (PersonCard)request.getAttribute("actionBean");
	Employee profile = actionBean.getEmployee();
	String profileType = profile.getProfileType();
	UIBusinessCardConfig cardConfig = UIBusinessCardConfig.instance(profileType);
	pageContext.setAttribute("cardConfig", cardConfig);
	UIAttributeWriterConfig writerConfig = new UIAttributeWriterConfig();
	UIAttributeWriterHelper writer = new UIAttributeWriterHelper(writerConfig, getServletContext(), request, out);
	writer.setProfile(profile);

%><%--

--%><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html <lc-ui:htmlLanguage />>
<head>
   <title><c:out value="${actionBean.employee.displayName}" /></title>

   <lc-ui:stylesheets />
   <lc-cache:stylesheet template="{webResourcesRoot}/web/com.ibm.social.personcard/test/card/card.css" />
</head>

<body class="lotusui">
	<div id="content" class="card-content">
		<div class="person-content">
			<c:if test="${cardConfig.showProfilePhoto}"><div class="person-image-border"><img class="person-image" style="width:100px; height:100px;" src="${pageContext.request.contextPath}/photo.do?key=${actionBean.employee.key}"></div></c:if><%
					
			for (UIAttributeConfig attr : cardConfig.getAttributes())
				if ("status".equals(attr.getAttributeId()))
				{
%>
					<div class="person-status">Ready for another busy day at Renovations.</div>
					<div class="person-status-lastupdated lotusTiny">3 hours ago</div>
<%
				}
				else if (!"displayName".equals(attr.getAttributeId()) || showName)
					writer.writeAttr(attr);
%>
			<div class="lotusClear"><!-- IE --></div>
		</div>
		<div class="person-actions">
			<a class="action-right action-text lotusTiny" onclick="showTab(this,event); return false;" href="javascript:;" id="actions" title="<fmt:message key="personCardMoreActionsAltText" />" dojoType="com.ibm.social.personcard.tab.MoreActions"><fmt:message key="personCardMoreActions" /></a>
			<a href="mailto:<c:out value="${email}" />" target="_top" title="Send Email"><img alt="Email" class="cardImage" src='<lc-ui:blankGif />'></a>
			<a onclick="showTab(this,event); return false;" href="javascript:;" id="invite" dojoType="com.ibm.social.personcard.tab.Network" title="<fmt:message key="personCardAddAsColleagues" />"><img alt="<fmt:message key="label.header.mynetwork" />" class="cardImage" src="<lc-ui:blankGif />"></a>
		</div>
		<div id="more-actions" style="display: none;">
			Add actions here
		</div>
	</div>
	<div class="extra-info" id="extra-info"></div>
	<script>
		/* The Javascript modules that must be loaded whenever tabs are activated */
		var modules = ["com.ibm.social.personcard.tabs","com.ibm.social.personcard.tab.MoreActions","com.ibm.social.personcard.tab.Network"];
		/* Info about the current person shown in the card */
		var userInfo = {name: '<c:out value="${actionBean.employee.displayName}" />', key: '<c:out value="${actionBean.employee.key}" />'};
	</script>
	<lc-ui:dojo include="com.ibm.social.personcard.card" />
	<script>contentChanged();</script>
</body>
</html><%--

--%></lc-ui:bundle>