<%-- Copyright IBM Corp. 2011, 2013  All Rights Reserved. --%><%--
                   

   The Connections business card is generated by this JSP.
                   
=== DO NOT CHANGE ===
--%><%@ page contentType="text/html;charset=UTF-8" %><%--
--%><%@ taglib prefix="c"        uri="http://java.sun.com/jsp/jstl/core" %><%--
--%><%@ taglib prefix="fmt"      uri="http://java.sun.com/jsp/jstl/fmt" %><%--
--%><%@ taglib prefix="lc-cache" uri="http://www.ibm.com/connections/core/cache" %><%--
--%><%@ taglib prefix="lc-ui"    uri="http://www.ibm.com/lconn/tags/coreuiutil" %><%--
--%><%@ taglib prefix="fn" 			uri="http://java.sun.com/jsp/jstl/functions" %><%--
--%><%@ taglib prefix="html" 		uri="http://jakarta.apache.org/struts/tags-html" %><%--
--%><%@ taglib prefix="tiles" 		uri="http://jakarta.apache.org/struts/tags-tiles" %><%--
--%><%@ taglib prefix="profiles"	uri="/WEB-INF/tlds/profiles.tld" %><%--
--%><%@ taglib prefix="tags"		uri="/WEB-INF/tags" %><%--

--%><lc-ui:bundle basename="com.ibm.lconn.profiles.strings.ui" ><%--

--%><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html <lc-ui:htmlLanguage />>
<head>
   <title><fmt:message key="label.personcard.noprofilemsg" /></title>

   <lc-ui:stylesheets />
   <lc-cache:stylesheet template="{webResourcesRoot}/web/com.ibm.social.personcard/test/card/card.css" />
</head>

<body class="lotusui">
	<div id="content" class="card-content">
		<div class="person-content">
			<div class="person-missing">
			<fmt:message key="label.personcard.noprofilemsg" />
			</div>
		</div>
	</div>
</body>
</html><%--

--%></lc-ui:bundle>