-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68

--
-- Fix constraints & relations
--

-- Drop Constraint
ALTER TABLE {SUBST_SCHEMA}.SNMSGV_ENTRY DROP CONSTRAINT SNMSGV_ENTRY_FK@

-- Change vector ID to be assoc id
UPDATE {SUBST_SCHEMA}.SNMSGV_ENT_PTR
SET EP_VECTOR_ID = (select VECTOR_RES_ASSOC_ID from {SUBST_SCHEMA}.SNMSGV_VECTOR where VECTOR_ID = EP_VECTOR_ID)
WHERE EXISTS (select VECTOR_RES_ASSOC_ID from {SUBST_SCHEMA}.SNMSGV_VECTOR where VECTOR_ID = EP_VECTOR_ID)@

COMMIT@

UPDATE {SUBST_SCHEMA}.SNMSGV_ENTRY
SET VECTOR_ID = (select VECTOR_RES_ASSOC_ID from {SUBST_SCHEMA}.SNMSGV_VECTOR where {SUBST_SCHEMA}.SNMSGV_VECTOR.VECTOR_ID = {SUBST_SCHEMA}.SNMSGV_ENTRY.VECTOR_ID)
WHERE EXISTS (select VECTOR_RES_ASSOC_ID from {SUBST_SCHEMA}.SNMSGV_VECTOR where {SUBST_SCHEMA}.SNMSGV_VECTOR.VECTOR_ID = {SUBST_SCHEMA}.SNMSGV_ENTRY.VECTOR_ID)@

COMMIT@

UPDATE {SUBST_SCHEMA}.SNMSGV_VECTOR 
set VECTOR_ID = VECTOR_RES_ASSOC_ID@

COMMIT@

-- Re-add Constraint
ALTER TABLE {SUBST_SCHEMA}.SNMSGV_ENTRY ADD CONSTRAINT SNMSGV_ENTRY_FK FOREIGN KEY (VECTOR_ID) 
	REFERENCES {SUBST_SCHEMA}.SNMSGV_VECTOR (VECTOR_ID) 
	ON DELETE CASCADE ON UPDATE NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION@

--
-- Fix indexexs
--

-- drop old indexes
DROP INDEX {SUBST_SCHEMA}.SNMSGV_ENTRY_ORDER_IDX@
DROP INDEX {SUBST_SCHEMA}.SNMSGV_ENTRY_LASTUPDATE_IDX@
DROP INDEX {SUBST_SCHEMA}.SNMSGV_ENT_WALKER_IDX@


-- create corrected
CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENTRY_ORDER_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (VECTOR_ID ASC, ENTRY_TYPE ASC, PUBLISHED ASC, ENTRY_ID ASC)
	CLUSTER ALLOW REVERSE SCANS@

CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENTRY_LASTUPDATE_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (VECTOR_ID ASC, ENTRY_TYPE ASC, LASTUPDATE ASC, ENTRY_ID ASC)
	ALLOW REVERSE SCANS@
	
CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENT_WALKER_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (ENTRY_TYPE ASC, PUBLISHED ASC, ENTRY_ID ASC)
	ALLOW REVERSE SCANS@
	
CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENT_WALKER_LU_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (ENTRY_TYPE ASC, LASTUPDATE ASC, ENTRY_ID ASC)
	ALLOW REVERSE SCANS@

-- with entry type at end@ needed for some queries
CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENTRY_ORDR2_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (VECTOR_ID ASC, PUBLISHED ASC, ENTRY_ID ASC, ENTRY_TYPE ASC)
	ALLOW REVERSE SCANS@

CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENTRY_LASTUPDT2_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (VECTOR_ID ASC, LASTUPDATE ASC, ENTRY_ID ASC, ENTRY_TYPE ASC)
	ALLOW REVERSE SCANS@

CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENT_WLKR2_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (PUBLISHED ASC, ENTRY_ID ASC, ENTRY_TYPE ASC)
	ALLOW REVERSE SCANS@
	
CREATE INDEX {SUBST_SCHEMA}.SNMSGV_ENT_WLKR2_LU_IDX ON {SUBST_SCHEMA}.SNMSGV_ENTRY (LASTUPDATE ASC, ENTRY_ID ASC, ENTRY_TYPE ASC)
	ALLOW REVERSE SCANS@


-- org utilize cluster
reorg table {SUBST_SCHEMA}.SNMSGV_ENTRY index {SUBST_SCHEMA}.SNMSGV_ENTRY_ORDER_IDX use {SUBST_TEMPSPACE8K}@


-- drop old indexes
DROP INDEX {SUBST_SCHEMA}.SNMSGV_COMMENT_LASTUPDATE_IDX@

-- create corrected
CREATE INDEX {SUBST_SCHEMA}.SNMSGV_COMMENT_LASTUPDATE_IDX ON {SUBST_SCHEMA}.SNMSGV_COMMENT (ENTRY_ID ASC, LASTUPDATE ASC, COMMENT_ID ASC)
	ALLOW REVERSE SCANS@

--
-- Update Schema Version
--
UPDATE {SUBST_SCHEMA}.SNCORE_SCHEMA SET DBSCHEMAVER= 5 WHERE COMPKEY = 'LC_MSG_VECTOR'@
