-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2016
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
--CONNECT TO PEOPLEDB;

-- grant connect

--GRANT CONNECT ON DATABASE TO LCUSER;

-- grants for Profiles tables

GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.GIVEN_NAME TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.SURNAME TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_EXTENSIONS TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_EXT_DRAFT TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PEOPLE_TAG TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.DEPARTMENT TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.ORGANIZATION TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.COUNTRY TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_TYPE TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMPLOYEE TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PHOTO TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PHOTOBKUP TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PHOTO_GUID TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PRONUNCIATION TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.WORKLOC TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_DRAFT TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.CHG_EMP_DRAFT  TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROF_CONNECTIONS TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.SNPROF_SCHEMA TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROF_CONSTANTS TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EVENTLOG TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_LOGIN TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_PREFS TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.PROFILE_LAST_LOGIN TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.USER_PLATFORM_EVENTS TO LCUSER;
--GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.USER_PLATFORM_EVENTS_INDEX TO LCUSER;
GRANT USAGE ON SEQUENCE EMPINST.USER_PLATFORM_EVENT_INDEX_SEQ TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.TENANT TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_ROLE_MAP TO LCUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_UPDATE_TIMESTAMP TO LCUSER;

GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_TASK TO LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_LMGR TO LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_LMPR TO LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_TREG TO LCUSER;

COMMIT;

--CONNECT RESET;
