-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2013, 2014                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68

SET CURRENT SCHEMA EMPINST;

------
-- Message board removal (fixup37)
------
------
-- table SNMSGV_ENT_PTR
------
ALTER TABLE EMPINST.SNMSGV_ENT_PTR DROP CONSTRAINT SNMSGV_ENT_PTR_EFK; 
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENT_PTR_UDIDX;
COMMIT;

DROP TABLE EMPINST.SNMSGV_ENT_PTR;
COMMIT;

------
-- table SNMSGV_COMMENT
------
ALTER TABLE EMPINST.SNMSGV_COMMENT DROP CONSTRAINT SNMSGV_COMMENT_FK;
COMMIT;

DROP INDEX EMPINST.SNMSGV_COMMENT_ORDER_UIDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_COMMENT_LASTUPDATE_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_COMMENT_PUBLISHED_IDX;
COMMIT;

DROP TABLE EMPINST.SNMSGV_COMMENT;
COMMIT;

------
-- table SNMSGV_ENTRY_REC
------
ALTER TABLE EMPINST.SNMSGV_ENTRY_REC DROP CONSTRAINT SNMSGV_ENTREC_FK;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENTREC_UDX;
COMMIT;

DROP TABLE EMPINST.SNMSGV_ENTRY_REC;
COMMIT;

------
-- table SNMSGV_ENTRY
------
ALTER TABLE EMPINST.SNMSGV_ENTRY DROP CONSTRAINT SNMSGV_ENTRY_FK;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENT_WLKR2_LU_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENT_WLKR2_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENTRY_LASTUPDT2_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENTRY_ORDR2_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENT_WALKER_LU_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENT_WALKER_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENTRY_LASTUPDATE_IDX;
COMMIT;

DROP INDEX EMPINST.SNMSGV_ENTRY_ORDER_IDX;
COMMIT;

DROP TABLE EMPINST.SNMSGV_ENTRY;
COMMIT;

------
-- table SNMSGV_VECTOR
------
ALTER TABLE EMPINST.SNMSGV_VECTOR DROP CONSTRAINT SNMSGV_VECTOR_FK;
COMMIT;

DROP INDEX EMPINST.SNMSGV_VECTOR_RES_ASSOC_UIDX;
COMMIT;

DROP TABLE EMPINST.SNMSGV_VECTOR;
COMMIT;

------
-- DYNA_ATTR removal (fixup38)
------
------
-- DYNA_OBJ_REF
------
ALTER TABLE EMPINST.DYNA_OBJ_REF DROP CONSTRAINT DYNA_DEF_FK;
COMMIT;

DROP INDEX EMPINST.DYNA_RESASSOC_DEFLK;
COMMIT;

DROP INDEX EMPINST.DYNA_RESASSOC_BIDX;
COMMIT;

DROP INDEX EMPINST.DYNA_RESASSOC_SIDX;
COMMIT;

DROP TABLE  EMPINST.DYNA_OBJ_REF;
COMMIT;

------
-- DYNA_DEFS
------
DROP INDEX EMPINST.DYNA_DEFS_APPIDX;
COMMIT;

DROP INDEX EMPINST.DYNA_DEFS_LK;
COMMIT;

DROP TABLE EMPINST.DYNA_DEFS;
COMMIT;

DROP TABLE EMPINST.DYNA_ATTRS;
COMMIT;

------
-- SNCORE_SCHEMA
------
DROP TABLE EMPINST.SNCORE_SCHEMA;
COMMIT;

DELETE FROM EMPINST.PROF_CONSTANTS WHERE PROF_PROPERTY_KEY = 'LA_IDX_STATE';
DELETE FROM EMPINST.PROF_CONSTANTS WHERE PROF_PROPERTY_KEY = 'sys.usrPhotoThumbnail.task';
INSERT INTO EMPINST.PROF_CONSTANTS VALUES ('sys.usrPhotoThumbnail.task', 'complete');
COMMIT;

------
-- Drop FKs (fixup40)
------
ALTER TABLE EMPINST.EMPLOYEE			DROP CONSTRAINT EMPLOYEE_TENANT_FK;
ALTER TABLE EMPINST.GIVEN_NAME			DROP CONSTRAINT GVNAME_TENANT_FK;
ALTER TABLE EMPINST.SURNAME				DROP CONSTRAINT SURNAME_TENANT_FK;
ALTER TABLE EMPINST.PROFILE_EXTENSIONS	DROP CONSTRAINT PROFEXT_TENT_FK;
ALTER TABLE EMPINST.PROFILE_EXT_DRAFT	DROP CONSTRAINT PREXTDRFT_TENT_FK;
ALTER TABLE EMPINST.PEOPLE_TAG			DROP CONSTRAINT PPLTAG_TENT_FK;
ALTER TABLE EMPINST.DEPARTMENT			DROP CONSTRAINT DEPT_TENANT_FK;
ALTER TABLE EMPINST.ORGANIZATION		DROP CONSTRAINT ORG_TENANT_FK;
ALTER TABLE EMPINST.COUNTRY				DROP CONSTRAINT CNTRY_TENANT_FK;
ALTER TABLE EMPINST.EMP_TYPE			DROP CONSTRAINT EMPTYPE_TENANT_FK;
ALTER TABLE EMPINST.PHOTO				DROP CONSTRAINT PHOTO_TENT_FK;
ALTER TABLE EMPINST.PRONUNCIATION		DROP CONSTRAINT PRONUNC_TENT_FK;
ALTER TABLE EMPINST.WORKLOC				DROP CONSTRAINT WORKLOC_TENANT_FK;
ALTER TABLE EMPINST.EMP_DRAFT			DROP CONSTRAINT EMPDRAFT_TENT_FK;
ALTER TABLE EMPINST.CHG_EMP_DRAFT		DROP CONSTRAINT CHEMPDRFT_TENT_FK;
ALTER TABLE EMPINST.PROF_CONNECTIONS	DROP CONSTRAINT CONNECT_TENT_FK;
ALTER TABLE EMPINST.EVENTLOG			DROP CONSTRAINT EVLOG_TENANT_FK;
ALTER TABLE EMPINST.PROFILE_LOGIN		DROP CONSTRAINT LOGIN_TENANT_FK;
ALTER TABLE EMPINST.PROFILE_PREFS		DROP CONSTRAINT PROFPREF_TENT_FK;
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN	DROP CONSTRAINT LASTLOGIN_TENT_FK;
ALTER TABLE EMPINST.USER_PLATFORM_EVENTS DROP CONSTRAINT UPLTEV_TENANT_FK;
COMMIT;

------
-- TENANT_KEY INDEXING (fixup39)
------
------
-- TENANT
------

DROP INDEX EMPINST.TENANT_EXID_UDX;

ALTER TABLE EMPINST.TENANT DROP PRIMARY KEY;
ALTER TABLE EMPINST.TENANT ADD CONSTRAINT TENANT_PK PRIMARY KEY (TENANT_KEY);
COMMIT;

------
-- EMPLOYEE
------
ALTER TABLE EMPINST.EMPLOYEE DROP CONSTRAINT EMPPROF_TENT_UK;
ALTER TABLE EMPINST.EMPLOYEE DROP PRIMARY KEY;
ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (PROF_KEY,TENANT_KEY);

-- mode column from fixup43
ALTER TABLE EMPINST.EMPLOYEE ADD COLUMN PROF_MODE SMALLINT DEFAULT 0 NOT NULL;

DROP INDEX EMPINST.EMP_GUID_UDX;
CREATE UNIQUE INDEX EMPINST.EMP_GUID_UDX ON EMPINST.EMPLOYEE 
		(PROF_GUID ASC, TENANT_KEY);

DROP INDEX EMPINST.MAIL_LOWER_IDX;
CREATE INDEX EMPINST.MAIL_LOWER_IDX ON EMPINST.EMPLOYEE 
		(PROF_MAIL_LOWER ASC, TENANT_KEY);

DROP INDEX EMPINST.UID_LOWER_UDX;
CREATE UNIQUE INDEX EMPINST.UID_LOWER_UDX ON EMPINST.EMPLOYEE 
		(PROF_UID_LOWER ASC, TENANT_KEY);

DROP INDEX EMPINST.DISPNMX;
CREATE INDEX EMPINST.DISPNMX ON EMPINST.EMPLOYEE 
		(PROF_DISPLAY_NAME ASC, TENANT_KEY);

DROP INDEX EMPINST.PROF_DISP_IDX;
CREATE INDEX EMPINST.PROF_DISP_IDX ON EMPINST.EMPLOYEE 
		(PROF_KEY ASC, PROF_DISPLAY_NAME ASC, PROF_SURNAME ASC, PROF_GIVEN_NAME ASC,TENANT_KEY);

DROP INDEX EMPINST.PROF_SNGN_IDX;
CREATE INDEX EMPINST.PROF_SNGN_IDX ON EMPINST.EMPLOYEE 
		(PROF_KEY ASC, PROF_SURNAME ASC, PROF_GIVEN_NAME ASC, TENANT_KEY);

DROP INDEX EMPINST.PROF_GN2_IDX;
CREATE INDEX EMPINST.PROF_GN2_IDX ON EMPINST.EMPLOYEE 
		(PROF_GIVEN_NAME ASC, PROF_KEY ASC, TENANT_KEY);

DROP INDEX EMPINST.PROF_SN2_IDX;
CREATE INDEX EMPINST.PROF_SN2_IDX ON EMPINST.EMPLOYEE 
		(PROF_SURNAME ASC, PROF_KEY ASC, TENANT_KEY);

DROP INDEX EMPINST.LOGIN_LOWER_IDX;
CREATE INDEX EMPINST.LOGIN_LOWER_IDX ON EMPINST.EMPLOYEE
		(PROF_LOGIN_LOWER ASC, TENANT_KEY);

DROP INDEX EMPINST.MANAGER_UID_LOWER_IDX;
CREATE INDEX EMPINST.MANAGER_UID_LOWER_IDX ON EMPINST.EMPLOYEE
		(PROF_MANAGER_UID_LOWER ASC, TENANT_KEY);

DROP INDEX EMPINST.PROFILE_SEARCH_IDX;
CREATE INDEX EMPINST.PROFILE_SEARCH_IDX ON EMPINST.EMPLOYEE
		(PROF_LAST_UPDATE ASC, PROF_KEY ASC, TENANT_KEY);

DROP INDEX EMPINST.PROF_TYPE_IDX;
CREATE INDEX EMPINST.PROF_TYPE_IDX ON EMPINST.EMPLOYEE 
		(PROF_TYPE ASC, TENANT_KEY);

DROP INDEX EMPINST.SRC_UID_LOWER_IDX;
CREATE INDEX EMPINST.SRC_UID_LOWER_IDX ON EMPINST.EMPLOYEE 
		(PROF_SRC_UID_LOWER ASC, PROF_KEY ASC, TENANT_KEY);

DROP INDEX EMPINST.PROF_SRC_UID_IDX;
CREATE INDEX EMPINST.PROF_SRC_UID_IDX ON EMPINST.EMPLOYEE
		(PROF_SOURCE_UID ASC, TENANT_KEY);
		
-- mode index from fixup44
CREATE INDEX EMPINST.PROF_MODE ON EMPINST.EMPLOYEE (PROF_MODE ASC, TENANT_KEY);
COMMIT;

------
-- EMPINST.GIVEN_NAME
------

ALTER TABLE EMPINST.GIVEN_NAME DROP PRIMARY KEY;
ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GIVEN_NAME_PK PRIMARY KEY (PROF_KEY, PROF_GIVENNAME, TENANT_KEY);

--  mode column from fixup 43
ALTER TABLE EMPINST.GIVEN_NAME ADD COLUMN PROF_MODE SMALLINT DEFAULT 0 NOT NULL;

-- indexing from fixup44
DROP INDEX EMPINST.GIVEN_NAME_IDX;
CREATE INDEX EMPINST.GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME (PROF_GIVENNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY);

DROP INDEX EMPINST.GIVEN_NAME_IDX2;
CREATE INDEX EMPINST.GIVEN_NAME_IDX2 ON EMPINST.GIVEN_NAME (PROF_USRSTATE ASC, PROF_MODE ASC, PROF_GIVENNAME ASC, PROF_KEY ASC, TENANT_KEY);

DROP INDEX EMPINST.GIVEN_NAMEX;
CREATE INDEX EMPINST.GIVEN_NAMEX ON EMPINST.GIVEN_NAME (PROF_KEY ASC, PROF_GIVENNAME ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY);

------
-- EMPINST.SURNAME
------

ALTER TABLE EMPINST.SURNAME DROP PRIMARY KEY;
ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_PK PRIMARY KEY (PROF_KEY, PROF_SURNAME, TENANT_KEY);

--  mode column from fixup 43
ALTER TABLE EMPINST.SURNAME ADD COLUMN PROF_MODE SMALLINT DEFAULT 0 NOT NULL;

-- indexing from fixup44
DROP INDEX EMPINST.SURNAME_IDX;
CREATE INDEX EMPINST.SURNAME_IDX ON EMPINST.SURNAME (PROF_SURNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY);

DROP INDEX EMPINST.SURNAME_IDX2;
CREATE INDEX EMPINST.SURNAME_IDX2 ON EMPINST.SURNAME (PROF_USRSTATE ASC, PROF_MODE ASC, PROF_SURNAME ASC, PROF_KEY ASC, TENANT_KEY);

DROP INDEX EMPINST.SURNAMEX;
CREATE INDEX EMPINST.SURNAMEX ON EMPINST.SURNAME (PROF_KEY ASC, PROF_SURNAME ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY);

------
-- EMPINST.PROFILE_EXTENSIONS
------

ALTER TABLE EMPINST.PROFILE_EXTENSIONS DROP PRIMARY KEY;
ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROF_EXT_PK PRIMARY KEY (PROF_KEY, PROF_PROPERTY_ID, TENANT_KEY);

DROP INDEX EMPINST.PROFILE_EXTENSIONS_IDX;
CREATE INDEX EMPINST.PROFILE_EXTENSIONS_IDX ON EMPINST.PROFILE_EXTENSIONS 
		(PROF_KEY ASC, TENANT_KEY) CLUSTER;

DROP INDEX EMPINST.PROFILE_EXTENSIONS_IDX2;
CREATE INDEX EMPINST.PROFILE_EXTENSIONS_IDX2 ON EMPINST.PROFILE_EXTENSIONS
		(PROF_NAME ASC, PROF_PROPERTY_ID ASC, TENANT_KEY);

------
-- EMPINST.PROFILE_EXT_DRAFT
------

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT DROP PRIMARY KEY;
ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT EXT_DRAFT_PK PRIMARY KEY (PROF_KEY, TENANT_KEY, PROF_UPDATE_SEQUENCE);

------
-- EMPINST.PEOPLE_TAG
------

ALTER TABLE EMPINST.PEOPLE_TAG DROP PRIMARY KEY;
ALTER TABLE EMPINST.PEOPLE_TAG ADD CONSTRAINT PEOPLE_TAG_PK PRIMARY KEY (PROF_TAG_ID, TENANT_KEY);

DROP INDEX EMPINST.PEOPLE_TAG_IDX;
CREATE INDEX EMPINST.PEOPLE_TAG_IDX ON EMPINST.PEOPLE_TAG 
		(PROF_TAG ASC, PROF_TARGET_KEY ASC, TENANT_KEY) ;

DROP INDEX EMPINST.PEOPLE_TAG_IDX2;
CREATE INDEX EMPINST.PEOPLE_TAG_IDX2 ON EMPINST.PEOPLE_TAG 
		(PROF_TARGET_KEY ASC, PROF_TAG ASC, PROF_SOURCE_KEY ASC, TENANT_KEY) CLUSTER;
		
DROP INDEX EMPINST.PEOPLE_TAG_UDX;
CREATE UNIQUE INDEX EMPINST.PEOPLE_TAG_UDX ON EMPINST.PEOPLE_TAG 
		(PROF_SOURCE_KEY ASC, PROF_TARGET_KEY ASC, PROF_TAG ASC, TENANT_KEY) ;

------
-- EMPINST.DEPARTMENT
------

ALTER TABLE EMPINST.DEPARTMENT DROP PRIMARY KEY;
ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY (PROF_DEPARTMENT_CODE, TENANT_KEY);

------
-- EMPINST.ORGANIZATION
------

ALTER TABLE EMPINST.ORGANIZATION DROP PRIMARY KEY;
ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_PK PRIMARY KEY (PROF_ORGANIZATION_CODE, TENANT_KEY);

------
-- EMPINST.COUNTRY
------

ALTER TABLE EMPINST.COUNTRY DROP PRIMARY KEY;
ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (PROF_ISO_COUNTRY_CODE, TENANT_KEY);

------
-- EMPINST.EMP_TYPE
------

ALTER TABLE EMPINST.EMP_TYPE DROP PRIMARY KEY;
ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_PK PRIMARY KEY (PROF_EMPLOYEE_TYPE, TENANT_KEY);

------
-- EMPINST.PHOTO
------

ALTER TABLE EMPINST.PHOTO DROP CONSTRAINT PHOTO_TENT_UK;
ALTER TABLE EMPINST.PHOTO DROP PRIMARY KEY;
ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_PK PRIMARY KEY (PROF_KEY, TENANT_KEY);

DROP INDEX EMPINST.PHOTOIDX;
CREATE INDEX EMPINST.PHOTOIDX ON EMPINST.PHOTO 
		(PROF_UPDATED DESC, TENANT_KEY);

------
--EMPINST.PRONUNCIATION
------
ALTER TABLE EMPINST.PRONUNCIATION DROP CONSTRAINT PRONUNC_TENT_UK;
ALTER TABLE EMPINST.PRONUNCIATION DROP PRIMARY KEY;
ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNCIATION_PK PRIMARY KEY (PROF_KEY, TENANT_KEY);

DROP INDEX EMPINST.PRONOUNCEIDX;
CREATE INDEX EMPINST.PRONOUNCEIDX ON EMPINST.PRONUNCIATION 
		(PROF_UPDATED DESC, TENANT_KEY);

------
-- EMPINST.WORKLOC
------

ALTER TABLE EMPINST.WORKLOC DROP PRIMARY KEY;
ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_PK PRIMARY KEY (PROF_WORK_LOC, TENANT_KEY);

------
-- EMPINST.EMP_DRAFT 
------

ALTER TABLE EMPINST.EMP_DRAFT DROP PRIMARY KEY;
ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMP_DRAFT_PK PRIMARY KEY (PROF_KEY, PROF_UPDATE_SEQUENCE, TENANT_KEY);

DROP INDEX EMPINST.EMP_DRAFT_PK;

DROP INDEX EMPINST.ED_MAIL;
CREATE INDEX EMPINST.ED_MAIL ON EMPINST.EMP_DRAFT 
		(PROF_MAIL ASC,TENANT_KEY);

DROP INDEX EMPINST.ED_DISPNMX;
CREATE INDEX EMPINST.ED_DISPNMX ON EMPINST.EMP_DRAFT 
		(PROF_DISPLAY_NAME ASC, TENANT_KEY);

DROP INDEX EMPINST.ED_UPDATE_IDX;
CREATE INDEX EMPINST.ED_UPDATE_IDX ON EMPINST.EMP_DRAFT 
		(PROF_LAST_UPDATE DESC, PROF_KEY DESC, PROF_UPDATE_SEQUENCE DESC, TENANT_KEY);

------
-- EMPINST.PROF_CONNECTIONS
------

ALTER TABLE EMPINST.PROF_CONNECTIONS DROP PRIMARY KEY;
ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECTIONS_PK PRIMARY KEY (PROF_CONNECTION_ID, TENANT_KEY);

DROP INDEX EMPINST.CONN_UDX;
CREATE UNIQUE INDEX EMPINST.CONN_UDX ON EMPINST.PROF_CONNECTIONS
		(PROF_SOURCE_KEY ASC, PROF_TARGET_KEY ASC, PROF_TYPE ASC, TENANT_KEY);

-- Main index to select a users connections for showing friends in UI
DROP INDEX EMPINST.CONN_INDEX1;
CREATE INDEX EMPINST.CONN_INDEX1 ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_LASTMOD DESC, PROF_TARGET_KEY ASC, TENANT_KEY);

-- Friends in common; get list of connection keys 'isConnection' query
DROP INDEX EMPINST.CONN_INDEX2;
CREATE INDEX EMPINST.CONN_INDEX2 ON EMPINST.PROF_CONNECTIONS 
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_TARGET_KEY ASC, PROF_LASTMOD ASC, TENANT_KEY);

-- Reverse index for deletes
DROP INDEX EMPINST.CONN_REV_IDX;
CREATE INDEX EMPINST.CONN_REV_IDX ON EMPINST.PROF_CONNECTIONS 
	(PROF_TARGET_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_SOURCE_KEY ASC, PROF_LASTMOD ASC, TENANT_KEY);

------
-- EMPINST.EVENTLOG
------

ALTER TABLE EMPINST.EVENTLOG DROP PRIMARY KEY;
ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVENTLOG_PK PRIMARY KEY (EVENT_KEY, TENANT_KEY);

DROP INDEX EMPINST.EVLOG_TYPE_IDX;
CREATE INDEX EMPINST.EVLOG_TYPE_IDX ON EMPINST.EVENTLOG
	(EVENT_TYPE ASC,CREATED ASC, EVENT_KEY ASC, TENANT_KEY);

DROP INDEX EMPINST.EVLOG_AUDIT_IDX;
CREATE INDEX EMPINST.EVLOG_AUDIT_IDX ON EMPINST.EVENTLOG
	(ISSYSEVENT ASC, EVENT_KEY ASC, TENANT_KEY);

------
--EMPINST.PROFILE_LOGIN
------

ALTER TABLE EMPINST.PROFILE_LOGIN DROP PRIMARY KEY;
ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT PROFILE_LOGIN_PK PRIMARY KEY (PROF_KEY, PROF_LOGIN, TENANT_KEY);

------
-- EMPINST.PROFILE_PREFS
------

ALTER TABLE EMPINST.PROFILE_PREFS DROP CONSTRAINT PROFPREF_TENT_UK;
ALTER TABLE EMPINST.PROFILE_PREFS DROP PRIMARY KEY;
ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFILE_PREFS_PK PRIMARY KEY (PROF_KEY, PROF_PREFID, TENANT_KEY);

------
-- EMPINST.PROFILE_LAST_LOGIN
------

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN DROP CONSTRAINT LASTLOGIN_TENT_UK;
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN DROP PRIMARY KEY;
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_PK PRIMARY KEY (PROF_KEY, TENANT_KEY);

------
-- EMPINST.USER_PLATFORM_EVENTS
------

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS DROP PRIMARY KEY;
ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT PLATFORMEVENTS_PK PRIMARY KEY (EVENT_KEY, TENANT_KEY);

------
-- TENANT_KEY = TENANT_EXID
------

UPDATE EMPINST.TENANT SET TENANT_EXID = '00000000-0000-0000-0000-040508202233' WHERE TENANT_KEY = '00000000-0000-0000-0000-040508202233';

--====
-- Support a type on a tag
--====
ALTER TABLE EMPINST.PEOPLE_TAG
	ADD COLUMN PROF_TYPE VARCHAR(36) CCSID 1208 DEFAULT 'general' NOT NULL;		

CREATE INDEX EMPINST.PEOPLE_TAG_IDX3 ON EMPINST.PEOPLE_TAG 
		(PROF_TAG ASC, PROF_TYPE ASC, TENANT_KEY) ;

DROP INDEX EMPINST.PEOPLE_TAG_UDX;
CREATE UNIQUE INDEX EMPINST.PEOPLE_TAG_UDX ON EMPINST.PEOPLE_TAG 
	(PROF_SOURCE_KEY ASC, PROF_TARGET_KEY ASC, PROF_TAG ASC, PROF_TYPE ASC, TENANT_KEY);
COMMIT;

--====
-- Extension attribute labels (fixup42)
--====

ALTER TABLE EMPINST.PROFILE_EXTENSIONS
	ADD COLUMN SUPPORT_LABEL SMALLINT DEFAULT 0 NOT NULL;

--====
-- EMPLOYEE, NAMES: PROF_MODE for internal/external designation
--====

-- incorporated above
--ALTER TABLE EMPINST.EMPLOYEE
--	ADD COLUMN PROF_MODE SMALLINT DEFAULT 0 NOT NULL@

-- incorporated above
--ALTER TABLE EMPINST.GIVEN_NAME
--	ADD COLUMN PROF_MODE SMALLINT DEFAULT 0 NOT NULL@

-- incorporated above
--ALTER TABLE EMPINST.SURNAME
--	ADD COLUMN PROF_MODE SMALLINT DEFAULT 0 NOT NULL@


--====
-- fixup44 NAME table indexing incorporated above
-- fixup44 EMPLOYEE indexing incorporated above
--====

--====
-- EMPLOYEE ROLE MAPPING (fixup45)
--====

	CREATE TABLE EMPINST.EMP_ROLE_MAP(
	MAP_KEY        VARCHAR(36) CCSID 1208 NOT NULL ,
	PROF_KEY       VARCHAR(36) CCSID 1208 NOT NULL ,
	ROLE_ID        VARCHAR(128) CCSID 1208 NOT NULL ,
	CREATED        TIMESTAMP NOT NULL ,
	TENANT_KEY	   VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
) ;

GRANT DELETE, INSERT, SELECT, UPDATE ON EMPINST.EMP_ROLE_MAP TO LCUSER;

ALTER TABLE EMPINST.EMP_ROLE_MAP ADD CONSTRAINT EMPINST.EMP_ROLEMAP_PK PRIMARY KEY (MAP_KEY, TENANT_KEY);

CREATE UNIQUE INDEX EMPINST.EMP_ROLE_UDX ON EMPINST.EMP_ROLE_MAP (PROF_KEY, ROLE_ID, TENANT_KEY);

--====
-- PHOTO BACKUP
--====

CREATE TABLE EMPINST.PHOTOBKUP  (
		  PROF_KEY VARCHAR(36) CCSID 1208 NOT NULL , 
		  PROF_FILE_TYPE VARCHAR(50) CCSID 1208 , 
		  PROF_UPDATED TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
		  PROF_IMAGE BLOB(50000) ,
		  PROF_THUMBNAIL BLOB(10000) ,
		  TENANT_KEY		VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
	) ;

ALTER TABLE EMPINST.PHOTOBKUP ADD CONSTRAINT EMPINST.PHOTOBK_PK PRIMARY KEY (PROF_KEY, TENANT_KEY);
COMMIT;

------
-- Update schema version
------

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 46, RELEASEVER='5.0.0.0' WHERE COMPKEY='Profiles';
COMMIT;

