-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2016
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.GIVEN_NAME TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.SURNAME TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PROFILE_EXTENSIONS TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PROFILE_EXT_DRAFT TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PEOPLE_TAG TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.DEPARTMENT TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.ORGANIZATION TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.COUNTRY TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.EMP_TYPE TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.EMPLOYEE TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PHOTO TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PHOTOBKUP TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PHOTO_GUID TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PRONUNCIATION TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.WORKLOC TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.EMP_DRAFT TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.CHG_EMP_DRAFT TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PROF_CONNECTIONS TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.SNPROF_SCHEMA TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PROF_CONSTANTS TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.EVENTLOG TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PROFILE_LOGIN TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PROFILE_PREFS TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.PROFILE_LAST_LOGIN TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.TENANT TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.EMP_ROLE_MAP TO PROFUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON EMPINST.EMP_UPDATE_TIMESTAMP TO PROFUSER_ROLE;

GRANT ALL ON EMPINST.USER_PLATFORM_EVENT_INDEX_SEQ TO PROFUSER_ROLE;

GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.USER_PLATFORM_EVENTS TO PROFUSER_ROLE;
--GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.USER_PLATFORM_EVENTS_INDEX TO PROFUSER_ROLE;
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_TASK TO PROFUSER_ROLE;
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_LMGR TO PROFUSER_ROLE;
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_LMPR TO PROFUSER_ROLE;
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILES_SCHEDULER_TREG TO PROFUSER_ROLE;

GRANT ALTER SESSION TO PROFUSER_ROLE;
GRANT CREATE SESSION TO PROFUSER_ROLE;
GRANT CREATE SYNONYM TO PROFUSER_ROLE;
GRANT SELECT_CATALOG_ROLE, PROFUSER_ROLE TO PROFUSER;

COMMIT;
QUIT;
