-- ***************************************************************** 
--                                                                   
-- HCL Confidential
--                                                                   
-- OCO Source Materials
--                                                                   
-- Copyright HCL Technologies Limited 2007, 2022
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
CREATE SMALLFILE TABLESPACE "PROFREGTABSPACE" DATAFILE 'PROFREGTABSPACE' 
    SIZE 100M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED LOGGING 
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "PROFINDEXTABSPACE" DATAFILE 'PROFINDEXTABSPACE' 
    SIZE 100M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED LOGGING 
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


CREATE ROLE PROFUSER_ROLE;
CREATE USER "PROFUSER" PROFILE "DEFAULT" IDENTIFIED BY "&1" DEFAULT TABLESPACE "PROFREGTABSPACE" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
CREATE USER "EMPINST" PROFILE "DEFAULT" IDENTIFIED BY "&1" DEFAULT TABLESPACE "PROFREGTABSPACE" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

COMMIT;

GRANT CONNECT TO EMPINST;
GRANT CREATE SYNONYM TO EMPINST;
GRANT ALTER SESSION TO EMPINST;
GRANT CREATE SESSION TO EMPINST;
ALTER USER EMPINST DEFAULT ROLE ALL;
GRANT ALTER TABLESPACE TO EMPINST; 
GRANT UNLIMITED TABLESPACE TO EMPINST; 

COMMIT;

ALTER SESSION SET CURRENT_SCHEMA = EMPINST;

--------------------------------------
-- CREATE SEQUENCES
--------------------------------------
CREATE SEQUENCE EMPINST.EXT_DRAFT_SEQ;

CREATE SEQUENCE EMPINST.EMP_DRAFT_SEQ;

CREATE SEQUENCE EMPINST.CHG_EMP_DRAFT_SEQ1;

CREATE SEQUENCE EMPINST.CHG_EMP_DRAFT_SEQ2;

------------------------------------------------
-- DDL Statements for table "EMPINST"."SNCOMM_SCHEMA"
------------------------------------------------

CREATE TABLE EMPINST.SNPROF_SCHEMA (
	COMPKEY			VARCHAR2(36) NOT NULL,
	DBSCHEMAVER		NUMBER(19,0) NOT NULL,
	PRESCHEMAVER	VARCHAR2(10) DEFAULT '0' NOT NULL,
	POSTSCHEMAVER	VARCHAR2(10) DEFAULT '0' NOT NULL,
	RELEASEVER		VARCHAR2(32)
)
	TABLESPACE PROFREGTABSPACE;

INSERT INTO EMPINST.SNPROF_SCHEMA (COMPKEY, DBSCHEMAVER, POSTSCHEMAVER, RELEASEVER) VALUES ('Profiles', 56, '56.0', '8.0.0.0');

------------------------------------------------
-- DDL Statements for table "EMPINST"."TENANT"
------------------------------------------------

CREATE TABLE "EMPINST"."TENANT"  (
	"TENANT_KEY"		VARCHAR2(36)	NOT NULL,
	"TENANT_EXID"		VARCHAR2(256)	NOT NULL,
	"TENANT_NAME"		VARCHAR2(256)	NOT NULL,
	"TENANT_NAME_LOWER"	VARCHAR2(256)	NOT NULL,
	"TENANT_STATE"		NUMBER(19,0)	NOT NULL,
	"TENANT_CREATED"	TIMESTAMP NOT NULL,
	--"TENANT_CREATED_BY_KEY" VARCHAR2(36) NOT NULL,
	"TENANT_LASTUPDATE"	TIMESTAMP	NOT NULL
	--TENANT_LASTMOD_BY_KEY VARCHAR(36) NOT NULL
)
	TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.TENANT ADD CONSTRAINT TENANT_PK PRIMARY KEY (TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE UNIQUE INDEX EMPINST."TENANT_EXID_UDX" ON EMPINST."TENANT" ("TENANT_EXID" ASC);

INSERT INTO EMPINST.TENANT(
	TENANT_KEY           ,
	TENANT_EXID          ,
	TENANT_NAME          ,
	TENANT_NAME_LOWER    ,
	TENANT_STATE         ,
	TENANT_CREATED       ,
	--TENANT_CREATED_BY_KEY,
	TENANT_LASTUPDATE
	--TENANT_LASTMOD_BY_KEY
)
VALUES(
	'a',
	'a',
	'Standard Tenant',
	'standard tenant',
	0,
	SYSDATE,
	-- no admin,
	SYSDATE
	-- no admin
);

------------------------------------------------
-- DDL Statements for table "EMPINST"."EMPLOYEE"
------------------------------------------------

CREATE TABLE EMPINST."EMPLOYEE"  (
  "PROF_KEY" VARCHAR2(36) NOT NULL,
  "PROF_UID" VARCHAR2(256) NOT NULL ,
  "PROF_UID_LOWER" VARCHAR2(256) NOT NULL ,
  "PROF_IDHASH" VARCHAR2(256) DEFAULT '?' NOT NULL,
  "PROF_LAST_UPDATE" TIMESTAMP NOT NULL,
  "PROF_MAIL" VARCHAR2(256) ,
  "PROF_MAIL_LOWER" VARCHAR2(256) ,
  "PROF_GUID" VARCHAR2(256) NOT NULL,
  "PROF_SOURCE_UID" VARCHAR2(256) NOT NULL,
  "PROF_DISPLAY_NAME" VARCHAR2(256) ,
  "PROF_LOGIN" VARCHAR2(256) ,
  "PROF_LOGIN_LOWER" VARCHAR2(256) ,
  "PROF_GIVEN_NAME"		VARCHAR2(128)  ,
  "PROF_SURNAME"		VARCHAR2(128) , 
  "PROF_ALTERNATE_LAST_NAME" VARCHAR2(64) ,
  "PROF_PREFERRED_FIRST_NAME" VARCHAR2(32) ,
  "PROF_PREFERRED_LAST_NAME" VARCHAR2(64) ,
  "PROF_TYPE"			VARCHAR2(64),
  "PROF_MANAGER_UID" VARCHAR2(256) ,
  "PROF_MANAGER_UID_LOWER" VARCHAR2(256) ,
  "PROF_SECRETARY_UID" VARCHAR2(256) ,
  "PROF_IS_MANAGER" CHAR(1) ,
  "PROF_GROUPWARE_EMAIL" VARCHAR2(128) ,
  "PROF_GW_EMAIL_LOWER" VARCHAR2(128) ,
  "PROF_JOB_RESPONSIBILITIES" VARCHAR2(128) ,
  "PROF_ORGANIZATION_IDENTIFIER" VARCHAR2(64) ,
  "PROF_ISO_COUNTRY_CODE" VARCHAR2(3) ,
  "PROF_FAX_TELEPHONE_NUMBER" VARCHAR2(32) ,
  "PROF_IP_TELEPHONE_NUMBER" VARCHAR2(32),
  "PROF_MOBILE" VARCHAR2(32) ,
  "PROF_PAGER" VARCHAR2(32) ,
  "PROF_TELEPHONE_NUMBER" VARCHAR2(32) ,
  "PROF_WORK_LOCATION" VARCHAR2(32) ,
  "PROF_BUILDING_IDENTIFIER" VARCHAR2(64) ,
  "PROF_DEPARTMENT_NUMBER" VARCHAR2(24) ,
  "PROF_EMPLOYEE_TYPE" VARCHAR2(256) ,
  "PROF_FLOOR" VARCHAR2(16) ,
  "PROF_EMPLOYEE_NUMBER" VARCHAR2(16) ,
  "PROF_PAGER_TYPE" VARCHAR2(16) ,
  "PROF_PAGER_ID" VARCHAR2(32) ,
  "PROF_PAGER_SERVICE_PROVIDER" VARCHAR2(50) ,
  "PROF_PHYSICAL_DELIVERY_OFFICE" VARCHAR2(64) ,
  "PROF_PREFERRED_LANGUAGE" VARCHAR2(100) ,
  "PROF_SHIFT" VARCHAR2(4) ,
  "PROF_TITLE" VARCHAR2(256) ,
  "PROF_COURTESY_TITLE" VARCHAR2(64) ,
  "PROF_TIMEZONE" VARCHAR2(64) , 
  "PROF_NATIVE_LAST_NAME" VARCHAR2(256) ,
  "PROF_NATIVE_FIRST_NAME" VARCHAR2(256) ,
  "PROF_BLOG_URL" VARCHAR2(256) ,
  "PROF_FREEBUSY_URL" VARCHAR2(256) ,
  "PROF_CALENDAR_URL" VARCHAR2(256) ,
  "PROF_DESCRIPTION" CLOB ,
  "PROF_EXPERIENCE" CLOB ,
  "PROF_SOURCE_URL" VARCHAR2(512),
  "PROF_SRC_UID_LOWER" VARCHAR2(256) NOT NULL,
  "TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL,
  "H_TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL,
  "PROF_STATE"	INTEGER DEFAULT 0 NOT NULL,
  "PROF_MODE"	NUMBER(5,0) DEFAULT 0 NOT NULL
)
  TABLESPACE PROFREGTABSPACE ;

-- DDL Statements for indexes, constraints on Table "EMPINST"."EMPLOYEE"

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (PROF_KEY,TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE UNIQUE INDEX EMPINST."EMP_GUID_UDX" ON EMPINST."EMPLOYEE" 
		("PROF_GUID" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."MAIL_LOWER_IDX" ON EMPINST."EMPLOYEE" 
		("PROF_MAIL_LOWER" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE UNIQUE INDEX EMPINST."UID_LOWER_UDX" ON EMPINST."EMPLOYEE" 
		("PROF_UID_LOWER" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
		
CREATE INDEX EMPINST."IDHASH_UDX" ON EMPINST."EMPLOYEE"
		("PROF_IDHASH" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."DISPNMX" ON EMPINST."EMPLOYEE"
		("PROF_DISPLAY_NAME" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_DISP_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_KEY" ASC, "PROF_DISPLAY_NAME" ASC, "PROF_SURNAME" ASC, "PROF_GIVEN_NAME" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_SNGN_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_KEY" ASC, "PROF_SURNAME" ASC, "PROF_GIVEN_NAME" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_GN2_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_GIVEN_NAME" ASC, "PROF_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_SN2_IDX" ON "EMPINST"."EMPLOYEE" 
		("PROF_SURNAME" ASC, "PROF_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;     				
				
CREATE INDEX EMPINST."LOGIN_LOWER_IDX" ON EMPINST."EMPLOYEE" 
		("PROF_LOGIN_LOWER" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."MANAGER_UID_LOWER_IDX" ON EMPINST."EMPLOYEE" 
		("PROF_MANAGER_UID_LOWER" ASC) TABLESPACE PROFINDEXTABSPACE;
		
CREATE INDEX "EMPINST"."PROFILE_SEARCH_IDX" ON "EMPINST"."EMPLOYEE"
        ("PROF_LAST_UPDATE" ASC, "PROF_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_TYPE_IDX" ON "EMPINST"."EMPLOYEE"
        ("PROF_TYPE" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."SRC_UID_LOWER_IDX" ON "EMPINST"."EMPLOYEE"
        ("PROF_SRC_UID_LOWER" ASC, "PROF_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
        
CREATE INDEX EMPINST.PROF_SRC_UID_IDX ON EMPINST.EMPLOYEE
	(PROF_SOURCE_UID ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST.PROF_MODE ON EMPINST.EMPLOYEE 
	(PROF_MODE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."GIVEN_NAME"
------------------------------------------------

CREATE TABLE EMPINST."GIVEN_NAME"  (
  "PROF_KEY" VARCHAR2(36) NOT NULL , 
  "PROF_GIVENNAME" VARCHAR2(128) NOT NULL ,
  "PROF_NAME_SOURCE" NUMBER(19,0) DEFAULT 0,
  "PROF_USRSTATE" NUMBER(19,0) DEFAULT 0 NOT NULL,
  "PROF_MODE"	NUMBER(5,0) DEFAULT 0 NOT NULL,
  "TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GIVEN_NAME_PK PRIMARY KEY (PROF_KEY, PROF_GIVENNAME, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

--CREATE INDEX EMPINST.GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME (PROF_GIVENNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME (PROF_GIVENNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

--CREATE INDEX EMPINST.GIVEN_NAME_IDX2 ON EMPINST.GIVEN_NAME (PROF_USRSTATE ASC, PROF_GIVENNAME ASC, PROF_KEY ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.GIVEN_NAME_IDX2 ON EMPINST.GIVEN_NAME (PROF_USRSTATE ASC, PROF_MODE ASC, PROF_GIVENNAME ASC, PROF_KEY ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

--CREATE INDEX EMPINST.GIVEN_NAMEX ON EMPINST.GIVEN_NAME (PROF_KEY ASC, PROF_GIVENNAME ASC, PROF_USRSTATE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.GIVEN_NAMEX ON EMPINST.GIVEN_NAME (PROF_KEY ASC, PROF_GIVENNAME ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."SURNAME"
------------------------------------------------ 

CREATE TABLE EMPINST."SURNAME"  (
  "PROF_KEY" VARCHAR2(36) NOT NULL , 
  "PROF_SURNAME" VARCHAR2(128) NOT NULL ,
  "PROF_NAME_SOURCE" NUMBER(19,0) DEFAULT 0,
  "PROF_USRSTATE" NUMBER(19,0) DEFAULT 0 NOT NULL,
  "PROF_MODE"	NUMBER(5,0) DEFAULT 0 NOT NULL,
  "TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_PK PRIMARY KEY (PROF_KEY, PROF_SURNAME, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

--CREATE INDEX EMPINST.SURNAME_IDX ON EMPINST.SURNAME (PROF_SURNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.SURNAME_IDX ON EMPINST.SURNAME (PROF_SURNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

--CREATE INDEX EMPINST.SURNAME_IDX2 ON EMPINST.SURNAME (PROF_USRSTATE ASC, PROF_SURNAME ASC, PROF_KEY ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.SURNAME_IDX2 ON EMPINST.SURNAME (PROF_USRSTATE ASC, PROF_MODE ASC, PROF_SURNAME ASC, PROF_KEY ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

--CREATE INDEX EMPINST.SURNAMEX ON EMPINST.SURNAME (PROF_KEY ASC, PROF_SURNAME ASC, PROF_USRSTATE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.SURNAMEX ON EMPINST.SURNAME (PROF_KEY ASC, PROF_SURNAME ASC, PROF_USRSTATE ASC, PROF_MODE ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."PROFILE_EXTENSIONS"
------------------------------------------------

CREATE TABLE EMPINST.PROFILE_EXTENSIONS  (
  PROF_KEY            VARCHAR2(36) NOT NULL ,
  PROF_PROPERTY_ID    VARCHAR2(64) NOT NULL ,  
  PROF_EXT_KEY        VARCHAR2(256) ,
  PROF_NAME           VARCHAR2(256) ,
  PROF_DATA_TYPE      VARCHAR2(64) ,   
  PROF_VALUE          VARCHAR2(1024),
  SUPPORT_LABEL       NUMBER(5,0) DEFAULT 0 NOT NULL,
  PROF_VALUE_EXTENDED BLOB,
  TENANT_KEY          VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)  
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROF_EXT_PK PRIMARY KEY (PROF_KEY, PROF_PROPERTY_ID, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."PROFILE_EXTENSIONS_IDX" ON EMPINST."PROFILE_EXTENSIONS" 
		("PROF_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."PROFILE_EXTENSIONS_IDX2" ON EMPINST."PROFILE_EXTENSIONS" 
		("PROF_NAME" ASC, "PROF_PROPERTY_ID" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;


------------------------------------------------
-- DDL Statements for table "EMPINST"."PROFILE_EXT_DRAFT"
------------------------------------------------

CREATE TABLE EMPINST.PROFILE_EXT_DRAFT  (
  PROF_UPDATE_SEQUENCE NUMBER(19,0) NOT NULL,
  PROF_KEY             VARCHAR2(36) NOT NULL ,
  PROF_PROPERTY_ID     VARCHAR2(64) NOT NULL ,  
  PROF_EXT_KEY         VARCHAR2(256) ,
  PROF_NAME            VARCHAR2(256) ,
  PROF_DATA_TYPE       VARCHAR2(64) ,   
  PROF_VALUE           VARCHAR2(1024),
  PROF_VALUE_EXTENDED  BLOB,
  TENANT_KEY           VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)  
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT EXT_DRAFT_PK PRIMARY KEY (PROF_KEY, PROF_UPDATE_SEQUENCE, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."PEOPLE_TAG"
------------------------------------------------

CREATE TABLE EMPINST.PEOPLE_TAG (
  PROF_TAG_ID     VARCHAR2(36) NOT NULL ,
  PROF_SOURCE_KEY VARCHAR2(36) NOT NULL,
  PROF_TARGET_KEY VARCHAR2(36) NOT NULL,
  PROF_TAG        VARCHAR2(256) NOT NULL,
  PROF_TYPE 	  VARCHAR2(36) DEFAULT 'general' NOT NULL,  
  TENANT_KEY      VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL,
  CONSTRAINT PEOPLE_TAG_PK PRIMARY KEY ( PROF_TAG_ID, TENANT_KEY ) 
)  
  ORGANIZATION INDEX
  TABLESPACE PROFREGTABSPACE;

CREATE INDEX EMPINST."PEOPLE_TAG_IDX" ON EMPINST."PEOPLE_TAG" 
		("PROF_TAG" ASC, "PROF_TARGET_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."PEOPLE_TAG_IDX2" ON EMPINST."PEOPLE_TAG" 
	("PROF_TARGET_KEY" ASC, "PROF_TAG" ASC, "PROF_SOURCE_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."PEOPLE_TAG_IDX3" ON EMPINST."PEOPLE_TAG" 
		("PROF_TAG" ASC, "PROF_TYPE" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
	
CREATE UNIQUE INDEX EMPINST."PEOPLE_TAG_UDX" ON EMPINST."PEOPLE_TAG" 
		("PROF_SOURCE_KEY" ASC, "PROF_TARGET_KEY" ASC, "PROF_TAG" ASC, "PROF_TYPE" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."DEPARTMENT"
------------------------------------------------
	
CREATE TABLE EMPINST."DEPARTMENT"  (
  "PROF_DEPARTMENT_CODE"	VARCHAR2(24) NOT NULL , 
  "PROF_DEPARTMENT_TITLE"	VARCHAR2(256) ,
  "TENANT_KEY"		     VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL 
) 
  TABLESPACE PROFREGTABSPACE;
  
ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY (PROF_DEPARTMENT_CODE, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."ORGANIZATION"
------------------------------------------------
 
CREATE TABLE EMPINST."ORGANIZATION"  (
  "PROF_ORGANIZATION_CODE" VARCHAR2(64) NOT NULL , 
  "PROF_ORGANIZATION_TITLE" VARCHAR2(256) ,
  "TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL 
) 
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_PK PRIMARY KEY (PROF_ORGANIZATION_CODE, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."COUNTRY"
------------------------------------------------

CREATE TABLE EMPINST."COUNTRY"  (
  "PROF_ISO_COUNTRY_CODE" VARCHAR2(3) NOT NULL , 
  "PROF_COUNTRY_DESC" VARCHAR2(256) ,
  "TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)  
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (PROF_ISO_COUNTRY_CODE, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."EMP_TYPE"
------------------------------------------------

CREATE TABLE EMPINST."EMP_TYPE"  (
  "PROF_EMPLOYEE_TYPE" VARCHAR2(256) NOT NULL , 
  "PROF_EMPLOYEE_DESC" VARCHAR2(256) ,
  "TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
) 
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_PK PRIMARY KEY (PROF_EMPLOYEE_TYPE, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."PHOTO"
------------------------------------------------

CREATE TABLE EMPINST.PHOTO  (
  PROF_KEY       VARCHAR2(36) NOT NULL , 
  PROF_FILE_TYPE VARCHAR2(50) , 
  PROF_UPDATED   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PROF_IMAGE     BLOB ,
  PROF_THUMBNAIL BLOB ,
  TENANT_KEY     VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
) 
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_PK PRIMARY KEY (PROF_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."PHOTOIDX" ON EMPINST."PHOTO" 
		("PROF_UPDATED" DESC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE TABLE EMPINST.PHOTOBKUP  (
  PROF_KEY       VARCHAR2(36) NOT NULL , 
  PROF_FILE_TYPE VARCHAR2(50) , 
  PROF_UPDATED   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PROF_IMAGE     BLOB ,
  PROF_THUMBNAIL BLOB ,
  TENANT_KEY     VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
) 
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.PHOTOBKUP ADD CONSTRAINT PHOTOBK_PK PRIMARY KEY (PROF_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE TABLE EMPINST.PHOTO_GUID  (
  PROF_GUID      VARCHAR2(36) NOT NULL , 
  PROF_FILE_TYPE VARCHAR2(50) , 
  PROF_UPDATED   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PROF_IMAGE     BLOB ,
  PROF_THUMBNAIL BLOB ,
  H_TENANT_KEY   VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.PHOTO_GUID ADD CONSTRAINT PHOTO_GUID_PK PRIMARY KEY (PROF_GUID) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."PRONUNCIATION"
------------------------------------------------

CREATE TABLE EMPINST."PRONUNCIATION"  (
  PROF_KEY        VARCHAR2(36) NOT NULL , 
  PROF_PRONOUNCE  BLOB , 
  PROF_UPDATED    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PROF_FILE_TYPE  VARCHAR2(50) DEFAULT 'audio/wav' NOT NULL,
  TENANT_KEY      VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
) 
  TABLESPACE PROFREGTABSPACE; 

ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNCIATION_PK PRIMARY KEY (PROF_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."PRONOUNCEIDX" ON EMPINST."PRONUNCIATION" 
		("PROF_UPDATED" DESC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."WORKLOC"
------------------------------------------------

CREATE TABLE EMPINST."WORKLOC"  (
  "PROF_WORK_LOC" VARCHAR2(32) NOT NULL , 
  "PROF_ADDRESS1" VARCHAR2(256) , 
  "PROF_ADDRESS2" VARCHAR2(256) , 
  "PROF_CITY" VARCHAR2(128) , 
  "PROF_STATE" VARCHAR2(64) ,
  "PROF_POSTAL_CODE" VARCHAR2(16),
  "TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL	
) 
  TABLESPACE PROFREGTABSPACE; 

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_PK PRIMARY KEY (PROF_WORK_LOC, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."EMP_DRAFT"
------------------------------------------------

CREATE TABLE EMPINST.EMP_DRAFT  (
  PROF_UPDATE_SEQUENCE	NUMBER(19,0),
  PROF_KEY		VARCHAR2(36) NOT NULL,
  PROF_UID		VARCHAR2(256) NOT NULL ,
  PROF_LAST_UPDATE	TIMESTAMP NOT NULL,
  PROF_MAIL		VARCHAR2(256) ,
  PROF_SOURCE_UID	VARCHAR2(256),
  PROF_GUID		VARCHAR2(256) ,
  PROF_DISPLAY_NAME	VARCHAR2(256) ,
  PROF_LOGIN		VARCHAR2(256) ,
  PROF_GIVEN_NAME	VARCHAR2(128)  ,
  PROF_SURNAME		VARCHAR2(128) , 
  PROF_ALTERNATE_LAST_NAME	VARCHAR2(64) ,
  PROF_PREFERRED_FIRST_NAME	VARCHAR2(32) ,
  PROF_PREFERRED_LAST_NAME	VARCHAR2(64) ,
  PROF_TYPE		VARCHAR2(64),
  PROF_MANAGER_UID	VARCHAR2(256) ,
  PROF_SECRETARY_UID	VARCHAR2(256) ,
  PROF_IS_MANAGER	CHAR(1) ,
  PROF_GROUPWARE_EMAIL	VARCHAR2(128) ,
  PROF_JOB_RESPONSIBILITIES	VARCHAR2(128) ,
  PROF_ORGANIZATION_IDENTIFIER	VARCHAR2(64) ,
  PROF_ISO_COUNTRY_CODE	VARCHAR2(3) ,
  PROF_FAX_TELEPHONE_NUMBER	VARCHAR2(32) ,
  PROF_IP_TELEPHONE_NUMBER	VARCHAR2(32),
  PROF_MOBILE		VARCHAR2(32) ,
  PROF_PAGER		VARCHAR2(32) ,
  PROF_TELEPHONE_NUMBER	VARCHAR2(32) ,
  PROF_WORK_LOCATION	VARCHAR2(32) ,
  PROF_BUILDING_IDENTIFIER	VARCHAR2(16) ,
  PROF_DEPARTMENT_NUMBER	VARCHAR2(24) ,
  PROF_EMPLOYEE_TYPE	VARCHAR2(256) ,
  PROF_FLOOR		VARCHAR2(16) ,
  PROF_EMPLOYEE_NUMBER	VARCHAR2(16) ,
  PROF_PAGER_TYPE	VARCHAR2(16) ,
  PROF_PAGER_ID		VARCHAR2(32) ,
  PROF_PAGER_SERVICE_PROVIDER	VARCHAR2(50) ,
  PROF_PHYSICAL_DELIVERY_OFFICE	VARCHAR2(32) ,
  PROF_PREFERRED_LANGUAGE	VARCHAR2(100) ,
  PROF_SHIFT		VARCHAR2(4) ,
  PROF_TITLE		VARCHAR2(256) ,
  PROF_COURTESY_TITLE	VARCHAR2(64) ,
  PROF_TIMEZONE		VARCHAR2(64) , 
  PROF_NATIVE_LAST_NAME	VARCHAR2(256) ,
  PROF_NATIVE_FIRST_NAME	VARCHAR2(256) ,
  PROF_BLOG_URL		VARCHAR2(256) ,
  PROF_FREEBUSY_URL	VARCHAR2(256) ,
  PROF_CALENDAR_URL	VARCHAR2(256) ,
  PROF_DESCRIPTION	CLOB ,
  PROF_EXPERIENCE	CLOB ,
  TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
  TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMP_DRAFT_PK PRIMARY KEY (PROF_UPDATE_SEQUENCE, PROF_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."ED_MAIL" ON EMPINST."EMP_DRAFT" 
		("PROF_MAIL" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."ED_DISPNMX" ON EMPINST."EMP_DRAFT" 
		("PROF_DISPLAY_NAME" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST."ED_UPDATE_IDX" ON EMPINST."EMP_DRAFT" 
		("PROF_LAST_UPDATE" DESC, "PROF_KEY" DESC, "PROF_UPDATE_SEQUENCE" DESC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."CHG_EMP_DRAFT"
------------------------------------------------

CREATE TABLE EMPINST.CHG_EMP_DRAFT ( 
  IBMSNAP_COMMITSEQ NUMBER(19,0) NULL, 
  IBMSNAP_INTENTSEQ NUMBER(19,0) NOT NULL,
  IBMSNAP_OPERATION CHAR(1) NOT NULL,	 
  IBMSNAP_LOGMARKER DATE NOT NULL, 
  PROF_UPDATE_SEQUENCE NUMBER(19,0) NOT NULL,
  PROF_KEY VARCHAR2(36) NOT NULL,
  TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
  TABLESPACE PROFREGTABSPACE;

--------------------------------------
-- CREATE THE TRIGGERS
--------------------------------------
CREATE TRIGGER EMPINST."T_EXT_DRAFT_SEQ" BEFORE INSERT ON EMPINST."PROFILE_EXT_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW
		BEGIN
		 SELECT EMPINST.EXT_DRAFT_SEQ.NEXTVAL INTO :N.PROF_UPDATE_SEQUENCE FROM DUAL;
		END;
/

CREATE TRIGGER EMPINST."T_EMP_DRAFT_SEQ" BEFORE INSERT ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW 
		BEGIN
		 SELECT EMPINST.EMP_DRAFT_SEQ.NEXTVAL INTO :N.PROF_UPDATE_SEQUENCE FROM DUAL;
		END;
/

CREATE TRIGGER EMPINST."T_EMP_INS" AFTER INSERT ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW
		BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION,IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY, TENANT_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'I', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY, :N.TENANT_KEY);
		END;
/

CREATE TRIGGER EMPINST."T_EMP_DEL" AFTER DELETE ON EMPINST."EMP_DRAFT" REFERENCING OLD AS N 
	FOR EACH ROW 
		 BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION, IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY, TENANT_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'D', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY, :N.TENANT_KEY);
		END;
/

CREATE TRIGGER EMPINST."T_EMP_UPD" AFTER UPDATE ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW 
		 BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION, IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY, TENANT_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'U', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY, :N.TENANT_KEY);
		END;
/

------------------------------------------------
-- DDL Statements for table EMPINST.PROF_CONNECTIONS
------------------------------------------------

CREATE TABLE EMPINST.PROF_CONNECTIONS (
		PROF_CONNECTION_ID VARCHAR2(36) NOT NULL,
		PROF_SOURCE_KEY VARCHAR2(256) NOT NULL,
		PROF_TARGET_KEY VARCHAR2(256) NOT NULL,
		PROF_CREATED_BY_KEY VARCHAR2(256) NOT NULL,
		PROF_LASTMOD_BY_KEY VARCHAR2(256) NOT NULL,
		PROF_LASTMOD TIMESTAMP NOT NULL,
		PROF_CREATED TIMESTAMP NOT NULL,
		PROF_STATUS NUMBER(19,0) NOT NULL,
		PROF_MESSAGE VARCHAR2(2000),
		PROF_TYPE VARCHAR2(36) NOT NULL,
		TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)  
	TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECTIONS_PK PRIMARY KEY (PROF_CONNECTION_ID, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE UNIQUE INDEX EMPINST."CONN_UDX" ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY, PROF_TARGET_KEY, PROF_TYPE, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

-- Main index to select a users connections for showing friends in UI
CREATE INDEX EMPINST.CONN_INDEX1 ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_LASTMOD DESC, PROF_TARGET_KEY ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;
	
CREATE INDEX EMPINST.CONN_INDEX1B ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_LASTMOD ASC, PROF_TARGET_KEY ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

-- Friends in common; get list of connection keys 'isConnection' query
CREATE INDEX EMPINST.CONN_INDEX2 ON EMPINST.PROF_CONNECTIONS 
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_TARGET_KEY ASC, PROF_LASTMOD ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

-- Reverse index for deletes
CREATE INDEX EMPINST.CONN_REV_IDX ON EMPINST.PROF_CONNECTIONS 
	(PROF_TARGET_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_SOURCE_KEY ASC, PROF_LASTMOD ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."PROF_CONSTANTS"
------------------------------------------------

CREATE TABLE EMPINST.PROF_CONSTANTS (
    PROF_PROPERTY_KEY VARCHAR (64) NOT NULL,
    PROF_PROPERTY_VALUE VARCHAR (128) NOT NULL,
 	PRIMARY KEY (PROF_PROPERTY_KEY)
) ORGANIZATION INDEX TABLESPACE PROFREGTABSPACE;

INSERT INTO EMPINST.PROF_CONSTANTS VALUES ('USERID_PROPERTY', 'guid');
INSERT INTO EMPINST.PROF_CONSTANTS VALUES ('sys.usrPhotoThumbnail.task', 'complete');

------------------------------------------------
-- DDL Statements for view "EMPINST"."EVENTLOG"
------------------------------------------------

CREATE TABLE EMPINST.EVENTLOG (
	"EVENT_KEY"			VARCHAR2(36) NOT NULL, 
	"EVENT_SOURCE"		VARCHAR2(36) NOT NULL, 
	"OBJECT_KEY"		VARCHAR2(36) NOT NULL,
	"EVENT_NAME"		VARCHAR2(128) NOT NULL, 
	"EVENT_TYPE"		NUMBER(19,0) DEFAULT -1 NOT NULL, 
	"CREATED"			TIMESTAMP NOT NULL,
	"CREATED_BY_KEY"	VARCHAR2(36) NOT NULL,
	"CREATED_BY_GUID"	VARCHAR2(256) NOT NULL, 
	"CREATED_BY_UID"	VARCHAR2(256) NOT NULL, 
	"CREATED_BY_NAME"	VARCHAR2(128),
	"ISPRIVATE"			NUMBER(19,0) DEFAULT 0,
	"ISSYSEVENT"		NUMBER(19,0) DEFAULT 0,
	"EVENT_METADATA"	CLOB,
	"TENANT_KEY"		VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
	TABLESPACE PROFREGTABSPACE ;

ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVENTLOG_PK PRIMARY KEY (EVENT_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."EVLOG_TYPE_IDX" ON EMPINST.EVENTLOG
	("EVENT_TYPE" ASC, "CREATED" ASC,  "EVENT_KEY" ASC, TENANT_KEY)	TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."EVLOG_AUDIT_IDX" ON EMPINST.EVENTLOG
	("ISSYSEVENT" ASC, "EVENT_KEY" ASC, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."PROFILE_LOGIN"
------------------------------------------------

CREATE TABLE EMPINST.PROFILE_LOGIN  (
	PROF_KEY		VARCHAR2(36) NOT NULL, 
	PROF_LOGIN		VARCHAR2(256) NOT NULL,
	TENANT_KEY		VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
	TABLESPACE PROFREGTABSPACE ;

ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT PROFILE_LOGIN_PK PRIMARY KEY (PROF_KEY, PROF_LOGIN, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE UNIQUE INDEX EMPINST.LOGIN_UDX ON EMPINST.PROFILE_LOGIN
		(PROF_LOGIN,TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table EMPINST.PROFILE_PREFS
------------------------------------------------

CREATE TABLE EMPINST.PROFILE_PREFS (
	PROF_KEY 	VARCHAR2(36) NOT NULL, 
	PROF_PREFID 	VARCHAR2(128) NOT NULL, 
	PROF_VALUE	VARCHAR2(1024),
	TENANT_KEY	VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
	TABLESPACE PROFREGTABSPACE ;

ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFILE_PREFS_PK PRIMARY KEY (PROF_KEY, PROF_PREFID, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for user to role mappings
------------------------------------------------

CREATE TABLE EMPINST.EMP_ROLE_MAP (
	MAP_KEY        VARCHAR2(36)  NOT NULL,
	PROF_KEY       VARCHAR2(36)  NOT NULL,
	ROLE_ID        VARCHAR2(128) NOT NULL,
	CREATED        TIMESTAMP     NOT NULL,
	TENANT_KEY     VARCHAR2(36)  DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
	TABLESPACE PROFREGTABSPACE ;

ALTER TABLE EMPINST.EMP_ROLE_MAP ADD CONSTRAINT EMP_ROLEMAP_PK PRIMARY KEY (MAP_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE UNIQUE INDEX EMPINST.EMP_ROLE_UDX ON EMPINST.EMP_ROLE_MAP (PROF_KEY, ROLE_ID, TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for view "EMPINST"."PROFILE_LAST_LOGIN"
------------------------------------------------

CREATE TABLE EMPINST.PROFILE_LAST_LOGIN (
	PROF_KEY 		VARCHAR2(36) NOT NULL, 
	PROF_LAST_LOGIN 	TIMESTAMP NOT NULL, 
	PROF_LOCALE 		VARCHAR2(32),
	TENANT_KEY		VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
	TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_PK PRIMARY KEY (PROF_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for view "EMPINST"."EMP_UPDATE_TIMESTAMP"
------------------------------------------------

CREATE TABLE EMPINST.EMP_UPDATE_TIMESTAMP (
	PROF_KEY						VARCHAR(36) NOT NULL, 
	TENANT_KEY						VARCHAR(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL,
	LDAP_MOD_TIMESTAMP_SOURCE	 	VARCHAR(36) NOT NULL,
	LDAP_MOD_TIMESTAMP	 			VARCHAR(128) DEFAULT '0' NOT NULL,
	MARK 							VARCHAR(1) DEFAULT '0' NOT NULL
)
	TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.EMP_UPDATE_TIMESTAMP ADD CONSTRAINT TS_PK PRIMARY KEY (PROF_KEY, TENANT_KEY, LDAP_MOD_TIMESTAMP_SOURCE) USING INDEX TABLESPACE PROFINDEXTABSPACE;

------------------------------------------------
-- DDL Statements for table "EMPINST"."USER_PLATFORM_EVENTS"
------------------------------------------------

CREATE TABLE "EMPINST"."USER_PLATFORM_EVENTS"  (
	"EVENT_KEY" NUMBER(19, 0) NOT NULL, 
	"EVENT_TYPE" VARCHAR2(36) NOT NULL,
	"PAYLOAD" CLOB,
	"CREATED" TIMESTAMP NOT NULL,
	"TENANT_KEY" VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL
)
	TABLESPACE PROFREGTABSPACE;

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT PLATFORM_EVENTS_PK PRIMARY KEY (EVENT_KEY, TENANT_KEY) USING INDEX TABLESPACE PROFINDEXTABSPACE;

CREATE SEQUENCE "EMPINST"."USER_PLATFORM_EVENT_INDEX_SEQ"
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	NOCYCLE
	MINVALUE 0
	CACHE 20;

-------------------------------------------------------------------
-- START ADDING SCHEDULER TABLES
-------------------------------------------------------------------

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TASK" (
	TASKID NUMBER(19, 0) NOT NULL,
	VERSION VARCHAR2(5) NOT NULL,
	ROW_VERSION NUMBER(10, 0) NOT NULL,
	TASKTYPE NUMBER(10, 0) NOT NULL,
	TASKSUSPENDED NUMBER(5, 0) NOT NULL,
	CANCELLED NUMBER(5, 0) NOT NULL,
	NEXTFIRETIME NUMBER(19, 0) NOT NULL,
	STARTBYINTERVAL VARCHAR2(254),
	STARTBYTIME NUMBER(19, 0),
	VALIDFROMTIME NUMBER(19, 0),
	VALIDTOTIME NUMBER(19, 0),
	REPEATINTERVAL VARCHAR2(254),
	MAXREPEATS NUMBER(10, 0) NOT NULL,
	REPEATSLEFT NUMBER(10, 0) NOT NULL,
	TASKINFO BLOB,
	NAME VARCHAR2(254) NOT NULL,
	AUTOPURGE NUMBER(10, 0) NOT NULL,
	FAILUREACTION NUMBER(10, 0),
	MAXATTEMPTS NUMBER(10, 0),
	QOS NUMBER(10, 0),
	PARTITIONID NUMBER(10, 0),
	OWNERTOKEN VARCHAR2(200) NOT NULL,
	CREATETIME NUMBER(19, 0) NOT NULL,
	PRIMARY KEY (TASKID)
) 
TABLESPACE PROFREGTABSPACE;

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX1 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" ("TASKID", "OWNERTOKEN") TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX2 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" ("NEXTFIRETIME" ASC, "REPEATSLEFT", "PARTITIONID") TABLESPACE PROFINDEXTABSPACE;

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TREG" (
	REGKEY VARCHAR2(254) NOT NULL,
	REGVALUE VARCHAR2(254),
	PRIMARY KEY (REGKEY)
) 
TABLESPACE PROFREGTABSPACE;

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMGR" (
	LEASENAME VARCHAR2(254) NOT NULL,
	LEASEOWNER VARCHAR2(254) NOT NULL,
	LEASE_EXPIRE_TIME  NUMBER(19, 0),
	DISABLED VARCHAR2(5),
	PRIMARY KEY (LEASENAME)
)
TABLESPACE PROFREGTABSPACE;


CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMPR" (
	LEASENAME VARCHAR2(254) NOT NULL,
	NAME VARCHAR2(254) NOT NULL,
	VALUE VARCHAR2(254) NOT NULL
)
TABLESPACE PROFREGTABSPACE;

CREATE INDEX "EMPINST"."PROFILES_SCHEDULER_LMPR_IDX1"
	ON "EMPINST"."PROFILES_SCHEDULER_LMPR" ("LEASENAME", "NAME") TABLESPACE PROFINDEXTABSPACE;
	
-------------------------------------------------------------------
-- END ADDING SCHEDULER TABLES
-------------------------------------------------------------------

COMMIT;
QUIT;
