-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2010                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
DROP TABLE EMPINST.USER_STATE_LAIDX;

{include.dynaDefsFixUp05.sql}

-- fix some indexes
DROP INDEX "EMPINST"."INDEX CONN_INDEX1";
DROP INDEX "EMPINST"."INDEX CONN_INDEX2";
DROP INDEX "EMPINST"."CONN_TARGET_IDX";

-- Main index to select a users connections for showing friends in UI
CREATE INDEX EMPINST.CONN_INDEX1 ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_LASTMOD DESC, PROF_TARGET_KEY ASC) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.CONN_INDEX1B ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_LASTMOD ASC, PROF_TARGET_KEY ASC) TABLESPACE PROFINDEXTABSPACE;

-- Friends in common; get list of connection keys
-- 'isConnection' query
CREATE INDEX EMPINST.CONN_INDEX2 ON EMPINST.PROF_CONNECTIONS 
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_TARGET_KEY ASC, PROF_LASTMOD ASC) TABLESPACE PROFINDEXTABSPACE;

-- Reverse index for deletes
CREATE INDEX EMPINST.CONN_REV_IDX ON EMPINST.PROF_CONNECTIONS 
	(PROF_TARGET_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_SOURCE_KEY ASC, PROF_LASTMOD ASC) TABLESPACE PROFINDEXTABSPACE;

	
------------------------------------------------
-- DDL Statements for view "EMPINST"."EMPLOYEE"
------------------------------------------------

ALTER TABLE "EMPINST"."EMPLOYEE" MODIFY "PROF_TIMEZONE" VARCHAR2(64);

--
-- User state look aside index table
--
CREATE TABLE EMPINST.USER_STATE_LAIDX (
	IDXID    RAW(16) NOT NULL,
	DEFID    RAW(16) NOT NULL,
	ATTRID	 RAW(16) NOT NULL,
	USRSTATE INTEGER NOT NULL,
	USRSTATE_UPDATED TIMESTAMP NOT NULL,
	OBJID    RAW(16) NOT NULL,
	OBJIDSTR   CHAR(36) NOT NULL,
	CONSTRAINT USRSTATE_PK PRIMARY KEY (IDXID)
) TABLESPACE PROFREGTABSPACE;

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_DEF_FK FOREIGN KEY (DEFID) 
	REFERENCES EMPINST.DYNA_DEFS(DEFID)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

--
-- Foriegn key constraint to reference field which contains value
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_ATTR_FK FOREIGN KEY (ATTRID) 
	REFERENCES EMPINST.DYNA_ATTRS(ATTRID)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

--
-- Enforce single attr/idx-val
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_ATTR_UK UNIQUE (ATTRID);

--
-- Constrain to one value per user
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT OBJID_UNIQUE UNIQUE (OBJID);
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT OBJIDSTR_UNIQUE UNIQUE (OBJIDSTR);

CREATE INDEX USRSTATE_CONS_VALB 
	ON EMPINST.USER_STATE_LAIDX (OBJID ASC, OBJIDSTR ASC, USRSTATE ASC, USRSTATE_UPDATED ASC)
	 TABLESPACE PROFINDEXTABSPACE;
	
CREATE INDEX EMPINST.USRSTATE_CONS_VALS 
	ON EMPINST.USER_STATE_LAIDX (OBJIDSTR ASC, OBJID ASC, USRSTATE ASC, USRSTATE_UPDATED ASC)
	TABLESPACE PROFINDEXTABSPACE; 

--
-- Main index for scanning
--
CREATE INDEX EMPINST.USRSTATE_IDX
	ON EMPINST.USER_STATE_LAIDX (USRSTATE ASC, USRSTATE_UPDATED ASC, OBJID ASC, OBJIDSTR ASC)
	TABLESPACE PROFINDEXTABSPACE;


--
-- User state look aside index table
--
CREATE TABLE EMPINST.USER_ORGS_LAIDX (
	IDXID    RAW(16) NOT NULL,
	DEFID    RAW(16) NOT NULL,
	ATTRID	 RAW(16) NOT NULL,
	ORGID	 VARCHAR2(128) NOT NULL,
	OBJID    RAW(16) NOT NULL,
	OBJIDSTR CHAR(36) NOT NULL,
	CONSTRAINT USRORGS_PK PRIMARY KEY (IDXID)
) TABLESPACE PROFREGTABSPACE;

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_DEF_FK FOREIGN KEY (DEFID) 
	REFERENCES EMPINST.DYNA_DEFS(DEFID)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

--
-- Foriegn key constraint to reference field which contains value
--
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_ATTR_FK FOREIGN KEY (ATTRID) 
	REFERENCES EMPINST.DYNA_ATTRS(ATTRID)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

--
--
--
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRSTE_ATTR_UK UNIQUE (ATTRID);

--
-- Main index for scanning
--
CREATE INDEX EMPINST.USRORGS_IDX
	ON EMPINST.USER_ORGS_LAIDX (DEFID ASC, ORGID ASC, OBJIDSTR ASC, OBJID ASC);


ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_C_OBJID UNIQUE (DEFID, OBJID, ORGID);
ALTER TABLE EMPINST.USER_ORGS_LAIDX ADD CONSTRAINT USRORGS_C_OBJIDS UNIQUE (DEFID, OBJIDSTR, ORGID);

CREATE INDEX EMPINST.USRORGS_MEM_BIDX
	ON EMPINST.USER_ORGS_LAIDX (OBJID ASC, DEFID ASC, ORGID ASC, OBJIDSTR ASC)
	TABLESPACE PROFINDEXTABSPACE;
	
CREATE UNIQUE INDEX EMPINST.USRORGS_MEM_SIDX
	ON EMPINST.USER_ORGS_LAIDX (OBJIDSTR ASC, DEFID ASC, ORGID ASC, OBJID ASC)
	TABLESPACE PROFINDEXTABSPACE;

-- Fix given_name
ALTER TABLE EMPINST.GIVEN_NAME ADD PROF_USRSTATE NUMBER(19,0) DEFAULT 0 NOT NULL;

DROP INDEX EMPINST.GIVEN_NAMEX;	
DROP INDEX EMPINST.GIVENNAME_IDX; 

CREATE INDEX EMPINST.GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME (PROF_GIVENNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST.GIVEN_NAME_IDX2 ON EMPINST.GIVEN_NAME (PROF_USRSTATE ASC, PROF_GIVENNAME ASC, PROF_KEY ASC) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST.GIVEN_NAMEX ON EMPINST.GIVEN_NAME (PROF_KEY ASC, PROF_GIVENNAME ASC, PROF_USRSTATE ASC) TABLESPACE PROFINDEXTABSPACE;

-- Fix surname
ALTER TABLE EMPINST.SURNAME ADD PROF_USRSTATE NUMBER(19,0) DEFAULT 0 NOT NULL;

DROP INDEX EMPINST.SURNAMEX;
DROP INDEX EMPINST.SURNAME_IDX;

CREATE INDEX EMPINST.SURNAME_IDX ON EMPINST.SURNAME (PROF_SURNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST.SURNAME_IDX2 ON EMPINST.SURNAME (PROF_USRSTATE ASC, PROF_SURNAME ASC, PROF_KEY ASC) TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX EMPINST.SURNAMEX ON EMPINST.SURNAME (PROF_KEY ASC, PROF_SURNAME ASC, PROF_USRSTATE ASC) TABLESPACE PROFINDEXTABSPACE;
	
-- Update schema versions
UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 28 WHERE COMPKEY='Profiles';

COMMIT;
QUIT;
