-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- add column: see sn.homepage\lwp\dboard.sn.install\scripts\db\<dbtype>\fixup\fixup12.sql

------
-- TENANT: create table, add constraitns, indexes
------

CREATE TABLE "EMPINST"."TENANT"  (						-- new
	"TENANT_KEY"		VARCHAR2(36)	NOT NULL,		-- new
	"TENANT_EXID"		VARCHAR2(256)	NOT NULL,		-- new
	"TENANT_NAME"		VARCHAR2(256)	NOT NULL,		-- new
	"TENANT_NAME_LOWER"	VARCHAR2(256)	NOT NULL,		-- new
	"TENANT_STATE"		NUMBER(19,0)	NOT NULL,		-- new
	"TENANT_CREATED"	TIMESTAMP NOT NULL,				-- new
	--"TENANT_CREATED_BY_KEY" VARCHAR2(36) NOT NULL,		-- new
	"TENANT_LASTUPDATE"	TIMESTAMP	NOT NULL,			-- new
	--"TENANT_LASTMOD_BY_KEY" VARCHAR2(36) NOT NULL,		-- new
	CONSTRAINT "TENANT_PK" PRIMARY KEY ("TENANT_KEY")	-- new
)
	TABLESPACE PROFREGTABSPACE;


CREATE UNIQUE INDEX EMPINST.TENANT_EXID_UDX ON EMPINST.TENANT
		(TENANT_EXID ASC) TABLESPACE PROFINDEXTABSPACE;

INSERT INTO EMPINST.TENANT(
	TENANT_KEY           ,
	TENANT_EXID          ,
	TENANT_NAME          ,
	TENANT_NAME_LOWER    ,
	TENANT_STATE         ,
	TENANT_CREATED       ,
	--TENANT_CREATED_BY_KEY,
	TENANT_LASTUPDATE
	--TENANT_LASTMOD_BY_KEY
)
VALUES(
	'00000000-0000-0000-0000-040508202233',
	'standard_tenant_guid',
	'Default Tenant',
	'default tenant',
	0,
	SYSDATE,
	-- no admin,
	SYSDATE
	-- no admin
);

------
-- EMPLOYEE: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.EMPLOYEE
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPPROF_TENT_UK  UNIQUE (PROF_KEY, TENANT_KEY);

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- GIVEN_NAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.GIVEN_NAME
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GVNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- SURNAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.SURNAME
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- DEPARTMENT: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.DEPARTMENT
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.DEPARTMENT DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT PDEPARTMENT_PK PRIMARY KEY (TENANT_KEY, PROF_DEPARTMENT_CODE);

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPT_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- ORGANIZATION: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.ORGANIZATION
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.ORGANIZATION DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_PK PRIMARY KEY (TENANT_KEY, PROF_ORGANIZATION_CODE);

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- COUNTRY: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.COUNTRY
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.COUNTRY DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (TENANT_KEY, PROF_ISO_COUNTRY_CODE);

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT CNTRY_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- EMP_TYPE: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EMP_TYPE
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.EMP_TYPE DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_PK PRIMARY KEY (TENANT_KEY, PROF_EMPLOYEE_TYPE);

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- WORKLOC: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.WORKLOC
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.WORKLOC DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_PK PRIMARY KEY (TENANT_KEY, PROF_WORK_LOC);

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- EVENTLOG: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EVENTLOG
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVLOG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PROFILE_LOGIN: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_LOGIN
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT LOGIN_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

DROP INDEX EMPINST.LOGIN_UDX;

CREATE UNIQUE INDEX EMPINST.LOGIN_UDX ON EMPINST.PROFILE_LOGIN
		(PROF_LOGIN,TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------
-- USER_PLATFORM_EVENTS: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT UPLTEV_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- Update schema versions
------

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 31, RELEASEVER='4.0.0.0' WHERE COMPKEY='Profiles';


COMMIT;

------
-- Disconnect
------

QUIT;
