-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2012                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
-- CREATE THE TRIGGERS
--------------------------------------
CREATE TRIGGER EMPINST."T_EXT_DRAFT_SEQ" BEFORE INSERT ON EMPINST."PROFILE_EXT_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW
		BEGIN
		 SELECT EMPINST.EXT_DRAFT_SEQ.NEXTVAL INTO :N.PROF_UPDATE_SEQUENCE FROM DUAL;
		END;
/


CREATE TRIGGER EMPINST."T_EMP_DRAFT_SEQ" BEFORE INSERT ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW 
		BEGIN
		 SELECT EMPINST.EMP_DRAFT_SEQ.NEXTVAL INTO :N.PROF_UPDATE_SEQUENCE FROM DUAL;
		END;
/


CREATE TRIGGER EMPINST."T_EMP_INS" AFTER INSERT ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW
		BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION,
                                                 IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'I', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY);
		END;
/
		 

CREATE TRIGGER EMPINST."T_EMP_DEL" AFTER DELETE ON EMPINST."EMP_DRAFT" REFERENCING OLD AS N 
	FOR EACH ROW 
		 BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION,
                                                 IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'D', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY);
		END;
/

CREATE TRIGGER EMPINST."T_EMP_UPD" AFTER UPDATE ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW 
		 BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION,
                                                 IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'U', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY);
		END;
/

--
--- Foreign keys for tenant
--
ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GVNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROFEXT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT PREXTDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PEOPLE_TAG ADD CONSTRAINT PPLTAG_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPT_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT CNTRY_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNC_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMPDRAFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.CHG_EMP_DRAFT ADD CONSTRAINT CHEMPDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVLOG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT LOGIN_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFPREF_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT UPLTEV_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

COMMIT;
{include.msgVector-postdbxfer301.sql}

{include.dynattr-postdbxfer30.sql}

COMMIT;
QUIT;
