-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2010                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
ALTER TABLE "EMPINST"."EMPLOYEE" MODIFY "PROF_LOGIN" VARCHAR2(256);
ALTER TABLE "EMPINST"."EMPLOYEE" MODIFY "PROF_LOGIN_LOWER" VARCHAR2(256);

ALTER TABLE "EMPINST"."EMPLOYEE" ADD "TEMP_DESC" VARCHAR2(4000);
UPDATE "EMPINST"."EMPLOYEE" SET "TEMP_DESC"="PROF_DESCRIPTION";
ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "PROF_DESCRIPTION";

ALTER TABLE "EMPINST"."EMPLOYEE" ADD "TEMP_EXP" VARCHAR2(4000);
UPDATE "EMPINST"."EMPLOYEE" SET "TEMP_EXP"="PROF_EXPERIENCE";
ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "PROF_EXPERIENCE";

ALTER TABLE "EMPINST"."EMPLOYEE" ADD "PROF_DESCRIPTION" CLOB;
UPDATE "EMPINST"."EMPLOYEE" SET "PROF_DESCRIPTION"="TEMP_DESC";
ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "TEMP_DESC";

ALTER TABLE "EMPINST"."EMPLOYEE" ADD "PROF_EXPERIENCE" CLOB;
UPDATE "EMPINST"."EMPLOYEE" SET "PROF_EXPERIENCE"="TEMP_EXP";
ALTER TABLE "EMPINST"."EMPLOYEE" DROP COLUMN "TEMP_EXP";

CREATE INDEX EMPINST."SRC_UID_IDX" ON EMPINST."EMPLOYEE" 
		("PROF_SOURCE_UID" ASC) TABLESPACE PROFINDEXTABSPACE;

DROP TRIGGER EMPINST."T_EMPLOYEE_MAIL_UPDT";


CREATE TRIGGER EMPINST."T_EMPLOYEE_MAIL_UPDT" BEFORE UPDATE OF PROF_MAIL ON EMPINST."EMPLOYEE" REFERENCING NEW AS N 
	FOR EACH ROW
		BEGIN
		 SELECT LOWER(:N.PROF_MAIL) INTO :N.PROF_MAIL_LOWER FROM DUAL;
		END;
/

ALTER TABLE "EMPINST"."EMP_DRAFT" MODIFY "PROF_LOGIN" VARCHAR2(256);
   
ALTER TABLE "EMPINST"."EMP_DRAFT" ADD "TEMP_DESC" VARCHAR2(4000);
UPDATE "EMPINST"."EMP_DRAFT" SET "TEMP_DESC"="PROF_DESCRIPTION";
ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "PROF_DESCRIPTION";

ALTER TABLE "EMPINST"."EMP_DRAFT" ADD "TEMP_EXP" VARCHAR2(4000);
UPDATE "EMPINST"."EMP_DRAFT" SET "TEMP_EXP"="PROF_EXPERIENCE";
ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "PROF_EXPERIENCE";



ALTER TABLE "EMPINST"."EMP_DRAFT" ADD "PROF_DESCRIPTION" CLOB;
UPDATE "EMPINST"."EMP_DRAFT" SET "PROF_DESCRIPTION"="TEMP_DESC";
ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "TEMP_DESC";

ALTER TABLE "EMPINST"."EMP_DRAFT" ADD "PROF_EXPERIENCE" CLOB;
UPDATE "EMPINST"."EMP_DRAFT" SET "PROF_EXPERIENCE"="TEMP_EXP";
ALTER TABLE "EMPINST"."EMP_DRAFT" DROP COLUMN "TEMP_EXP";

                   
DROP INDEX "EMPINST"."CONN_UDX" ;
DROP INDEX "EMPINST"."INDEX CONN_INDEX1";
DROP INDEX "EMPINST"."INDEX CONN_INDEX2"; 


ALTER TABLE "EMPINST"."PROF_CONNECTIONS" DROP COLUMN "PROF_VISIBILITY";
ALTER TABLE "EMPINST"."PROF_CONNECTIONS" DROP COLUMN "PROF_TYPE";

ALTER TABLE "EMPINST"."PROF_CONNECTIONS" ADD "PROF_TYPE" VARCHAR2(36);
UPDATE "EMPINST"."PROF_CONNECTIONS" SET "PROF_TYPE"="PROF_VALUE";

ALTER TABLE "EMPINST"."PROF_CONNECTIONS" DROP COLUMN "PROF_VALUE";

CREATE INDEX EMPINST."CONN_INDEX1" ON EMPINST.PROF_CONNECTIONS(PROF_STATUS, PROF_TYPE, PROF_SOURCE_KEY) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST."CONN_INDEX2" ON EMPINST.PROF_CONNECTIONS(PROF_STATUS, PROF_TYPE, PROF_SOURCE_KEY, PROF_LASTMOD) TABLESPACE PROFINDEXTABSPACE;                             

CREATE UNIQUE INDEX EMPINST."CONN_UDX" ON EMPINST.PROF_CONNECTIONS(PROF_SOURCE_KEY, PROF_TARGET_KEY, PROF_TYPE) TABLESPACE PROFINDEXTABSPACE;


CREATE INDEX "EMPINST"."PEOPLE_TAG_IDX3" ON "EMPINST"."PEOPLE_TAG" ("PROF_TARGET_KEY", "PROF_TAG_ID") TABLESPACE "PROFINDEXTABSPACE";


------------------------------------------------
-- update schema to current version
------------------------------------------------

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 5 WHERE COMPKEY='Profiles';

COMMIT;
QUIT;
