-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2012, 2013                             
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68
 
------
-- EMPLOYEE
------
CREATE INDEX EMPINST.PROF_SRC_UID_IDX ON EMPINST.EMPLOYEE (PROF_SOURCE_UID ASC) TABLESPACE PROFINDEXTABSPACE;

------
-- PROFILE_EXTENSIONS: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PROFILE_EXTENSIONS
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROFEXT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PROFILE_EXT_DRAFT: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PROFILE_EXT_DRAFT
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT PREXTDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PEOPLE_TAG: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PEOPLE_TAG
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PEOPLE_TAG ADD CONSTRAINT PPLTAG_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PHOTO: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PHOTO
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_TENT_UK UNIQUE (PROF_KEY, TENANT_KEY);

ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PRONUNCIATION: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PRONUNCIATION
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNC_TENT_UK UNIQUE (PROF_KEY, TENANT_KEY);

ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNC_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- EMP_DRAFT: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.EMP_DRAFT
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMPDRAFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- CHG_EMP_DRAFT: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.CHG_EMP_DRAFT
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.CHG_EMP_DRAFT ADD CONSTRAINT CHEMPDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

DROP TRIGGER EMPINST.T_EMP_INS;
DROP TRIGGER EMPINST.T_EMP_DEL;
DROP TRIGGER EMPINST.T_EMP_UPD;

CREATE TRIGGER EMPINST."T_EMP_INS" AFTER INSERT ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW
		BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION,
		 				IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY, TENANT_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'I', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY, :N.TENANT_KEY);
		END;
/

CREATE TRIGGER EMPINST."T_EMP_DEL" AFTER DELETE ON EMPINST."EMP_DRAFT" REFERENCING OLD AS N 
	FOR EACH ROW 
		 BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION,
		 				IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY, TENANT_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'D', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY, :N.TENANT_KEY);
		END;
/

CREATE TRIGGER EMPINST."T_EMP_UPD" AFTER UPDATE ON EMPINST."EMP_DRAFT" REFERENCING NEW AS N 
	FOR EACH ROW 
		 BEGIN 
		 INSERT INTO EMPINST."CHG_EMP_DRAFT" (IBMSNAP_COMMITSEQ, IBMSNAP_INTENTSEQ, IBMSNAP_OPERATION,
                                                 IBMSNAP_LOGMARKER, PROF_UPDATE_SEQUENCE, PROF_KEY, TENANT_KEY)
 		 VALUES (LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ1.NEXTVAL),20,'0'), LPAD(TO_CHAR(EMPINST.CHG_EMP_DRAFT_SEQ2.NEXTVAL),20,'0'), 'U', SYSDATE, :N.PROF_UPDATE_SEQUENCE, :N.PROF_KEY, :N.TENANT_KEY);
		END;
/

------
-- PROF_CONNECTIONS: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PROF_CONNECTIONS
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PROFILE_PREFS: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PROFILE_PREFS
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFPREF_TENT_UK UNIQUE (PROF_KEY, TENANT_KEY);

ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFPREF_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PROFILE_LAST_LOGIN: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_TENT_UK UNIQUE (PROF_KEY, TENANT_KEY);

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- Update schema version
------
UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 36, RELEASEVER='4.5.0.0' WHERE COMPKEY='Profiles';

COMMIT;
------
-- Disconnect
------

QUIT;