-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2010                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
-- DDL Statements for view "EMPINST"."EMPLOYEE"
------------------------------------------------


CREATE INDEX "EMPINST"."DISP_IDX" ON "EMPINST"."EMPLOYEE" 
	("PROF_KEY" ASC, "PROF_DISPLAY_NAME" ASC)
	TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_SNGN_IDX" ON "EMPINST"."EMPLOYEE" 
	("PROF_KEY" ASC, "PROF_SURNAME" ASC, "PROF_GIVEN_NAME" ASC)
	TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_GN2_IDX" ON "EMPINST"."EMPLOYEE" 
	("PROF_GIVEN_NAME" ASC, "PROF_KEY" ASC)
	TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST"."PROF_SN2_IDX" ON "EMPINST"."EMPLOYEE" 
	("PROF_SURNAME" ASC, "PROF_KEY" ASC)
	TABLESPACE PROFINDEXTABSPACE;

ALTER TABLE "EMPINST"."EMPLOYEE" MODIFY "PROF_DEPARTMENT_NUMBER" VARCHAR2(24);

------------------------------------------------
-- DDL Statements for table "EMPINST"."DEPARTMENT"
------------------------------------------------

ALTER TABLE "EMPINST"."DEPARTMENT" MODIFY "PROF_DEPARTMENT_CODE" VARCHAR2(24);


------------------------------------------------
-- DDL Statements for view "EMPINST"."PRONUNCIATION"
------------------------------------------------

ALTER TABLE "EMPINST"."PRONUNCIATION" ADD "PROF_FILE_TYPE" VARCHAR (50) DEFAULT 'audio/wav' NOT NULL ;

------------------------------------------------
-- DDL Statements for table "EMPINST"."USER_PLATFORM_EVENTS"
------------------------------------------------

CREATE TABLE "EMPINST"."USER_PLATFORM_EVENTS"  (
	"EVENT_KEY" NUMBER(19, 0) NOT NULL, 
	"EVENT_TYPE" VARCHAR2(36) NOT NULL,
	"PAYLOAD" CLOB,
	"CREATED" TIMESTAMP NOT NULL,
	PRIMARY KEY ("EVENT_KEY") 
) TABLESPACE PROFREGTABSPACE;

CREATE SEQUENCE "EMPINST"."USER_PLATFORM_EVENT_INDEX_SEQ"
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	CACHE 20;

-------------------------------------------------------------------
-- START ADDING SCHEDULER TABLES
-------------------------------------------------------------------

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TASK" (
	TASKID NUMBER(19, 0) NOT NULL,
	VERSION VARCHAR2(5) NOT NULL,
	ROW_VERSION NUMBER(10, 0) NOT NULL,
	TASKTYPE NUMBER(10, 0) NOT NULL,
	TASKSUSPENDED NUMBER(5, 0) NOT NULL,
	CANCELLED NUMBER(5, 0) NOT NULL,
	NEXTFIRETIME NUMBER(19, 0) NOT NULL,
	STARTBYINTERVAL VARCHAR2(254),
	STARTBYTIME NUMBER(19, 0),
	VALIDFROMTIME NUMBER(19, 0),
	VALIDTOTIME NUMBER(19, 0),
	REPEATINTERVAL VARCHAR2(254),
	MAXREPEATS NUMBER(10, 0) NOT NULL,
	REPEATSLEFT NUMBER(10, 0) NOT NULL,
	TASKINFO BLOB,
	NAME VARCHAR2(254) NOT NULL,
	AUTOPURGE NUMBER(10, 0) NOT NULL,
	FAILUREACTION NUMBER(10, 0),
	MAXATTEMPTS NUMBER(10, 0),
	QOS NUMBER(10, 0),
	PARTITIONID NUMBER(10, 0),
	OWNERTOKEN VARCHAR2(200) NOT NULL,
	CREATETIME NUMBER(19, 0) NOT NULL,
	PRIMARY KEY (TASKID)
) 
TABLESPACE PROFREGTABSPACE;

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX1 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" ("TASKID", "OWNERTOKEN") TABLESPACE PROFINDEXTABSPACE;

CREATE INDEX "EMPINST".PROFILES_SCHEDULER_TASK_IDX2 
	ON "EMPINST"."PROFILES_SCHEDULER_TASK" ("NEXTFIRETIME" ASC, "REPEATSLEFT", "PARTITIONID") TABLESPACE PROFINDEXTABSPACE;

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_TREG" (
	REGKEY VARCHAR2(254) NOT NULL,
	REGVALUE VARCHAR2(254),
	PRIMARY KEY (REGKEY)
) 
TABLESPACE PROFREGTABSPACE;

CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMGR" (
	LEASENAME VARCHAR2(254) NOT NULL,
	LEASEOWNER VARCHAR2(254) NOT NULL,
	LEASE_EXPIRE_TIME  NUMBER(19, 0),
	DISABLED VARCHAR2(5),
	PRIMARY KEY (LEASENAME)
)
TABLESPACE PROFREGTABSPACE;


CREATE TABLE "EMPINST"."PROFILES_SCHEDULER_LMPR" (
	LEASENAME VARCHAR2(254) NOT NULL,
	NAME VARCHAR2(254) NOT NULL,
	VALUE VARCHAR2(254) NOT NULL
)
TABLESPACE PROFREGTABSPACE;

CREATE INDEX "EMPINST"."PROFILES_SCHEDULER_LMPR_IDX1"
	ON "EMPINST"."PROFILES_SCHEDULER_LMPR" ("LEASENAME", "NAME") TABLESPACE PROFINDEXTABSPACE;
	
-------------------------------------------------------------------
-- END ADDING SCHEDULER TABLES
-------------------------------------------------------------------

------------------------------------------------
-- Stuff to create external index dynattr
------------------------------------------------

{include.createDynaDefs.sql}

--
-- User state look aside index table
--
CREATE TABLE EMPINST.USER_STATE_LAIDX (
    DEFID    RAW(16) NOT NULL,
	IDXID		RAW(16) NOT NULL,
	USRSTATE		NUMBER(19,0) NOT NULL,
	USRSTATE_UPDATED	TIMESTAMP NOT NULL,
	OBJID			RAW(16) NOT NULL,
	OBJIDSTR		CHAR(36) NOT NULL,
	CONSTRAINT USER_STATE_PK PRIMARY KEY (IDXID)
) TABLESPACE PROFREGTABSPACE;

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_DEF_FK FOREIGN KEY (DEFID) 
 REFERENCES EMPINST.DYNA_DEFS(DEFID)
 ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

--
-- Foriegn key constraint on obj-ref table to clean up on deletion
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT USRSTATE_OBJ_FK FOREIGN KEY (OBJID) 
	REFERENCES EMPINST.DYNA_OBJ_REF(OBJID)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

--
-- Constrain to one value per user
--
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT OBJID_UNIQUE UNIQUE (OBJID);
ALTER TABLE EMPINST.USER_STATE_LAIDX ADD CONSTRAINT OBJIDSTR_UNIQUE UNIQUE (OBJIDSTR);

CREATE INDEX USRSTATE_CONS_VALB 
	ON EMPINST.USER_STATE_LAIDX 
	(OBJID ASC, OBJIDSTR ASC, USRSTATE ASC, USRSTATE_UPDATED ASC)
	 TABLESPACE PROFINDEXTABSPACE;
	
CREATE INDEX USRSTATE_CONS_VALS 
	ON EMPINST.USER_STATE_LAIDX 
	(OBJIDSTR ASC, OBJID ASC, USRSTATE ASC, USRSTATE_UPDATED ASC)
	 TABLESPACE PROFINDEXTABSPACE; 

--
-- Main index for scanning
--
CREATE INDEX USRSTATE_IDX
	ON EMPINST.USER_STATE_LAIDX (USRSTATE ASC, USRSTATE_UPDATED ASC, OBJID ASC, OBJIDSTR ASC)
	 TABLESPACE PROFINDEXTABSPACE;

--
-- Board schema updates
--
{include.msgVector-fixup5.sql}

--
-- Add state field for lookaside index tables
--
INSERT INTO EMPINST.PROF_CONSTANTS VALUES ('LA_IDX_STATE', 'inconsistent');

------------------------------------------------
-- Update schema version
------------------------------------------------
UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 26, RELEASEVER='3.0.0.0' WHERE COMPKEY='Profiles';

COMMIT;

QUIT;
