-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2013                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- add column: see sn.homepage\lwp\dboard.sn.install\scripts\db\<dbtype>\fixup\fixup12.sql

-- see fixup31.sql
------
-- TENANT: create table, add constraitns, indexes
------

CREATE TABLE "EMPINST"."TENANT"  (						-- new
	"TENANT_KEY"		VARCHAR2(36)	NOT NULL,		-- new
	"TENANT_EXID"		VARCHAR2(256)	NOT NULL,		-- new
	"TENANT_NAME"		VARCHAR2(256)	NOT NULL,		-- new
	"TENANT_NAME_LOWER"	VARCHAR2(256)	NOT NULL,		-- new
	"TENANT_STATE"		NUMBER(19,0)	NOT NULL,		-- new
	"TENANT_CREATED"	TIMESTAMP NOT NULL,				-- new
	--"TENANT_CREATED_BY_KEY" VARCHAR2(36) NOT NULL,		-- new
	"TENANT_LASTUPDATE"	TIMESTAMP	NOT NULL,			-- new
	--"TENANT_LASTMOD_BY_KEY" VARCHAR2(36) NOT NULL,		-- new
	CONSTRAINT "TENANT_PK" PRIMARY KEY ("TENANT_KEY")	-- new
)
	TABLESPACE PROFREGTABSPACE;


CREATE UNIQUE INDEX EMPINST.TENANT_EXID_UDX ON EMPINST.TENANT
		(TENANT_EXID ASC) TABLESPACE PROFINDEXTABSPACE;

INSERT INTO EMPINST.TENANT(
	TENANT_KEY           ,
	TENANT_EXID          ,
	TENANT_NAME          ,
	TENANT_NAME_LOWER    ,
	TENANT_STATE         ,
	TENANT_CREATED       ,
	--TENANT_CREATED_BY_KEY,
	TENANT_LASTUPDATE
	--TENANT_LASTMOD_BY_KEY
)
VALUES(
	'00000000-0000-0000-0000-040508202233',
	'standard_tenant_guid',
	'Default Tenant',
	'default tenant',
	0,
	SYSDATE,
	-- no admin,
	SYSDATE
	-- no admin
);

------
-- EMPLOYEE: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.EMPLOYEE
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPPROF_TENT_UK  UNIQUE (PROF_KEY, TENANT_KEY);

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- GIVEN_NAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.GIVEN_NAME
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GVNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- SURNAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.SURNAME
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- DEPARTMENT: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.DEPARTMENT
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.DEPARTMENT DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT PDEPARTMENT_PK PRIMARY KEY (TENANT_KEY, PROF_DEPARTMENT_CODE);

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPT_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- ORGANIZATION: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.ORGANIZATION
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.ORGANIZATION DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_PK PRIMARY KEY (TENANT_KEY, PROF_ORGANIZATION_CODE);

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- COUNTRY: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.COUNTRY
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.COUNTRY DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (TENANT_KEY, PROF_ISO_COUNTRY_CODE);

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT CNTRY_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- EMP_TYPE: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EMP_TYPE
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.EMP_TYPE DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_PK PRIMARY KEY (TENANT_KEY, PROF_EMPLOYEE_TYPE);

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- WORKLOC: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.WORKLOC
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.WORKLOC DROP PRIMARY KEY CASCADE;

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_PK PRIMARY KEY (TENANT_KEY, PROF_WORK_LOC);

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- EVENTLOG: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EVENTLOG
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVLOG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- PROFILE_LOGIN: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_LOGIN
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT LOGIN_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

DROP INDEX EMPINST.LOGIN_UDX;

CREATE UNIQUE INDEX EMPINST.LOGIN_UDX ON EMPINST.PROFILE_LOGIN
		(PROF_LOGIN,TENANT_KEY) TABLESPACE PROFINDEXTABSPACE;

------
-- USER_PLATFORM_EVENTS: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS
	ADD TENANT_KEY VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT UPLTEV_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

-- see fixup32.sql
------
-- address MAIL a column length inconsistency (oracle specific cleanup)
------

DROP INDEX EMPINST.MAIL_IDX;
DROP INDEX EMPINST.MAIL_LOWER_IDX;
DROP INDEX EMPINST.ED_MAIL;

ALTER TABLE EMPINST.EMPLOYEE MODIFY (PROF_MAIL VARCHAR2(256));
ALTER TABLE EMPINST.EMPLOYEE MODIFY (PROF_MAIL_LOWER VARCHAR2(256));
ALTER TABLE EMPINST.EMP_DRAFT MODIFY (PROF_MAIL VARCHAR2(256));

-- we don't need to add back the mail index, should not be used
-- search cleanup -- CREATE INDEX EMPINST.MAIL_IDX ON EMPINST."EMPLOYEE" 
-- search cleanup -- 		("PROF_MAIL" ASC) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.MAIL_LOWER_IDX ON EMPINST."EMPLOYEE" 
		("PROF_MAIL_LOWER" ASC) TABLESPACE PROFINDEXTABSPACE;
CREATE INDEX EMPINST.ED_MAIL ON EMPINST."EMP_DRAFT" 
		("PROF_MAIL" ASC) TABLESPACE PROFINDEXTABSPACE;

COMMIT;

------
-- EMPLOYEE: add PROF_STATE column
------
ALTER TABLE EMPINST.EMPLOYEE ADD PROF_STATE INTEGER DEFAULT 0 NOT NULL;

COMMIT;

------
--  move state for inactive users from USER_STATE_LAIDX to EMPLOYEE
------
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '0' AND S.OBJIDSTR < '147' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '147' AND S.OBJIDSTR < '28f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '28f' AND S.OBJIDSTR < '3d7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '3d7' AND S.OBJIDSTR < '51e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '51e' AND S.OBJIDSTR < '666' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '666' AND S.OBJIDSTR < '7ae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '7ae' AND S.OBJIDSTR < '8f5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '8f5' AND S.OBJIDSTR < 'a3d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a3d' AND S.OBJIDSTR < 'b85' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b85' AND S.OBJIDSTR < 'ccc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ccc' AND S.OBJIDSTR < 'e14' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e14' AND S.OBJIDSTR < 'f5c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f5c' AND S.OBJIDSTR < '10a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '10a' AND S.OBJIDSTR < '11e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '11e' AND S.OBJIDSTR < '133' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '133' AND S.OBJIDSTR < '147' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '147' AND S.OBJIDSTR < '15c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '15c' AND S.OBJIDSTR < '170' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '170' AND S.OBJIDSTR < '185' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '185' AND S.OBJIDSTR < '199' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '199' AND S.OBJIDSTR < '1ae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '1ae' AND S.OBJIDSTR < '1c2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '1c2' AND S.OBJIDSTR < '1d7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '1d7' AND S.OBJIDSTR < '1eb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '1eb' AND S.OBJIDSTR < '1ff' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '1ff' AND S.OBJIDSTR < '214' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '214' AND S.OBJIDSTR < '228' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '228' AND S.OBJIDSTR < '23d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '23d' AND S.OBJIDSTR < '251' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '251' AND S.OBJIDSTR < '266' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '266' AND S.OBJIDSTR < '27a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '27a' AND S.OBJIDSTR < '28f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '28f' AND S.OBJIDSTR < '2a3' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '2a3' AND S.OBJIDSTR < '2b8' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '2b8' AND S.OBJIDSTR < '2cc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '2cc' AND S.OBJIDSTR < '2e1' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '2e1' AND S.OBJIDSTR < '2f5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '2f5' AND S.OBJIDSTR < '30a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '30a' AND S.OBJIDSTR < '31e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '31e' AND S.OBJIDSTR < '333' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '333' AND S.OBJIDSTR < '347' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '347' AND S.OBJIDSTR < '35c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '35c' AND S.OBJIDSTR < '370' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '370' AND S.OBJIDSTR < '385' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '385' AND S.OBJIDSTR < '399' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '399' AND S.OBJIDSTR < '3ae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '3ae' AND S.OBJIDSTR < '3c2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '3c2' AND S.OBJIDSTR < '3d7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '3d7' AND S.OBJIDSTR < '3eb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '3eb' AND S.OBJIDSTR < '3ff' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '3ff' AND S.OBJIDSTR < '414' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '414' AND S.OBJIDSTR < '428' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '428' AND S.OBJIDSTR < '43d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '43d' AND S.OBJIDSTR < '451' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '451' AND S.OBJIDSTR < '466' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '466' AND S.OBJIDSTR < '47a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '47a' AND S.OBJIDSTR < '48f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '48f' AND S.OBJIDSTR < '4a3' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '4a3' AND S.OBJIDSTR < '4b8' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '4b8' AND S.OBJIDSTR < '4cc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '4cc' AND S.OBJIDSTR < '4e1' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '4e1' AND S.OBJIDSTR < '4f5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '4f5' AND S.OBJIDSTR < '50a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '50a' AND S.OBJIDSTR < '51e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '51e' AND S.OBJIDSTR < '533' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '533' AND S.OBJIDSTR < '547' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '547' AND S.OBJIDSTR < '55c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '55c' AND S.OBJIDSTR < '570' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '570' AND S.OBJIDSTR < '585' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '585' AND S.OBJIDSTR < '599' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '599' AND S.OBJIDSTR < '5ae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '5ae' AND S.OBJIDSTR < '5c2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '5c2' AND S.OBJIDSTR < '5d7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '5d7' AND S.OBJIDSTR < '5eb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '5eb' AND S.OBJIDSTR < '5ff' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '5ff' AND S.OBJIDSTR < '614' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '614' AND S.OBJIDSTR < '628' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '628' AND S.OBJIDSTR < '63d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '63d' AND S.OBJIDSTR < '651' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '651' AND S.OBJIDSTR < '666' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '666' AND S.OBJIDSTR < '67a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '67a' AND S.OBJIDSTR < '68f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '68f' AND S.OBJIDSTR < '6a3' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '6a3' AND S.OBJIDSTR < '6b8' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '6b8' AND S.OBJIDSTR < '6cc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '6cc' AND S.OBJIDSTR < '6e1' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '6e1' AND S.OBJIDSTR < '6f5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '6f5' AND S.OBJIDSTR < '70a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '70a' AND S.OBJIDSTR < '71e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '71e' AND S.OBJIDSTR < '733' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '733' AND S.OBJIDSTR < '747' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '747' AND S.OBJIDSTR < '75c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '75c' AND S.OBJIDSTR < '770' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '770' AND S.OBJIDSTR < '785' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '785' AND S.OBJIDSTR < '799' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '799' AND S.OBJIDSTR < '7ae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '7ae' AND S.OBJIDSTR < '7c2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '7c2' AND S.OBJIDSTR < '7d7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '7d7' AND S.OBJIDSTR < '7eb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '7eb' AND S.OBJIDSTR < '7ff' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '7ff' AND S.OBJIDSTR < '814' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '814' AND S.OBJIDSTR < '828' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '828' AND S.OBJIDSTR < '83d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '83d' AND S.OBJIDSTR < '851' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '851' AND S.OBJIDSTR < '866' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '866' AND S.OBJIDSTR < '87a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '87a' AND S.OBJIDSTR < '88f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '88f' AND S.OBJIDSTR < '8a3' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '8a3' AND S.OBJIDSTR < '8b8' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '8b8' AND S.OBJIDSTR < '8cc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '8cc' AND S.OBJIDSTR < '8e1' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '8e1' AND S.OBJIDSTR < '8f5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '8f5' AND S.OBJIDSTR < '90a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '90a' AND S.OBJIDSTR < '91e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '91e' AND S.OBJIDSTR < '933' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '933' AND S.OBJIDSTR < '947' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '947' AND S.OBJIDSTR < '95c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '95c' AND S.OBJIDSTR < '970' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '970' AND S.OBJIDSTR < '985' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '985' AND S.OBJIDSTR < '999' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '999' AND S.OBJIDSTR < '9ae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '9ae' AND S.OBJIDSTR < '9c2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '9c2' AND S.OBJIDSTR < '9d7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '9d7' AND S.OBJIDSTR < '9eb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '9eb' AND S.OBJIDSTR < '9ff' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= '9ff' AND S.OBJIDSTR < 'a14' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a14' AND S.OBJIDSTR < 'a28' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a28' AND S.OBJIDSTR < 'a3d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a3d' AND S.OBJIDSTR < 'a51' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a51' AND S.OBJIDSTR < 'a66' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a66' AND S.OBJIDSTR < 'a7a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a7a' AND S.OBJIDSTR < 'a8f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'a8f' AND S.OBJIDSTR < 'aa3' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'aa3' AND S.OBJIDSTR < 'ab8' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ab8' AND S.OBJIDSTR < 'acc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'acc' AND S.OBJIDSTR < 'ae1' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ae1' AND S.OBJIDSTR < 'af5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'af5' AND S.OBJIDSTR < 'b0a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b0a' AND S.OBJIDSTR < 'b1e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b1e' AND S.OBJIDSTR < 'b33' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b33' AND S.OBJIDSTR < 'b47' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b47' AND S.OBJIDSTR < 'b5c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b5c' AND S.OBJIDSTR < 'b70' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b70' AND S.OBJIDSTR < 'b85' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b85' AND S.OBJIDSTR < 'b99' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'b99' AND S.OBJIDSTR < 'bae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'bae' AND S.OBJIDSTR < 'bc2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'bc2' AND S.OBJIDSTR < 'bd7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'bd7' AND S.OBJIDSTR < 'beb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'beb' AND S.OBJIDSTR < 'bff' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'bff' AND S.OBJIDSTR < 'c14' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'c14' AND S.OBJIDSTR < 'c28' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'c28' AND S.OBJIDSTR < 'c3d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'c3d' AND S.OBJIDSTR < 'c51' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'c51' AND S.OBJIDSTR < 'c66' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'c66' AND S.OBJIDSTR < 'c7a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'c7a' AND S.OBJIDSTR < 'c8f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'c8f' AND S.OBJIDSTR < 'ca3' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ca3' AND S.OBJIDSTR < 'cb8' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'cb8' AND S.OBJIDSTR < 'ccc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ccc' AND S.OBJIDSTR < 'ce1' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ce1' AND S.OBJIDSTR < 'cf5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'cf5' AND S.OBJIDSTR < 'd0a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd0a' AND S.OBJIDSTR < 'd1e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd1e' AND S.OBJIDSTR < 'd33' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd33' AND S.OBJIDSTR < 'd47' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd47' AND S.OBJIDSTR < 'd5c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd5c' AND S.OBJIDSTR < 'd70' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd70' AND S.OBJIDSTR < 'd85' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd85' AND S.OBJIDSTR < 'd99' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'd99' AND S.OBJIDSTR < 'dae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'dae' AND S.OBJIDSTR < 'dc2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'dc2' AND S.OBJIDSTR < 'dd7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'dd7' AND S.OBJIDSTR < 'deb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'deb' AND S.OBJIDSTR < 'dff' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'dff' AND S.OBJIDSTR < 'e14' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e14' AND S.OBJIDSTR < 'e28' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e28' AND S.OBJIDSTR < 'e3d' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e3d' AND S.OBJIDSTR < 'e51' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e51' AND S.OBJIDSTR < 'e66' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e66' AND S.OBJIDSTR < 'e7a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e7a' AND S.OBJIDSTR < 'e8f' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'e8f' AND S.OBJIDSTR < 'ea3' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ea3' AND S.OBJIDSTR < 'eb8' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'eb8' AND S.OBJIDSTR < 'ecc' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ecc' AND S.OBJIDSTR < 'ee1' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ee1' AND S.OBJIDSTR < 'ef5' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'ef5' AND S.OBJIDSTR < 'f0a' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f0a' AND S.OBJIDSTR < 'f1e' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f1e' AND S.OBJIDSTR < 'f33' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f33' AND S.OBJIDSTR < 'f47' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f47' AND S.OBJIDSTR < 'f5c' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f5c' AND S.OBJIDSTR < 'f70' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f70' AND S.OBJIDSTR < 'f85' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f85' AND S.OBJIDSTR < 'f99' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'f99' AND S.OBJIDSTR < 'fae' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'fae' AND S.OBJIDSTR < 'fc2' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'fc2' AND S.OBJIDSTR < 'fd7' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'fd7' AND S.OBJIDSTR < 'feb' );
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.OBJIDSTR FROM EMPINST.USER_STATE_LAIDX S WHERE S.USRSTATE = 1 AND S.OBJIDSTR >= 'feb' );
COMMIT;

-----
-- remove dynamic attributes
------
DELETE FROM EMPINST.DYNA_DEFS WHERE OBJFACET = 'sys.usrState.idx';
COMMIT;
DELETE FROM EMPINST.DYNA_DEFS WHERE OBJFACET = 'sys.usrOrgMem.idx';
COMMIT;
DELETE FROM EMPINST.DYNA_DEFS WHERE OBJFACET = 'sys.usrOrgAcl.idx';
COMMIT;

------
-- LAIDX may be incomplete, also pick up state from SURNAME table
------
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= '0' AND S.PROF_KEY < '199');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= '199' AND S.PROF_KEY < '333');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= '333' AND S.PROF_KEY < '4cc');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= '4cc' AND S.PROF_KEY < '666');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= '666' AND S.PROF_KEY < '7ff');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= '7ff' AND S.PROF_KEY < '999');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= '999' AND S.PROF_KEY < 'b33');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= 'b33' AND S.PROF_KEY < 'ccc');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= 'ccc' AND S.PROF_KEY < 'e66');
COMMIT;   
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 0 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 0 AND E.PROF_STATE = 1 AND S.PROF_KEY >= 'e66');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= '0' AND S.PROF_KEY < '199');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= '199' AND S.PROF_KEY < '333');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= '333' AND S.PROF_KEY < '4cc');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= '4cc' AND S.PROF_KEY < '666');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= '666' AND S.PROF_KEY < '7ff');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= '7ff' AND S.PROF_KEY < '999');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= '999' AND S.PROF_KEY < 'b33');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= 'b33' AND S.PROF_KEY < 'ccc');
COMMIT;
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= 'ccc' AND S.PROF_KEY < 'e66');
COMMIT;   
UPDATE EMPINST.EMPLOYEE E SET E.PROF_STATE = 1 WHERE E.PROF_KEY IN ( SELECT S.PROF_KEY FROM EMPINST.SURNAME S WHERE E.PROF_KEY = S.PROF_KEY AND S.PROF_USRSTATE = 1 AND E.PROF_STATE = 0 AND S.PROF_KEY >= 'e66');
COMMIT;

------
-- drop 'index' tables
------
DROP TABLE EMPINST.USER_STATE_LAIDX;
COMMIT;

DROP TABLE EMPINST.USER_ORGS_LAIDX;
COMMIT;

------
-- remove the s$usrState$v values, which are the only thing populated in DYNA_ATTRS
-- we just drop and recreate the table
------

DROP TABLE EMPINST.DYNA_ATTRS;
COMMIT;

CREATE TABLE EMPINST.DYNA_ATTRS (
	ATTRID		RAW(16) NOT NULL,
	OBJID		RAW(16) NOT NULL,
	ATTRFLAGS	INTEGER	NOT NULL,
	ATTRUPDATED	TIMESTAMP NOT NULL,
	ATTRKEY		VARCHAR2(256) NOT NULL,
	ATTRORDER	INTEGER NOT NULL,
	ATTRVAL		VARCHAR2(2000),
	ATTRVALEXT	BLOB
) TABLESPACE PROFREGTABSPACE;

CREATE UNIQUE INDEX EMPINST.DYNA_ATTRS_UIDX 
	ON EMPINST.DYNA_ATTRS (OBJID ASC, ATTRKEY ASC, ATTRORDER ASC)
	TABLESPACE PROFINDEXTABSPACE;

ALTER TABLE EMPINST.DYNA_ATTRS 
	ADD CONSTRAINT ATTR_PK PRIMARY KEY(ATTRID);
	
ALTER TABLE EMPINST.DYNA_ATTRS ADD CONSTRAINT DYNA_ATTR_FK FOREIGN KEY (OBJID)
	REFERENCES EMPINST.DYNA_OBJ_REF (OBJID)
	ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

------
-- drop obsolete indices from employee table
------

DROP INDEX EMPINST.EMP_UID_IDX;
-- DROP INDEX EMPINST.MAIL_IDX;
DROP INDEX EMPINST.SRC_UID_IDX;
DROP INDEX EMPINST.GW_EMAIL_LOWER_IDX;
DROP INDEX EMPINST.PREF_FNX;
DROP INDEX EMPINST.PREF_LNX;
DROP INDEX EMPINST.MGRIDX;
DROP INDEX EMPINST.GRPEMAIL_IDX;
DROP INDEX EMPINST.JOB_RESP_UID_IDX;
DROP INDEX EMPINST.ORG_UID_IDX;
DROP INDEX EMPINST.COUNTRY_UID_IDX;
DROP INDEX EMPINST.FAX_IDX;
DROP INDEX EMPINST.IPPHONE_IDX;
DROP INDEX EMPINST.MOBILE_IDX;
DROP INDEX EMPINST.PAGER_IDX;
DROP INDEX EMPINST.PHONE_IDX;
DROP INDEX EMPINST.WORKLOC_IDX;
COMMIT;

------
-- drop obsolete indices from other tables
------

DROP INDEX EMPINST.DEPARTMENT_WIZ1;
DROP INDEX EMPINST.ORGANIZATION_WIZ1;
DROP INDEX EMPINST.COUNTRY_WIZ1;
COMMIT;

------
-- add column to store user locale
------
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD PROF_LOCALE VARCHAR2(32);
COMMIT;

------
-- clear the scheduled tasks as they have changed
------
DELETE FROM EMPINST.PROFILES_SCHEDULER_TASK;
COMMIT;

DELETE FROM EMPINST.PROFILES_SCHEDULER_TREG;
COMMIT;

DELETE FROM EMPINST.PROFILES_SCHEDULER_LMGR;
COMMIT;

DELETE FROM EMPINST.PROFILES_SCHEDULER_LMPR;
COMMIT;

------
-- Drop LA_IDX_STATE to trigger photo regen and thumbnail creation
------
DELETE FROM EMPINST.DYNA_DEFS WHERE OBJFACET = 'sys.usrPhotoThumbnail.idx';
COMMIT;

------
-- Update schema version
------

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 33, RELEASEVER='4.0.0.0' WHERE COMPKEY='Profiles';
COMMIT;

------
-- Disconnect
------

QUIT;
