-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2016
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
USE PEOPLEDB
GO

GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.GIVEN_NAME TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.SURNAME TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PROFILE_EXTENSIONS TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILE_EXT_DRAFT TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PEOPLE_TAG TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.DEPARTMENT TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.ORGANIZATION TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.COUNTRY TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.EMP_TYPE TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.EMPLOYEE TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PHOTO TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PHOTOBKUP TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PHOTO_GUID TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.PRONUNCIATION TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.WORKLOC TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.SNPROF_SCHEMA TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.EMP_DRAFT TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.CHG_EMP_DRAFT TO PROFUSER;
GO 
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROF_CONNECTIONS TO PROFUSER;
GO 
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.SNPROF_SCHEMA TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROF_CONSTANTS TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.EVENTLOG TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILE_LOGIN TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILE_PREFS TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILE_LAST_LOGIN TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.TENANT TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.EMP_ROLE_MAP TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.EMP_UPDATE_TIMESTAMP TO PROFUSER;
GO

GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.USER_PLATFORM_EVENTS TO PROFUSER;
GO
--GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.USER_PLATFORM_EVENTS_INDEX TO PROFUSER;
--GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILES_SCHEDULER_TASK TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILES_SCHEDULER_LMGR TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILES_SCHEDULER_LMPR TO PROFUSER;
GO
GRANT DELETE,INSERT,SELECT,UPDATE,CONTROL ON EMPINST.PROFILES_SCHEDULER_TREG TO PROFUSER;
GO


