-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2013, 2014                             
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724-S68                                                          
USE PEOPLEDB;
GO

--====
-- TENANT_KEY re-indexing
--====

------
-- TENANT
------

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS DROP CONSTRAINT UPLTEV_TENANT_FK;
ALTER TABLE EMPINST.EMPLOYEE DROP CONSTRAINT EMPLOYEE_TENANT_FK;
ALTER TABLE EMPINST.GIVEN_NAME DROP CONSTRAINT GVNAME_TENANT_FK;
ALTER TABLE EMPINST.SURNAME DROP CONSTRAINT SURNAME_TENANT_FK;
ALTER TABLE EMPINST.PROFILE_EXTENSIONS DROP CONSTRAINT PROFEXT_TENT_FK;
ALTER TABLE EMPINST.PROFILE_EXT_DRAFT DROP CONSTRAINT PREXTDRFT_TENT_FK;
ALTER TABLE EMPINST.PEOPLE_TAG DROP CONSTRAINT PPLTAG_TENT_FK;
ALTER TABLE EMPINST.DEPARTMENT DROP CONSTRAINT DEPT_TENANT_FK;
ALTER TABLE EMPINST.ORGANIZATION DROP CONSTRAINT ORG_TENANT_FK;
ALTER TABLE EMPINST.COUNTRY DROP CONSTRAINT CNTRY_TENANT_FK;
ALTER TABLE EMPINST.EMP_TYPE DROP CONSTRAINT EMPTYPE_TENANT_FK;
ALTER TABLE EMPINST.PHOTO DROP CONSTRAINT PHOTO_TENT_FK;
ALTER TABLE EMPINST.PRONUNCIATION DROP CONSTRAINT PRONUNC_TENT_FK;
ALTER TABLE EMPINST.WORKLOC DROP CONSTRAINT WORKLOC_TENANT_FK;
ALTER TABLE EMPINST.EMP_DRAFT DROP CONSTRAINT EMPDRAFT_TENT_FK;
ALTER TABLE EMPINST.CHG_EMP_DRAFT DROP CONSTRAINT CHEMPDRFT_TENT_FK;
ALTER TABLE EMPINST.PROF_CONNECTIONS DROP CONSTRAINT CONNECT_TENT_FK;
ALTER TABLE EMPINST.EVENTLOG DROP CONSTRAINT EVLOG_TENANT_FK;
ALTER TABLE EMPINST.PROFILE_LOGIN DROP CONSTRAINT LOGIN_TENANT_FK;
ALTER TABLE EMPINST.PROFILE_PREFS DROP CONSTRAINT PROFPREF_TENT_FK;
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN DROP CONSTRAINT LASTLOGIN_TENT_FK
GO
ALTER TABLE EMPINST.TENANT DROP CONSTRAINT TENANT_PK;
GO
ALTER TABLE EMPINST.TENANT ADD CONSTRAINT TENANT_PK PRIMARY KEY (TENANT_KEY);
GO

------
-- EMPLOYEE
------
ALTER TABLE EMPINST.EMPLOYEE DROP CONSTRAINT EMPPROF_TENT_UK;
GO

ALTER TABLE EMPINST.EMPLOYEE DROP CONSTRAINT EMPLOYEE_PK;
GO
ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (PROF_KEY, TENANT_KEY);
GO
 
DROP INDEX EMP_GUID_UDX ON EMPINST.EMPLOYEE ;
GO
CREATE UNIQUE INDEX EMP_GUID_UDX ON EMPINST.EMPLOYEE 
		(PROF_GUID ASC, TENANT_KEY);
GO

DROP INDEX MAIL_LOWER_IDX ON EMPINST.EMPLOYEE ;
GO
CREATE INDEX MAIL_LOWER_IDX ON EMPINST.EMPLOYEE 
		(PROF_MAIL_LOWER ASC, TENANT_KEY);
GO

DROP INDEX UID_LOWER_UDX ON EMPINST.EMPLOYEE ;
GO
CREATE UNIQUE INDEX UID_LOWER_UDX ON EMPINST.EMPLOYEE 
		(PROF_UID_LOWER ASC, TENANT_KEY);
GO

DROP INDEX DISPNMX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX DISPNMX ON EMPINST.EMPLOYEE 
		(PROF_DISPLAY_NAME ASC, TENANT_KEY);
GO

DROP INDEX DISP_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX PROF_DISP_IDX ON EMPINST.EMPLOYEE 
		(PROF_KEY ASC, PROF_DISPLAY_NAME ASC, TENANT_KEY) INCLUDE (PROF_SURNAME, PROF_GIVEN_NAME);
GO

DROP INDEX PROF_SNGN_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX PROF_SNGN_IDX ON EMPINST.EMPLOYEE 
		(PROF_KEY ASC, PROF_SURNAME ASC, PROF_GIVEN_NAME ASC, TENANT_KEY);
GO

DROP INDEX PROF_GN2_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX PROF_GN2_IDX ON EMPINST.EMPLOYEE 
		(PROF_GIVEN_NAME ASC, PROF_KEY ASC, TENANT_KEY);
GO

DROP INDEX PROF_SN2_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX PROF_SN2_IDX ON EMPINST.EMPLOYEE 
		(PROF_SURNAME ASC, PROF_KEY ASC, TENANT_KEY);
GO

DROP INDEX LOGIN_LOWER_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX LOGIN_LOWER_IDX ON EMPINST.EMPLOYEE
                (PROF_LOGIN_LOWER ASC, TENANT_KEY);
GO

DROP INDEX MANAGER_UID_LOWER_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX MANAGER_UID_LOWER_IDX ON EMPINST.EMPLOYEE
                (PROF_MANAGER_UID_LOWER ASC, TENANT_KEY);
GO

DROP INDEX PROFILE_SEARCH_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX PROFILE_SEARCH_IDX ON EMPINST.EMPLOYEE
       		(PROF_LAST_UPDATE ASC, PROF_KEY ASC, TENANT_KEY);
GO

DROP INDEX PROF_TYPE_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX PROF_TYPE_IDX ON EMPINST.EMPLOYEE
       		(PROF_TYPE ASC, TENANT_KEY);
GO

DROP INDEX SRC_UID_LOWER_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX SRC_UID_LOWER_IDX ON EMPINST.EMPLOYEE
       		(PROF_SRC_UID_LOWER ASC, PROF_KEY ASC, TENANT_KEY);
GO

DROP INDEX PROF_SRC_UID_IDX ON EMPINST.EMPLOYEE;
GO
CREATE INDEX PROF_SRC_UID_IDX ON EMPINST.EMPLOYEE
		(PROF_SOURCE_UID ASC, TENANT_KEY);
GO
	
------
-- EMPINST.GIVEN_NAME
------

ALTER TABLE EMPINST.GIVEN_NAME DROP CONSTRAINT GIVEN_NAME_PK;
GO
ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GIVEN_NAME_PK PRIMARY KEY (PROF_KEY, PROF_GIVENNAME, TENANT_KEY);
GO

DROP INDEX GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME;
GO
CREATE INDEX GIVEN_NAME_IDX ON EMPINST.GIVEN_NAME (PROF_GIVENNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, TENANT_KEY);
GO

DROP INDEX GIVEN_NAME_IDX2 ON EMPINST.GIVEN_NAME;
GO
CREATE INDEX GIVEN_NAME_IDX2 ON EMPINST.GIVEN_NAME (PROF_USRSTATE ASC, PROF_GIVENNAME ASC, PROF_KEY ASC, TENANT_KEY);
GO

DROP INDEX GIVEN_NAMEX ON EMPINST.GIVEN_NAME;
GO
CREATE INDEX GIVEN_NAMEX ON EMPINST.GIVEN_NAME (PROF_KEY ASC, PROF_GIVENNAME ASC, PROF_USRSTATE ASC, TENANT_KEY);
GO

------
-- EMPINST.SURNAME
------

ALTER TABLE EMPINST.SURNAME DROP CONSTRAINT SURNAME_PK;
GO
ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_PK PRIMARY KEY (PROF_KEY, PROF_SURNAME, TENANT_KEY);
GO

DROP INDEX SURNAME_IDX ON EMPINST.SURNAME;
GO
CREATE INDEX SURNAME_IDX ON EMPINST.SURNAME (PROF_SURNAME ASC, PROF_KEY ASC, PROF_USRSTATE ASC, TENANT_KEY);
GO

DROP INDEX SURNAME_IDX2 ON EMPINST.SURNAME;
GO
CREATE INDEX SURNAME_IDX2 ON EMPINST.SURNAME (PROF_USRSTATE ASC, PROF_SURNAME ASC, PROF_KEY ASC, TENANT_KEY);
GO

DROP INDEX SURNAMEX ON EMPINST.SURNAME;
GO
CREATE INDEX SURNAMEX ON EMPINST.SURNAME (PROF_KEY ASC, PROF_SURNAME ASC, PROF_USRSTATE ASC, TENANT_KEY);
GO

------
-- EMPINST.PROFILE_EXTENSIONS
------

ALTER TABLE EMPINST.PROFILE_EXTENSIONS DROP CONSTRAINT PROFILE_EXTENSIONS_PK;
GO
ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROF_EXT_PK PRIMARY KEY (PROF_KEY, PROF_PROPERTY_ID, TENANT_KEY);
GO

--DROP INDEX PROFILE_EXTENSIONS_IDX ON EMPINST.PROFILE_EXTENSIONS;
--GO
CREATE INDEX PROFILE_EXTENSIONS_IDX ON EMPINST.PROFILE_EXTENSIONS 
		(PROF_KEY ASC, TENANT_KEY);
GO

DROP INDEX PROFILE_EXTENSIONS_IDX2 ON EMPINST.PROFILE_EXTENSIONS ;
GO
CREATE INDEX PROFILE_EXTENSIONS_IDX2 ON EMPINST.PROFILE_EXTENSIONS 
		(PROF_NAME ASC, PROF_PROPERTY_ID ASC, TENANT_KEY);
GO

------
-- EMPINST.PROFILE_EXT_DRAFT
------

ALTER TABLE EMPINST.PROFILE_EXT_DRAFT DROP CONSTRAINT EXT_DRAFT_PK;
GO
ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT EXT_DRAFT_PK PRIMARY KEY (PROF_KEY, PROF_UPDATE_SEQUENCE, TENANT_KEY);
GO

------
-- EMPINST.PEOPLE_TAG
------

DECLARE @SQL VARCHAR(4000)
SET @SQL = 'ALTER TABLE EMPINST.PEOPLE_TAG DROP CONSTRAINT |ConstraintName| '

SET @SQL = REPLACE(@SQL, '|ConstraintName|', ( SELECT   name
                                               FROM     sysobjects
                                               WHERE    xtype = 'PK'
                                                        AND parent_obj = OBJECT_ID('EMPINST.PEOPLE_TAG')
                                             ))

EXEC (@SQL)
GO
--ALTER TABLE EMPINST.PEOPLE_TAG DROP CONSTRAINT PEOPLE_TAG_PK ;
--GO
ALTER TABLE EMPINST.PEOPLE_TAG ADD CONSTRAINT PEOPLE_TAG_PK PRIMARY KEY (PROF_TAG_ID, TENANT_KEY);
GO

DROP INDEX PEOPLE_TAG_IDX ON EMPINST.PEOPLE_TAG;
GO
CREATE INDEX PEOPLE_TAG_IDX ON EMPINST.PEOPLE_TAG 
		(PROF_TAG ASC, PROF_TARGET_KEY ASC, TENANT_KEY) ;
GO

DROP INDEX PEOPLE_TAG_IDX2 ON EMPINST.PEOPLE_TAG;
GO
CREATE INDEX PEOPLE_TAG_IDX2 ON EMPINST.PEOPLE_TAG 
		(PROF_TARGET_KEY ASC, PROF_TAG ASC, PROF_SOURCE_KEY ASC, TENANT_KEY);
GO
		
DROP INDEX PEOPLE_TAG_UDX ON EMPINST.PEOPLE_TAG;
GO
CREATE UNIQUE INDEX PEOPLE_TAG_UDX ON EMPINST.PEOPLE_TAG 
		(PROF_SOURCE_KEY ASC, PROF_TARGET_KEY ASC, PROF_TAG ASC, TENANT_KEY) ;
GO

------
-- EMPINST.DEPARTMENT
------

ALTER TABLE EMPINST.DEPARTMENT DROP CONSTRAINT DEPARTMENT_PK;
GO
ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY (PROF_DEPARTMENT_CODE ASC, TENANT_KEY);
GO

------
-- EMPINST.ORGANIZATION
------

ALTER TABLE EMPINST.ORGANIZATION DROP CONSTRAINT ORG_PK;
GO
ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_PK PRIMARY KEY (PROF_ORGANIZATION_CODE, TENANT_KEY);
GO

------
-- EMPINST.COUNTRY
------

ALTER TABLE EMPINST.COUNTRY DROP CONSTRAINT COUNTRY_PK;
GO
ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (PROF_ISO_COUNTRY_CODE, TENANT_KEY);
GO

------
-- EMPINST.EMP_TYPE
------

ALTER TABLE EMPINST.EMP_TYPE DROP CONSTRAINT EMPTYPE_PK;
GO
ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_PK PRIMARY KEY (PROF_EMPLOYEE_TYPE, TENANT_KEY);
GO

------
-- EMPINST.PHOTO
------

ALTER TABLE EMPINST.PHOTO DROP CONSTRAINT PHOTO_TENT_UK;
GO

ALTER TABLE EMPINST.PHOTO DROP CONSTRAINT PHOTO_PK ;
GO
ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_PK PRIMARY KEY (PROF_KEY, TENANT_KEY);
GO

DROP INDEX PHOTOIDX ON EMPINST.PHOTO;
GO
CREATE INDEX PHOTOIDX ON EMPINST.PHOTO 
		(PROF_UPDATED DESC, TENANT_KEY);
GO

------
--EMPINST.PRONUNCIATION
------

ALTER TABLE EMPINST.PRONUNCIATION DROP CONSTRAINT PRONUNC_TENT_UK;
GO

ALTER TABLE EMPINST.PRONUNCIATION DROP CONSTRAINT PRONOUNCE_PK ;
GO
ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNCIATION_PK PRIMARY KEY (PROF_KEY, TENANT_KEY);
GO

DROP INDEX PRONOUNCEIDX ON EMPINST.PRONUNCIATION;
GO
CREATE INDEX PRONOUNCEIDX ON EMPINST.PRONUNCIATION 
		(PROF_UPDATED DESC, TENANT_KEY);
GO

------
-- EMPINST.WORKLOC
------

ALTER TABLE EMPINST.WORKLOC DROP CONSTRAINT WORKLOC_PK ;
GO
ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_PK PRIMARY KEY (PROF_WORK_LOC, TENANT_KEY);
GO

------
-- EMPINST.EMP_DRAFT 
------

-- MWC changed name
ALTER TABLE EMPINST.EMP_DRAFT DROP CONSTRAINT PK_EMP_DRAFT;
GO
DROP INDEX EMP_DRAFT_PK ON EMPINST.EMP_DRAFT;
GO
ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMP_DRAFT_PK PRIMARY KEY (PROF_KEY, PROF_UPDATE_SEQUENCE, TENANT_KEY);
GO

DROP INDEX ED_MAIL ON EMPINST.EMP_DRAFT;
GO
CREATE INDEX ED_MAIL ON EMPINST.EMP_DRAFT 
		(PROF_MAIL ASC, TENANT_KEY);
GO

DROP INDEX ED_DISPNMX ON EMPINST.EMP_DRAFT;
GO
CREATE INDEX ED_DISPNMX ON EMPINST.EMP_DRAFT 
		(PROF_DISPLAY_NAME ASC, TENANT_KEY);
GO

DROP INDEX ED_UPDATE_IDX ON EMPINST.EMP_DRAFT;
GO
CREATE INDEX ED_UPDATE_IDX ON EMPINST.EMP_DRAFT 
		(PROF_LAST_UPDATE DESC, PROF_KEY DESC, PROF_UPDATE_SEQUENCE DESC, TENANT_KEY);
GO

------
-- EMPINST.PROF_CONNECTIONS
------

DECLARE @SQL VARCHAR(4000)
SET @SQL = 'ALTER TABLE EMPINST.PROF_CONNECTIONS DROP CONSTRAINT |ConstraintName| '

SET @SQL = REPLACE(@SQL, '|ConstraintName|', ( SELECT   name
                                               FROM     sysobjects
                                               WHERE    xtype = 'PK'
                                                        AND parent_obj = OBJECT_ID('EMPINST.PROF_CONNECTIONS')
                                             ))

EXEC (@SQL)
GO
--ALTER TABLE EMPINST.PROF_CONNECTIONS DROP CONSTRAINT CONNECTIONS_PK;
--GO
ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECTIONS_PK PRIMARY KEY (PROF_CONNECTION_ID, TENANT_KEY);
GO

DROP INDEX CONN_UDX ON EMPINST.PROF_CONNECTIONS;
GO
CREATE UNIQUE INDEX CONN_UDX ON EMPINST.PROF_CONNECTIONS
		(PROF_SOURCE_KEY, PROF_TARGET_KEY, PROF_TYPE, TENANT_KEY);
GO

-- Main index to select a users connections for showing friends in UI
DROP INDEX CONN_INDEX1 ON EMPINST.PROF_CONNECTIONS;
GO
CREATE INDEX CONN_INDEX1 ON EMPINST.PROF_CONNECTIONS
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_LASTMOD DESC, PROF_TARGET_KEY ASC, TENANT_KEY);
GO

-- Friends in common; get list of connection keys 'isConnection' query
DROP INDEX CONN_INDEX2 ON EMPINST.PROF_CONNECTIONS ;
GO
CREATE INDEX CONN_INDEX2 ON EMPINST.PROF_CONNECTIONS 
	(PROF_SOURCE_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_TARGET_KEY ASC, PROF_LASTMOD ASC, TENANT_KEY);
GO

-- Reverse index for deletes
DROP INDEX CONN_REV_IDX ON EMPINST.PROF_CONNECTIONS ;
GO
CREATE INDEX CONN_REV_IDX ON EMPINST.PROF_CONNECTIONS 
	(PROF_TARGET_KEY ASC, PROF_TYPE ASC, PROF_STATUS ASC, PROF_SOURCE_KEY ASC, PROF_LASTMOD ASC, TENANT_KEY);
GO

------
-- EMPINST.EVENTLOG
------

ALTER TABLE EMPINST.EVENTLOG DROP CONSTRAINT EVLOG_PK ;
GO
ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVENTLOG_PK PRIMARY KEY (EVENT_KEY, TENANT_KEY);
GO

DROP INDEX EVLOG_TYPE_IDX ON EMPINST.EVENTLOG;
GO
CREATE INDEX EVLOG_TYPE_IDX ON EMPINST.EVENTLOG
	(EVENT_TYPE, CREATED, EVENT_KEY, TENANT_KEY);
GO

DROP INDEX EVLOG_AUDIT_IDX ON EMPINST.EVENTLOG;
GO
CREATE INDEX EVLOG_AUDIT_IDX ON EMPINST.EVENTLOG
	(ISSYSEVENT ASC, EVENT_KEY ASC, TENANT_KEY);
GO

------
--EMPINST.PROFILE_LOGIN
------

DROP INDEX LOGIN_UDX ON EMPINST.PROFILE_LOGIN;
GO
ALTER TABLE EMPINST.PROFILE_LOGIN DROP CONSTRAINT LOGIN_PK;
GO
ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT PROFILE_LOGIN_PK PRIMARY KEY (PROF_KEY, PROF_LOGIN, TENANT_KEY);
GO
CREATE UNIQUE INDEX LOGIN_UDX ON EMPINST.PROFILE_LOGIN
		(PROF_LOGIN,TENANT_KEY);
GO

------
-- EMPINST.PROFILE_PREFS
------

ALTER TABLE EMPINST.PROFILE_PREFS DROP CONSTRAINT PROFPREF_TENT_UK;
GO
ALTER TABLE EMPINST.PROFILE_PREFS DROP CONSTRAINT PREF_PK;
GO
ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFILE_PREFS_PK PRIMARY KEY (PROF_KEY, PROF_PREFID, TENANT_KEY);
GO

------
-- EMPINST.PROFILE_LAST_LOGIN
------

ALTER TABLE EMPINST.PROFILE_LAST_LOGIN DROP CONSTRAINT LASTLOGIN_TENT_UK;
GO
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN DROP CONSTRAINT LAST_LOGIN_PK;
GO
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LAST_LOGIN_PK UNIQUE (PROF_KEY, TENANT_KEY);
GO

------
-- EMPINST.USER_PLATFORM_EVENTS
------

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS DROP CONSTRAINT PLATFORM_EVENTS_PK ;
GO
ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT PLATFORMEVENTS_PK PRIMARY KEY (EVENT_KEY, TENANT_KEY);
GO

------
-- TENANT_KEY = TENANT_EXID
------

UPDATE EMPINST.TENANT SET TENANT_EXID = '00000000-0000-0000-0000-040508202233' WHERE TENANT_KEY = '00000000-0000-0000-0000-040508202233';
GO

----

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT UPLTEV_TENANT_FK 
  FOREIGN KEY (TENANT_KEY) REFERENCES EMPINST.TENANT (TENANT_KEY)
  ON DELETE CASCADE
GO
ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GVNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PROFILE_EXTENSIONS ADD CONSTRAINT PROFEXT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PROFILE_EXT_DRAFT ADD CONSTRAINT PREXTDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PEOPLE_TAG ADD CONSTRAINT PPLTAG_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPT_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT CNTRY_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PHOTO ADD CONSTRAINT PHOTO_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PRONUNCIATION ADD CONSTRAINT PRONUNC_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.EMP_DRAFT ADD CONSTRAINT EMPDRAFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.CHG_EMP_DRAFT ADD CONSTRAINT CHEMPDRFT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PROF_CONNECTIONS ADD CONSTRAINT CONNECT_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVLOG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT LOGIN_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PROFILE_PREFS ADD CONSTRAINT PROFPREF_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE EMPINST.PROFILE_LAST_LOGIN ADD CONSTRAINT LASTLOGIN_TENT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO
--ALTER TABLE EMPINST.USER_PLATFORM_EVENTS CHECK CONSTRAINT UPLTEV_TENANT_FK
--GO

------
-- Update schema version
------
UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 39, RELEASEVER='4.5.0.0' WHERE COMPKEY='Profiles';
GO


