-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2012                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- add column: see sn.homepage\lwp\dboard.sn.install\scripts\db\<dbtype>\fixup\fixup12.sql

-- 5724-S68                                                          
USE PEOPLEDB;
GO

------
-- TENANT: create table, add constraints, indexes
------

CREATE TABLE EMPINST.TENANT  (
	TENANT_KEY			NVARCHAR(36)	NOT NULL,
	TENANT_EXID			NVARCHAR(256)	NOT NULL,
	TENANT_NAME			NVARCHAR(256)	NOT NULL,
	TENANT_NAME_LOWER	NVARCHAR(256)	NOT NULL,
	TENANT_STATE		NUMERIC(19,0)	NOT NULL,
	TENANT_CREATED		DATETIME NOT NULL,
	--TENANT_CREATED_BY_KEY" NVARCHAR(36) NOT NULL,
	TENANT_LASTUPDATE	DATETIME	NOT NULL,
	--TENANT_LASTMOD_BY_KEY NVARCHAR(36) NOT NULL,
	CONSTRAINT TENANT_PK PRIMARY KEY (TENANT_KEY)
);
GO

INSERT INTO EMPINST.TENANT(
	TENANT_KEY           ,
	TENANT_EXID          ,
	TENANT_NAME          ,
	TENANT_NAME_LOWER    ,
	TENANT_STATE         ,
	TENANT_CREATED       ,
	--TENANT_CREATED_BY_KEY,
	TENANT_LASTUPDATE
	--TENANT_LASTMOD_BY_KEY
)
VALUES(
	'00000000-0000-0000-0000-040508202233',
	'standard_tenant_guid',
	'Standard Tenant',
	'standard tenant',
	0,
	CURRENT_TIMESTAMP,
	-- no admin,
	CURRENT_TIMESTAMP
	-- no admin
);
GO

CREATE UNIQUE INDEX TENANT_EXID_UDX ON EMPINST.TENANT (TENANT_EXID ASC);
GO

------
-- EMPLOYEE: add TENANT columns and FK constraints
------
ALTER TABLE EMPINST.EMPLOYEE
	ADD TENANT_KEY NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233';
GO

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPPROF_TENT_UK UNIQUE (PROF_KEY, TENANT_KEY);
GO

ALTER TABLE EMPINST.EMPLOYEE ADD CONSTRAINT EMPLOYEE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

------
-- GIVEN_NAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.GIVEN_NAME
	ADD TENANT_KEY NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233';
GO

ALTER TABLE EMPINST.GIVEN_NAME ADD CONSTRAINT GVNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

------
-- SURNAME: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.SURNAME
	ADD TENANT_KEY NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233';
GO

ALTER TABLE EMPINST.SURNAME ADD CONSTRAINT SURNAME_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

------
-- DEPARTMENT: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.DEPARTMENT
	ADD TENANT_KEY NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233';
GO

ALTER TABLE EMPINST.DEPARTMENT DROP CONSTRAINT DEPT_PK;
GO

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY (TENANT_KEY,PROF_DEPARTMENT_CODE ASC);
GO

ALTER TABLE EMPINST.DEPARTMENT ADD CONSTRAINT DEPT_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

------
-- ORGANIZATION: add TENANT columns and FK constraints
--   this table has an implicit primary key name. drop and recreate
------
exec sp_rename 'EMPINST.ORGANIZATION', 'ORGANIZATION_T'
GO

 CREATE TABLE EMPINST.ORGANIZATION  (
	PROF_ORGANIZATION_CODE 	NVARCHAR(64) NOT NULL, 
	PROF_ORGANIZATION_TITLE	NVARCHAR(256),
	TENANT_KEY				NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'
); 
GO

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_PK PRIMARY KEY (TENANT_KEY,PROF_ORGANIZATION_CODE);
GO

ALTER TABLE EMPINST.ORGANIZATION ADD CONSTRAINT ORG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

CREATE INDEX ORGANIZATION_WIZ1 ON EMPINST.ORGANIZATION 
		(PROF_ORGANIZATION_TITLE ASC);
GO

GRANT DELETE,INSERT,SELECT,UPDATE ON EMPINST.ORGANIZATION TO PROFUSER;
GO

-- copy data from old to new table --
INSERT INTO EMPINST.ORGANIZATION
(PROF_ORGANIZATION_CODE,PROF_ORGANIZATION_TITLE) 
 SELECT 
 PROF_ORGANIZATION_CODE,PROF_ORGANIZATION_TITLE
 FROM EMPINST.ORGANIZATION_T;
GO

-- drop old table -- 
DROP TABLE EMPINST.ORGANIZATION_T;
GO

------
-- COUNTRY: add TENANT columns and FK constraints
--   this table has an implicit primary key name. drop and recreate
------

exec sp_rename 'EMPINST.COUNTRY', 'COUNTRY_T'
GO

CREATE TABLE EMPINST.COUNTRY  (
	PROF_ISO_COUNTRY_CODE	NVARCHAR(3) NOT NULL, 
	PROF_COUNTRY_DESC		NVARCHAR(256),
	TENANT_KEY				NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'
);
GO

ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (TENANT_KEY,PROF_ISO_COUNTRY_CODE);
GO


ALTER TABLE EMPINST.COUNTRY ADD CONSTRAINT CNTRY_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

CREATE INDEX COUNTRY_WIZ1 ON EMPINST.COUNTRY 
		(PROF_COUNTRY_DESC ASC);
GO

-- copy data from old to new table --
INSERT INTO EMPINST.COUNTRY
(PROF_ISO_COUNTRY_CODE,PROF_COUNTRY_DESC) 
 SELECT 
 PROF_ISO_COUNTRY_CODE,PROF_COUNTRY_DESC
 FROM EMPINST.COUNTRY_T;
GO

-- drop old table -- 
DROP TABLE EMPINST.COUNTRY_T;
GO

------
-- EMP_TYPE: add TENANT columns and FK constraints
--   this table has an implicit primary key name. drop and recreate
------

exec sp_rename 'EMPINST.EMP_TYPE', 'EMP_TYPE_T'
GO

 CREATE TABLE EMPINST.EMP_TYPE  (
	PROF_EMPLOYEE_TYPE		NVARCHAR(256) NOT NULL, 
	PROF_EMPLOYEE_DESC		NVARCHAR(256),
	TENANT_KEY				NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233'
);
GO

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_PK PRIMARY KEY (TENANT_KEY,PROF_EMPLOYEE_TYPE);
GO

ALTER TABLE EMPINST.EMP_TYPE ADD CONSTRAINT EMPTYPE_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- copy data from old to new table --
INSERT INTO EMPINST.EMP_TYPE
(PROF_EMPLOYEE_TYPE,PROF_EMPLOYEE_DESC) 
 SELECT 
 PROF_EMPLOYEE_TYPE,PROF_EMPLOYEE_DESC
 FROM EMPINST.EMP_TYPE_T;
GO

-- drop old table -- 
DROP TABLE EMPINST.EMP_TYPE_T;
GO

------
-- WORKLOC: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.WORKLOC
	ADD TENANT_KEY NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233';

ALTER TABLE EMPINST.WORKLOC DROP CONSTRAINT WORKLOC_PK;
GO

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_PK PRIMARY KEY (TENANT_KEY,PROF_WORK_LOC);
GO

ALTER TABLE EMPINST.WORKLOC ADD CONSTRAINT WORKLOC_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

------
-- EVENTLOG: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.EVENTLOG
	ADD TENANT_KEY NVARCHAR(36) DEFAULT '00000000-0000-0000-0000-040508202233' NOT NULL;
GO

ALTER TABLE EMPINST.EVENTLOG ADD CONSTRAINT EVLOG_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

------
-- PROFILE_LOGIN: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.PROFILE_LOGIN
	ADD TENANT_KEY NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233';
GO

ALTER TABLE EMPINST.PROFILE_LOGIN ADD CONSTRAINT LOGIN_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

  -- this was the name in 3.0
DROP INDEX EMPINST.PROFILE_LOGIN.LOGIN_DX;
GO


CREATE UNIQUE INDEX LOGIN_UDX ON EMPINST.PROFILE_LOGIN (PROF_LOGIN,TENANT_KEY);
GO

------
-- USER_PLATFORM_EVENTS: add TENANT columns and FK constraints
------

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS
	ADD TENANT_KEY NVARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-040508202233';
GO

ALTER TABLE EMPINST.USER_PLATFORM_EVENTS ADD CONSTRAINT UPLTEV_TENANT_FK FOREIGN KEY (TENANT_KEY)
	REFERENCES EMPINST.TENANT(TENANT_KEY)
	ON DELETE CASCADE ON UPDATE NO ACTION;
GO

------
-- Update schema versions
------

UPDATE EMPINST.SNPROF_SCHEMA SET DBSCHEMAVER= 31, RELEASEVER='4.0.0.0' WHERE COMPKEY='Profiles';
GO
